### ISSUE TITLE
"Update Asset" doesn't apply feed producer changes

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#1034]
If you add/remove users to the 'feed producers' list, clicking on 'Update Asset' does not apply the changes, only the "Update" button within the feed producer tab.

![image](https://user-images.githubusercontent.com/15861527/35006873-afdd97a2-faef-11e7-8a9d-c41385c54cf7.png)

See - no feed producer info from the "Update Asset" button.
![image](https://user-images.githubusercontent.com/15861527/35006877-b34e7e10-faef-11e7-8817-b4ca4a16a828.png)

Working- feed producer info in the "Update" button.
![image](https://user-images.githubusercontent.com/15861527/35006992-0ffb8a04-faf0-11e7-8e58-66f7725ad460.png)

**Comment by HarukaMa** [comment]
This is already fixed in #1029. I've removed the separate update and reset button and used the buttons on upper right corner. Rest assured that there will not be another "update asset" operations even if nothing is changed; only changed parts will be updated in the PR.

If you trust my web wallet you could try https://b.mrx.im to see it in action.

**Comment by grctest** [comment]
@HarukaMa Excellent work, I'll close this issue then 👍
