### ISSUE TITLE
[2.75][ahdigital] Exchange Header Tweaks

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1035]
- [x] Replace large flip icon with '/'
- [x] Place flip icon next to label. Give it a lighter hover state to indicate that it is a control.
- [x] Place a star to the right of the flipper. Hover state should be yellow. When the market is in a user's favorites, the star should be yellow, otherwise gray.

> Second yellow star shown is only for color reference

<img width="323" alt="screen shot 2018-01-16 at 7 41 37 pm" src="https://user-images.githubusercontent.com/1254810/35021263-b6f86d22-faf5-11e7-9dff-0f5892ce6d5a.png">

## Colors

<img width="1020" alt="screen shot 2018-01-16 at 7 45 22 pm" src="https://user-images.githubusercontent.com/1254810/35021286-d92802a4-faf5-11e7-8243-6a8a369dfd23.png">

- [ ] Do not alter color of `Latest`. Leave it fixed (white on the dark theme) regardless of price action.
- [ ] Do not alter color of `Volume`. Leave it fixed (white on the dark theme).

## Responsive Design

Change the order of removing elements in the header as browser narrows. Remove in this order:

- [x] Margin Call Price
- [x] Call Limit
- [x] Settlement
- [x] 24hr Volume
- [x] 24hr Change
- [x] Latest and Trading Pair should never be hidden regardless of browser width

**Comment by ahdigital** [comment]
I can have a crack at this.

**Comment by ahdigital** [comment]
@wmbutler Pull request submitted: [https://github.com/bitshares/bitshares-ui/pull/1038](url)

**Comment by wmbutler** [comment]
Any chance you could post a licecap? Just speeds iterations when the PR is remote.

**Comment by ahdigital** [comment]
## Shuffle button
Relocated shuffle button to be inline with the stat label and added hover state.

![shuffle-button](https://user-images.githubusercontent.com/3088454/35141635-727b7c8e-fcf3-11e7-9d30-0d1d8b2d2a30.gif)

## Star market
Added star market button to be inline with stat label.

![star-market](https://user-images.githubusercontent.com/3088454/35141673-9da99e68-fcf3-11e7-99b2-7427f0a69fc2.gif)


## Responsive stat order
On browser window resize, updated the order in which stats are hidden and made it so they hide one by one and not just limited to groups according to small/medium resolution.

![stat-wrapping-order](https://user-images.githubusercontent.com/3088454/35141720-da41c9a4-fcf3-11e7-9a48-79e4466e3dda.gif)

## Layout header
Updated layout header so that the 'create account' link doesn't wrap so early.

![create-account-wrap](https://user-images.githubusercontent.com/3088454/35141753-f3d3d95c-fcf3-11e7-9909-2281b25009e5.gif)

**Comment by wmbutler** [comment]
Looks great.

- [ ] Settlement should be white

**Comment by ahdigital** [comment]
@wmbutler No problem - pull request updated.

![settlement-stat](https://user-images.githubusercontent.com/3088454/35210510-6e722224-ff4a-11e7-9e20-03a6dba08546.png)

**Comment by wmbutler** [comment]
I added .25 for this. Can you also look at the font size for the market? It feels like it's smaller than the fonts for the pricing. I'd like all the fonts on that header to be the same size.

**Comment by ahdigital** [comment]
Good spot, it was 2px smaller in size. I've updated and also adjusted the alignments so that they're in alignment.

![exchange-header-text](https://user-images.githubusercontent.com/3088454/35264508-eab42880-0014-11e8-80f1-f83d8a13dc81.png)

**Alignment:**

![alignment](https://user-images.githubusercontent.com/3088454/35264602-4a27f5bc-0015-11e8-8006-1f892e519337.png)

Pull request is updated.

**Comment by ahdigital** [comment]
@wmbutler @svk31  PR #1038 was merged into staging - can this issue be closed now?

**Comment by wmbutler** [comment]
Need your BTS address for payment @ahdigital

**Comment by ahdigital** [comment]
dom-0
