### ISSUE TITLE
[.5][gibbsfromncis]Asset price display bug in staging

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1069]
I was going though some testing on staging and I noticed that PEERPLAYS has a value in the new staging code but not on the current production code. Feel free to use account `billbutler` for testing since it has this asset in it.

**Comment by gibbsfromncis** [comment]
@wmbutler I see nobody wants to take this issue. I would like to help you solve this high priority issue but if you provide me more details because I totally don't understand what should be done.

**Comment by wmbutler** [comment]
I think it can be resolved by implementing #1061. This is a particularly strange issue though because if you compare my peerplays balance on the staging branch to that of the current 180115 release, they are different values. This leads me to believe that something changed about how we calculate balances on the staging branch.

**Comment by gibbsfromncis** [comment]
@wmbutler okay I'll investigate what happened but I don't understand why it's bug? I suppose you don't see the volume because it doesn't have the `price(BTS)` on staging.

**Comment by gibbsfromncis** [comment]
@wmbutler I've spent some time on investigation and now I'm ready to say that after this commit: https://github.com/bitshares/bitshares-ui/commit/0ba3468  by @svk31 we have the result of what you can see now. 

As I said above I don't understand why you think it's a bug. As I found out on current Deploy was something wrong about market prices and @svk31 fixed that. So now you can see the correct data about market prices and now there is an ability to calculate `Volume` by `Price`.

@wmbutler @svk31 I suppose you know each other so could you discuss this issue and let me know about results and should I do/fix something or not. 

@wmbutler if you don't want me to do something regarding this task (except #1061, I will work on this task on upcoming Sprint) I would be glad if you close this task and I get reward because I spend time on investigating.

**Comment by wmbutler** [comment]
OK, I just assumed it was a bug. Maybe it was a bug in the current version and staging fixed it.

**Comment by wmbutler** [comment]
Fine with me. I have no idea which is correct. It is unfortunate that my balance will be skewed to an incorrect value after this release is made official.

**Comment by wmbutler** [comment]
More evidence to support my assertion:

## Version 180115 OPEN.EOS price

![screen shot 2018-02-01 at 1 10 10 pm](https://user-images.githubusercontent.com/1254810/35698035-8d88e6a2-0751-11e8-8339-e855124afedd.png)


## Staging Branch OPEN.EOS price

![screen shot 2018-02-01 at 1 10 00 pm](https://user-images.githubusercontent.com/1254810/35698010-7759f31c-0751-11e8-870d-1cfe8173d349.png)

**Comment by gibbsfromncis** [comment]
@wmbutler looks interesting. Will investigate. Please increase the estimate to `1h` because I've spend already around 1h for investigating previous issue.

**Comment by svk31** [comment]
Oh I think I see why this happened, most likely when I changed the stats calculation from a manual calculation from market_history to values from the get_ticker api call the values changed. So inactive markets now get price values while before they were set to null. Not really something it's worth changing; the current values reflect the most recent prices, although in edge cases like PEERPLAYS those may not be very "real" since the market is disabled.

**Comment by gibbsfromncis** [comment]
@wmbutler @svk31  closed this task. Should I investigate this issue or leave it for @svk31 ?

**Comment by wmbutler** [comment]
@svk31 can you exclude inactive markets from the calculation? Advancing to next Sprint, but a hotfix would be nice. No telling how many ppl this affects.

**Comment by wmbutler** [comment]
This is a serious high priority bug in light of the OPEN.EOS discrepancy.

**Comment by gibbsfromncis** [comment]
@wmbutler okay, I'll take a look this tomorrow asap and will try to make fix. But I suppose the issue is on so deep level like issue about `PEERPLAYS` so I'm not sure if I can fix this without any help. 

Anyway I'll notify you asap.

**Comment by wmbutler** [comment]
@gibbsfromncis note that it's probably related to @svk31 earlier comment so don't kill yourself over it. It's probably buried pretty deep.

**Comment by gibbsfromncis** [comment]
@wmbutler I suppose it is. But as I want to be the superman on bitshares-ui I should start sometimes to get on deep level. So why not to do it tomorrow? :) 

@svk31 as I said I'll try tomorrow but I suppose we need you to work on it. I'll report back to you tomorrow

**Comment by gibbsfromncis** [comment]
@wmbutler it's hard to reproduce because I see all the values..

The screenshot was taken from the current Build:
<img width="641" alt="screenshot 2018-02-02 03 32 32" src="https://user-images.githubusercontent.com/35899973/35713832-c6d18e5a-07c9-11e8-8d8a-7186e637cfe6.png">

**Comment by svk31** [comment]
It could also be because the get_ticker API call has recently seen some fixes, but if your API node is not running the latest version you don't have those changes and you might get some incorrect values from the API.

**Comment by wmbutler** [comment]
I wonder if this is a caching issue of some sort.

**Comment by wmbutler** [comment]
It is. Incognito mode resolved. Clearing cache and re-importing wallet.

**Comment by wmbutler** [comment]
PEERPLAYS is still an issue on multiple nodes. I think OPEN.EOS was a cache issue of some sort.

**Comment by gibbsfromncis** [comment]
@wmbutler if you want me to do something I'm here. For now I did all what I can and wait for any news regarding this task if you need my help again.

**Comment by wmbutler** [comment]
I'm going to had this over to @svk31 since he's probably the only one who understands the potential fix.

**Comment by gibbsfromncis** [comment]
@wmbutler okay. Please keep in mind about 0.5h of my work on this task.

**Comment by gibbsfromncis** [comment]
@wmbutler I can't see this task on invoice for previous Sprint. You didn't include it because I didn't fix this bug or you forget to include this one? if you didn't include this to invoice because I didn't fix this bug - I'm OK with it. But I would be happy if you can pay for this one because nobody wanted to take this high priority bug and I've spent around 1 hour of my time for investigating.

**Comment by wmbutler** [comment]
Issues do not get paid until they are resolved and closed.

**Comment by wmbutler** [comment]
Non-issue now that we can hide assets. Credit @gibbsfromncis .5
