### ISSUE TITLE
[.5][ahdigital] User name and menu icon partially disappear on small window size 

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1083]
I can propose to hide username to Icon and display only balance. But the balance can be long too so it may be better to hide both and if user wants to see account name/balance/accounts list he can tap on account Icon. 

<img width="347" alt="screenshot 2018-01-29 23 02 06" src="https://user-images.githubusercontent.com/35899973/35536900-8e8aa03c-0548-11e8-8558-90f2b6bc4e5e.png">

**Comment by wmbutler** [comment]
I think it would be better to show the username and the burger, but hide the dashboard icon (and let it be the first item in the burger.

**Comment by gibbsfromncis** [comment]
@wmbutler assign to me please

**Comment by ahdigital** [comment]
Wondering if this will conflict with #1082 that I'm working on? We might end up having to merge two burger menu implementations down the line.

**Comment by gibbsfromncis** [comment]
@ahdigital what about his one - https://github.com/bitshares/bitshares-ui/pull/1084 ? I've changed the section with username and hamburger. Will it conflict too? I've changes Header.jsx.

Actually I don't understand why did you touch hamburger and what are the changes you had to do with that...

**Comment by ahdigital** [comment]
I haven't done anything with the burger menu *yet*, but I have seen it mentioned in a ticket (and consolidated) that I'm about to work on. E.g. #1082 and #917.

However, with all of this said - I thought I'd have to implement a burger menu from scratch because when I visit the wallet with cookies, sessions, local storage etc. cleared it isn't visible. Instead, 'Create account' is shown.

Therefore, I don't think my initial concerns are much to be worried about.

**Comment by gibbsfromncis** [comment]
@wmbutler please reassign this task to @ahdigital.

@ahdigital I've made changes #1084 to this menu already so make sure your staging will be up to date when you start to work on.

**Comment by wmbutler** [comment]
This is a great observation. As stated in another issue, the "Create Account" is a little redundant since we have a banner for this. There are plenty of cases where I think users might want to be able to navigate the menu (and optionally supply their account name or even someone else's account name) to track various aspects of that account without logging in. Since the blockchain is publicly accessible, this could be possible if we allowed for it.

We would need an obvious way for a user to get tot he create account banner if they wanted to but this is another matter entirely.

**Comment by startailcoon** [comment]
This issue is no longer present after the latest release.

**Comment by ahdigital** [comment]
Yes, I fixed as part of PR #1140.

**Comment by wmbutler** [comment]
Closing and will credit with this Sprint.
