### ISSUE TITLE
[0.25] Display Asset names exactly as they exist

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-ui#116]
_From @iPerky on February 1, 2017 17:57_

Bitshares community wallet needs to be impartial, clear and open!
Our wallet should clearly mark all assets and the differences between them.

It it misleading for BitShares to drop "open" for all openledger assets (or for any other asset).

This issue is about clarity and transparency. It has no reflection on the great work of both Ronny (of Openledger) and @svk (GUI developer).

_Copied from original issue: bitshares/bitshares-core#228_

**Comment by vikramrajkumar** [comment]
_From @fractalnode on February 1, 2017 19:18_

What name will the next similar company choose for their IOU.BTC then?

**Comment by vikramrajkumar** [comment]
_From @jonnybitcoin on February 1, 2017 20:3_

In the backend the OPEN. will remain. It's just easier in the front end to not have it while openledger has no competition. 
When openledger has some competition we can change it back again.

**Comment by vikramrajkumar** [comment]
_From @iPerky on February 2, 2017 12:36_

In my opinion this is a bad precedent.

**Comment by vikramrajkumar** [comment]
_From @grctest on February 2, 2017 13:1_

Is this not promoting OL over other EBA providers? Will this not confuse users who have trade.btc instead of open.btc?

If there was an automatic bridge of [<Any_EBA_Provider>.BTC -> BTC (when trading BTC:<whatever_token>] then this would make more sense & be fairer, no?

**Comment by vikramrajkumar** [comment]
_From @dnotestein on February 2, 2017 13:4_

To me it's simply confusing from the perspective of things like BitBTC. I find it confusing now to figure out if an asset is OPEN.BTC or BitBTC (which has a symbol of BTC). This is reason why I don't like dropping the prefixes.

**Comment by vikramrajkumar** [comment]
_From @abitmore on February 2, 2017 13:35_

I like the old behavior which lists
* bitCNY
* open.CNY
* iou.CNY

**Comment by vikramrajkumar** [comment]
_From @abitmore on February 2, 2017 13:38_

A little off-topic here, since this repo has been renamed to bitshares-core, I think it's better to tag future GUI releases in the bitshares-ui repository directly.

**Comment by vikramrajkumar** [comment]
_From @dnotestein on February 2, 2017 13:47_

yes, I also liked the display as mentioned by abitmore

**Comment by vikramrajkumar** [comment]
_From @kenCode-de on February 25, 2017 20:36_

I agree 100%. Let's please find a way to be transparent, and show the full asset names, without having to rely on a Tooltip or other event.

**Comment by vikramrajkumar** [comment]
_From @oxarbitrage on April 6, 2017 16:51_

Agree with @abitmore this discussion is a bit off-topic here as @jonnybitcoin mentioned the backend will not change the asset names.

How the GUI display the assets should be discussed here:
https://github.com/bitshares/bitshares-ui/issues

Anyways, by now this seems to be resolved in by removing the OPEN prefix from the wallet:

![228_1](https://cloud.githubusercontent.com/assets/21685097/24765793/8f353236-1acf-11e7-852c-bacd94be498b.png)

A user can only know the full symbol name by checking the url:

![228_2](https://cloud.githubusercontent.com/assets/21685097/24765800/98db7160-1acf-11e7-8909-124dbd6e5fd1.png)

There is nothing to do from the bitshares-core side. The issue i think should be moved or closed.

**Comment by vikramrajkumar** [comment]
_From @dnotestein on April 6, 2017 17:3_

The proper action is to move it, IMO.

**Comment by wmbutler** [comment]
This is a policy discussion.

**Comment by iPerky** [comment]
Masking asset names does not scream professionalism!

**Comment by wmbutler** [comment]
We should stop dragging our feet on this and do it. If nobody is opposed to it, I think we should do it.

**Comment by svk31** [comment]
So revert to showing the full asset names? OPEN.X?

**Comment by wmbutler** [comment]
Yes. I'll post this issue in the forums and make sure it's agreed upon but I think as the reference wallet, we are really left with no other option.

**Comment by btsfav** [comment]
+1 revert to open.x

**Comment by knifewine** [comment]
+1 for displaying true asset name (e.g revert to open.x)

**Comment by Xeldal** [comment]
I'm not a fan of either option.  Both create their own mess.
  
I'd like to see a separation of the various EXchanges(gateways) by prefix.  Like we do in the deposit/withdraw page.  Select which EX(gateway) you want to view and it only shows you those particular token pairs dropping the prefix for easy viewing.  The prefix would be clearly stated at the top of the page perhaps to reinforce what EX you were viewing.

The last selectable EX option would be ALL EXchanges, which would show all available pairs without filtering and leaving the prefix visible.  Like you're suggesting doing now.  Perhaps this is the default view until otherwise selected.  

Ideally each gateway will have their own frontend displaying however they want of course.  The reference client need not necessarily make any effort to beautify all the particular gateway options. But some effort should be make to be as easily understandstood and straightforward as possible.  Closely resembling what people are used to.  So filtering the prefixes makes sense to me.

The gateways selection would only filter it's own prefix so if OPEN.BTC were trading with RUDEX.PPY  While inside the OPEN EX(gateway) selection you'd see BTC : RUDEX.PPY  or BTC : bitBTC etc.

Maybe MPA's would have their own EX option where only counterparty-free smart tokens are displayed.

The fact that you have the option to select different EXchanges all within the same client reinforces what the DEX really is.  Put this option on it's own page front and center and the idea may click in peoples minds.  You may have more gateways spring up wanting to be on that page. 

IDK, just throwing out some thoughts / ideas.

**Comment by svk31** [comment]
I like Xeldal's ideas, but that's a bigger refactoring than the current scope of the issue and I'm not really a fan of introducing artificial limitations in what markets and deposit/withdrawal options are available for example.

**Comment by iPerky** [comment]
Xeldal's idea's should be taken on board and implemented by every third party front end / gateway.

This is a reference wallet and all assets should be treated equally by using their full name.
Masking asset names also makes arbitrage a pain.

**Comment by wmbutler** [comment]
I totally agree that the long term solution should be that the bitshares reference wallet treats the various exchanges like brands. This would help everyone understand how exchanges relate to Bitshares. It could be more easily communicated that they can go from one exchange to another through the deposit/withdraw option rather than trading across an exchange. At @svk31 points out, this issue is not about that type of refactoring. It's about treating all exchanges equally by exposing the full symbol name.

**Comment by svk31** [comment]
Implemented here: https://github.com/bitshares/bitshares-ui/commit/5dff5e2ca34bc3c992bc3842ec68026a8dc8d728

**Comment by landry314** [comment]
Well, if we all have agreed that we need to use open.ASSET consistently then I think that conforming the bitASSET names as I discuss in issue #388 is a logical next step here.
