### ISSUE TITLE
[1] Incorrect values in alert when closing margin position

### ISSUE THREAD

**Issue by dandehavilland** [bitshares/bitshares-ui#1194]
Is this the correct repo for issues like this?

<img width="408" alt="screen shot 2018-02-21 at 14 50 59" src="https://user-images.githubusercontent.com/95854/36483640-010f221a-1717-11e8-8f77-d73c86aed634.png">

**Comment by dandehavilland** [comment]
This was using wallet.bitshares.org.

**Comment by wmbutler** [comment]
Does this happen regularly or was this a one-time event? Unlikely we can solve this unless it can be reproduced reliably.

**Comment by dandehavilland** [comment]
That was my first attempt at opening/closing a margin position, but I just tried again and managed to reproduce the issue. This time I noticed that the 'close position' confirmation screen has the same issue:

<img width="697" alt="screen shot 2018-02-21 at 19 55 05" src="https://user-images.githubusercontent.com/95854/36499360-4913f764-1741-11e8-97d5-ba866cf5081f.png">

And the subsequent alert:
<img width="410" alt="screen shot 2018-02-21 at 19 55 17" src="https://user-images.githubusercontent.com/95854/36499378-5544d0bc-1741-11e8-8fda-55d51fe6fcf1.png">


The initial report was for 1000 bitUSD, this second try was for 1 bitUSD.

**Comment by abitmore** [comment]
This looks like an integer overflow issue (while displaying).

**Comment by startailcoon** [comment]
I think this is related to this section of the code

https://github.com/bitshares/bitshares-ui/blob/66678211f96b6b5e1f8c842092997d3996c314d7/app/components/Account/MarginPositions.jsx#L47-L84

When an asset update is negative, it will display the numbers in overflow.

**Comment by svk31** [comment]
Thanks for that hint @startailcoon, allowed me to reproduce it. The error is caused by a change in the bitsharesjs lib, this commit here: https://github.com/bitshares/bitsharesjs/commit/2f08691f85dbf54daa9dbc7d8942c71db7f30dc0 and PR 
https://github.com/bitshares/bitsharesjs/pull/16

The assumption that we don't need signed ints appears to be wrong, as the asset struct requires negative numbers in the specific case of call order updates. @abitmore any hints on how to resolve this?

**Comment by svk31** [comment]
Think I figured out a way to fix it:

https://github.com/bitshares/bitshares-ui/issues/1194
