### ISSUE TITLE
[2.5][ahdigital][8][startailcoon] UX Nodes list layout and validation

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1223]
Related to #1149

**Comment by ahdigital** [comment]
### Node switch widget
I'm proposing an enhancement to the connection summary in the bottom right corner of the viewport. On hover over we could open a widget that shows the next best nodes to switch to in terms of latency (Lowest to highest). To keep the list A) succinct, and B) useful, only nodes which are low or medium latency should be shown.

The switch icon would allow the user to easily change node and would be color coded to denote latency.

There would be a link at the bottom of the widget that could route a user to the full node settings page. This way, we could potentially return to what we previously had whereby a click on the connection summary took you through the general settings page (something I found useful).

![node switch widget](https://user-images.githubusercontent.com/3088454/37474198-b1230624-2867-11e8-9027-344856db6424.png)

### Node settings (automatically select)
The first update I would make to the nodes settings page is to rename it to 'Nodes' instead of 'Access'. It just seems more relevant.

Secondly, the proposed design gives users a toggle switch to let them decide if they want to automatically or manually select nodes. Automatic would be the default for new users and the benefit of this is that the page appears very straight forward at first glance.

It's a good idea I think to append to the toggle switch label a count of the total nodes available though, just to make it clear that there's not just one node available.

![nodes auto connect](https://user-images.githubusercontent.com/3088454/37474868-47d36392-2869-11e8-94e3-d47b9dd664f7.png)

### Node settings (manually select + available)
If the user toggles off the automatic node selection they will be presented with a tab bar grouping nodes into 'available nodes', 'hidden nodes' and 'my nodes'. The nodes would be listed in tabular format, with actions visible without the need to hover - preventing any responsive/mobile issues.

There is a switch icon which when clicked would update the active node.

![nodes manually connect available](https://user-images.githubusercontent.com/3088454/37475199-04513134-286a-11e8-9244-2ba1caac418b.png)

### Node settings (manually select + hidden)
Hidden nodes would be listed on this 'hidden nodes' tab. Any unreachable node would see it's switch button omitted.

![nodes manually connect hidden](https://user-images.githubusercontent.com/3088454/37475280-37211b06-286a-11e8-9e7a-91f00181a78b.png)

### Node settings (manually select + my nodes)
I felt it would be easier for the user to have a tab specifically for listing their own nodes as it would made finding them amongst larger lists easier. I guess also in case the user forgets what name they gave it.

One thing I wasn't sure about however (which I did include in the mock up) is that should users be able to hide their own nodes? I'm leaning towards not, but wanted to keep the experience consistent.

![nodes manually connect my nodes](https://user-images.githubusercontent.com/3088454/37475436-a2d76044-286a-11e8-9e37-65c5f74640b7.png)

@wmbutler, these mock ups have taken longer than the single hour plus I'm expecting some feedback on this so could we increase the hours?

**Comment by wmbutler** [comment]
Yes, please increase accordingly. I only have one question. Otherwise, looks great:

If the user selects closest available node, does it pick from all nodes from the list below?

- Available Nodes
- Hidden Nodes
- My Nodes

**Comment by ahdigital** [comment]
Thanks. Not sure I can edit the title though.

**Comment by ahdigital** [comment]
> If the user selects closest available node, does it pick from all nodes from the list below?

Automatic selection should ignore hidden nodes and those that are unreachable.

Whether or not your own nodes should be included is up for debate, but personally I'd say no.

What do you think?

**Comment by startailcoon** [comment]
If this needs a cooker for claim, I can take this task.

**Comment by wmbutler** [comment]
- @ahdigital just tell me total hours for UX and I'll add it
- I'd say no to the hidden and you own nodes as well
- @startailcoon it's yours

**Comment by ahdigital** [comment]
Increase to 2.5 please. Thanks.

Agreed on the second point - over to you @startailcoon then!

**Comment by wmbutler** [comment]
- [ ] We need a way to manually reconnect to the currently selected node
- [ ] We may want to extend the Disconnected warning timer to double its current setting

**Comment by ahdigital** [comment]
> We need a way to manually reconnect to the currently selected node.

I accounted for this already but didn't show mock up. Will post in the morning but essentially where the connected icon is on the active node, I made another icon (disconnected) which when clicked performs the manual reconnect.

**Comment by ahdigital** [comment]
Something like this is how I saw the manual reconnect working.

![image](https://user-images.githubusercontent.com/3088454/37513519-36514190-28fd-11e8-80ae-a4d9773a6efe.png)

**Comment by startailcoon** [comment]
This will be an interesting task to do, but it's a great mockup and I hope to be able to go trough this task this milestone.

**Comment by startailcoon** [comment]
## Current Progress

There is still work to be done, but here is an update on the progress

### A few notes
- When a user toggles auto OFF the app will stay on the current node it has, but view the full list
- When a user toggle auto ON the app will connect to the automatic node selection, choosing the best node and hide the full list

![bitshares-nodes](https://user-images.githubusercontent.com/12114550/37790589-44ae7dfc-2e07-11e8-861f-e52b85b93842.gif)

**Comment by sschiessl-bcp** [comment]
Great progress here!

I have been digging through routerTransition and refactored it a bit while working on #1228. There will be an easy way to recreate the ping for all nodes. Maybe you could add a button for that and leave it disabled, I can fill in the logic then.

**Comment by startailcoon** [comment]
@sschiessl-bcp @ahdigital where should such a button be placed?

**Comment by startailcoon** [comment]
@ahdigital Do we have an iconset for the connected/disconnected icons?

**Comment by startailcoon** [comment]
![image](https://user-images.githubusercontent.com/12114550/37862351-afff7c7e-2f4b-11e8-9711-02b379b814e5.png)

**Comment by ahdigital** [comment]
> @ahdigital Do we have an iconset for the connected/disconnected icons?

Typicons is what I have suggested on the style guide.

**Comment by startailcoon** [comment]
### Regarding the popup
- Should it contain the current connected node?
- Should it display the "Automatic select node" toggle? 
  - Always or only when off/on?
- How many nodes should be displayed?
- What nodes should it display?
  - Visible/Hidden/Private?

**Comment by startailcoon** [comment]
# Popup Preview
This is a preview of the work done so far. Some styling is still required, but functionality is complete.

![bitshares-nodes_popup](https://user-images.githubusercontent.com/12114550/37864130-d0b20d14-2f6a-11e8-9a75-6011d0bdde1a.gif)

**Comment by startailcoon** [comment]
Small modification for mobile compatibility 

![](https://i.imgur.com/cSc4iOw.jpg)

**Comment by startailcoon** [comment]
I have not done any disconnected logic as I think it falls outside the scope of this UI task. There are work done with this in other issues and I think it's best to wait for the result of these.

**Comment by wmbutler** [comment]
Just to clarify, a low latency node is a good thing. Making sure you have your terminology straight @ahdigital

**Comment by ahdigital** [comment]
Where it says 23 nodes available, is that dynamic?

**Comment by wmbutler** [comment]
I would imagine, yes, that it's based on the array.length

**Comment by startailcoon** [comment]
It's a count of all available nodes added minus the two testnet nodes and the local. So it's dynamic yes.

**Comment by sschiessl-bcp** [comment]
With the refactoring [here](https://github.com/blockchainprojects/bitshares-ui/tree/access-setting) you will be able to update all pings like this (exact API might get refactored again, I ll wait for feedback):
`import {routerTransitioner} from "../../routerTransition";
routerTransitioner.doLatencyUpdate().then(()=>{});`

**Comment by startailcoon** [comment]
@sschiessl-bcp I will test this and push an update to the PR tomorrow

**Comment by sschiessl-bcp** [comment]
The refactoring has to be approved first,  carefully not to create dependencies on the PR.

But please do test :)

**Comment by sschiessl-bcp** [comment]
The refactoring has to be approved first,  careful not to create dependencies on the PR.

But please do test :)

**Comment by wmbutler** [comment]
Hope this makes it into the release. @svk31

**Comment by litepresence** [comment]
Lay users shouldn't even be presented with node connectivity issue.   There is no need for the common trader to have access and it simply complicates connectivity and ads undue burden and mental overhead for noobs.    The solution needn't be to make changing nodes more accessible; the nodes issue should  should be handled as a background process by the UI as an stochastic AI function.   Further, the way the reference UI is handling nodes leaves anyone open to the possibility that one of the whitelisted nodes goes rogue; offers tainted price feeds to unsuspecting users and they trade on oblivious.  

please, play with microDEX: this is how connectivity to nodes should work.

My orderbooks are orders of magnitude faster than the reference UI and validated by the fact they're switching websockets multiple times per second.  

I have a copy right now of microDEX that has been streaming live books updated multiple times per second for days... along side running copy of the reference UI that I have to manually switch nodes on twice an hour to keep happy.   There is no reason for it to be that way. 

https://github.com/litepresence/extinction-event/blob/master/microDEX/microDEX.py
