### ISSUE TITLE
[.25] Request: Remove prepended 'bit' from smartcoin name

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#1281]
![image](https://user-images.githubusercontent.com/15861527/37176703-1126245a-2315-11e8-95b4-b6a6db69aa3e.png)

Hey,

As highlighted in the above screenshot (in red), the wallet currently prepends 'bit' infront of 'Hertz'; isn't the 'bit' technically reserved for the core smartcoins? Can this be optional or removed? The token isn't called bitHertz anywhere else.

Cheers 👍

**Comment by startailcoon** [comment]
@wmbutler what is our view of how to sepperate core MPA against other MPA coins?

Is all MPA coins prepended the `bit` name today?

**Comment by happyconcepts** [comment]
All the MPA coins issued by `committee-account` are prepended with bit.

**Comment by grctest** [comment]
@happyconcepts Would that include MPA created by an user, then ownership transferred to the committee-account?

IMO only the core FIAT MPA originally created by the committee-account should have this prepended bit text. It could be statically set in the UI for a set list of core MPA, instead of all committee-owned MPA having 'bit' prepended?

**Comment by startailcoon** [comment]
This can easily be done by replacing the custom bit append code with using <AssetName /> instead, as it appends the bit to all assets that should have it.

**Comment by abitmore** [comment]
Add a tag in `description` field, e.g. "no bit prefix", then UI can skip displaying "bit" for it.

**Comment by startailcoon** [comment]
@abitmore why du that when AssetName already works for this?

And its still a bug, not a feature

**Comment by abitmore** [comment]
BitAssets are there due to historical reasons and are well acknowledged by early participants. It's related to brand recognition, IMHO should not be decided by the UI team alone. Personally I'm against removing "bit" from all market pegged assets in the reference wallet, other 3rd party hosted wallets can have their own preferences. However, it's true that some (new) assets aren't that good to be named bit-something. So, IMHO it's a feature that adding "bit" to some assets but not to all. Perhaps better if there is an option in settings that can be changed by individual user. Then this need UX design. And we need tutorials and etc.

**Comment by abitmore** [comment]
>All the MPA coins issued by `committee-account` are prepended with bit.

Yes, this is the rule.

**Comment by wmbutler** [comment]
All I care about is consistency. Bottom line, should this asset be displayed as bit or not?

**Comment by startailcoon** [comment]
Hertz does not have bit prepended to it elsewhere, and is exactly how it's supposed to be. The market tabs are one place that does this check in a different manner rather than using `<AssetName />` that does this correctly.

That is why I'm saying we need to change it to using that function instead.

**Comment by wmbutler** [comment]
@abitmore I truly don't have an opinion on this. Should they all say bitHERTZ or should they all say HERTZ?

**Comment by abitmore** [comment]
HERTZ. @startailcoon is correct.

**Comment by gibbsfromncis** [comment]
PR: #1315
<img width="758" alt="screenshot 2018-03-13 04 45 20" src="https://user-images.githubusercontent.com/35899973/37321610-5e0345c0-2679-11e8-9842-57237e33467a.png">

**Comment by svk31** [comment]
Sorry @gibbsfromncis but I ran into this in your other PR here: https://github.com/bitshares/bitshares-ui/pull/1314 after looking at your bit assets check. Turns out we had some incorrect logic in a lot of places, which was the cause of this issue among other things. I fixed that and it's made your PR for this issue unnecessary.

**Comment by svk31** [comment]
Took me a bit longer to fix since it impacted other places too, bumped to 0.5 hours
