### ISSUE TITLE
[8] Send modal 'To' field doesn't save account name

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#1299]
![image](https://i.imgur.com/aOCTfa2.gif)

When entering the username into the 'to' field, if you don't click on the name in the drop down then the name is not saved in the text box value field, but the member type (basic/ltm) and their account number remain behind.

Perhaps users may misspell a send account name (misspelling an exchange account name for example), then not have the opportunity to visually spot their error.

**Comment by startailcoon** [comment]
I came across this as well. Its because the typeahead returns the value directly and not when you select one.

The typeahead needs

**Comment by grctest** [comment]
What do you think about a down-chevron next to 'BTS' in the quantity & fee fields, so as to draw attention to the drop down menus? Think it's be too intrusive?

**Comment by wmbutler** [comment]
This is a feature for some and a bug for others. Some would say that you need to click or press enter to select the asset because you may risk replacing the currently entered asset otherwise.

I'd suggest that if we have a single exact account match that a `onBlur` event should should replace the value in the input fields.

**Comment by grctest** [comment]
@wmbutler Perhaps the top right '<Member Type><Account ID>' data shouldn't apply as a valid target in the send modal until you've fully clicked on a matching account name in the drop down sub menu?

**Comment by wmbutler** [comment]
> @wmbutler Perhaps the top right 'Member Type, Account ID' data shouldn't auto-apply as a valid target in the send modal until you've fully clicked on a matching account name in the drop down sub menu?

Agreed. It should only apply to the value that has been entered into the final input field.

**Comment by startailcoon** [comment]
There is a bug in this.

I agree with you both here. Bill, the account should not change unless you actively click on on in the list you've searched for. But today it fills in all the data from a possible find even if you don't click.

This means you can search and click on a username, then search again and don't click. You will then have all the new users details everywhere, except for the input box that doesn't overwrite unless you clicked on the name.

This can be devastating for users if they don't notice it on the confirmation screen.

**Comment by wmbutler** [comment]
@startailcoon if the user searches for `bill` and we see in the typeahead:

```
billy
billbutler
billiam
```
Presumably, the first item will be highlighted. What should happen when the typeahead loses focus? The user could do 4 things to lose focus:

```
tab
enter
click
offclick
```

How should each of these react? Seems like:

```
enter - select the item
click - select the item
offclick - do not select the item
tab - ambiguous, could be argued both ways
```

**Comment by startailcoon** [comment]
It'd go for

```
enter - select first or highlighted item
click - select highlighted and clicked item
offclick - do nothing at all
tab - select highligted item OR tabulate in the typeahead list if possible
```

**Comment by wmbutler** [comment]
More to clarify:

- `enter` Is the first item in the list always highlighted? I think it has to be.
- `tab` I'm less sure about this but agree it's probably the right call. I have no idea what `tabulate in the typeahead` means.

**Comment by startailcoon** [comment]
* `enter` - Agree, as first item should be highlighted it should be that one. If the mouse moves over another item, highlighting it, that one should be the one that's selected (not sure how much of an issue this is though).
* `tab` - With "tabulate in the typeahead", I mean that tab should move to the next item in the list, rather than loosing focus of the list. This is where enter comes in to action as well, making the selection when you're done.

**Comment by wmbutler** [comment]
I have to disagree on the tab. The tab key should move the user to the next input field on the form. The question is:

Should the tab key action select the currently highlighted item or should it move to the next field without selecting the item.

**Comment by wmbutler** [comment]
I set this at 1.5 because this issue requires careful consideration and testing.

**Comment by startailcoon** [comment]
>  The tab key should move the user to the next input field on the form.

Good point, I have to agree on that as you point it out. Then I think it should *not* select an item in the list at all.

**Comment by wmbutler** [comment]
Do you want to claim this?

**Comment by startailcoon** [comment]
Sure, I'll take this

**Comment by startailcoon** [comment]
## Preview

I'm going for a change in how the Typeahead is displaying the account status.
Currently it's sending back the input, displaying the account status, which isn't a good idea as we've seen here.

The account status will instead be listed directly in the typeahead, like the following.

**NOTE THAT THIS IS NOT FINAL**

![image](https://user-images.githubusercontent.com/12114550/37554081-eaad522e-29d3-11e8-9e34-5715a8246555.png)

**Comment by startailcoon** [comment]
## Final Results
#### Requested Hours: 5.5hrs

I've been required to rewrite most of the logic of the AccountSelector component since it wasn't working together with the Typeahead component, hence the higher requested hours.

Significant failsafe work has also had to be done to make sure nothing is broken in other parts of the app.

The AccountSelector now has a "selectedAccount" and a "inputName" to sepperate the two from each others. Only when an item is selected by a click or enter is the selectedAccount stored and displayed on the upper right.

The typeahead component now visualize the status of an account directly in the list.

In the licecap you can't see that I'm using `Enter` or `Tab`, but enter will select the first item in the list unless it's disabled while tab will just jump to the next input field without storing any changes.



## Licecap

![bitshares-newtypeahead](https://user-images.githubusercontent.com/12114550/37560582-761c78aa-2a3b-11e8-8e59-14a566be11df.gif)

![bitshares-newtypeahead2](https://user-images.githubusercontent.com/12114550/37560687-46010a12-2a3d-11e8-9dec-9b2ad488bdc3.gif)

**Comment by startailcoon** [comment]
There is some tricky aspects where the `<AccountSelector>` is in various sections of the app, that I've had to put some additional time in. I expect a final result to not be to far away and will submit a PR when it's done.

**Comment by wmbutler** [comment]
Thanks. This is exactly the kind of meticulous work we need. Really happy with your work @startailcoon

**Comment by startailcoon** [comment]
I'm happy to do the work, and won't sign of unless it works as expect in all aspects of the app.

**Comment by startailcoon** [comment]
## Update

The Typeahead/AccountSelector is used widely on other parts of the app, so I've enabled some other parts of the app to use typeahead, while some other have not.

To enable typeahead, simply use `typeahead={true}`. Some legacy code may need to be worked on to enable it fully, but has worked out of the box on the onces I've used it one now.

## Legacy Send
![bitshares-typeahead_legacysend](https://user-images.githubusercontent.com/12114550/37570891-14e0a866-2af6-11e8-9504-b94c5574ee2f.gif)

## Modal Send
![bitshares-typeahead_modalsend](https://user-images.githubusercontent.com/12114550/37570898-1eb56552-2af6-11e8-83dd-c18431b4f360.gif)

## Proxy for Voting
![bitshares-typeahead_voting](https://user-images.githubusercontent.com/12114550/37570900-25715752-2af6-11e8-9eaa-e22fe6a76186.gif)

## Authority (not using typeahead)
![bitshares-typeahead_auth](https://user-images.githubusercontent.com/12114550/37570908-34edc5a8-2af6-11e8-9ed6-398a6838f092.gif)

**Comment by startailcoon** [comment]
I will update my hours tomorrow after I've checked all the code again and signed it of fully

**Comment by gibbsfromncis** [comment]
@startailcoon I suppose you should wait for merge of #1325 and then add User Contacts to typeahead.

**Comment by startailcoon** [comment]
Indeed, still waiting for your contacts changes. Nice work on that.

**Comment by startailcoon** [comment]
Updated to support new `Contacts` instead of old `Linked Accounts`.
