### ISSUE TITLE
[2.5] Responsive design glitch in market view

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#1317]
![image](https://user-images.githubusercontent.com/15861527/37337275-aa05a2d8-26ab-11e8-944c-ce285ae70d41.png)

A large buy order for Hertz gets squished into an unreadable state when the screen is resized.

**Comment by svk31** [comment]
After the font size increase this happens for a lot of markets. It can't possibly be perfect at all screen widths though

**Comment by ahdigital** [comment]
I don't think we can do anything with truncating the figures, so if we were to do anything I'd suggest something like this:

![buy-sell-scroll](https://user-images.githubusercontent.com/3088454/37477670-2d6be48c-2870-11e8-856f-8c21ca9e4924.gif)
![buy-sell-scroll-2](https://user-images.githubusercontent.com/3088454/37477671-2d86e822-2870-11e8-9816-404e88d9ccc8.gif)

**Comment by calvinfroedge** [comment]
I actually think it's better to set a minimum width on the whole table (including the headers) rather than just on the table contents as the chart is harder to read if the label and contents aren't matched up. Otherwise, this PR implements as suggested:

https://github.com/bitshares/bitshares-ui/pull/1362

![update](https://user-images.githubusercontent.com/632938/37879065-04998f44-3038-11e8-9b3a-9854d5eb8b08.gif)

**Comment by wmbutler** [comment]
@ahdigital should I credit you for any UX time on this?

**Comment by ahdigital** [comment]
Nah, I didn't do anything.

**Comment by calvinfroedge** [comment]
I have updated my PR as per SVK feedback in the last sprint. You can view screencast and updated comments here:

https://github.com/bitshares/bitshares-ui/pull/1362/

This issue has grown a bit in implementation time due to feedback and I imagine it may grow a bit more to deal with edge cases.

**Comment by startailcoon** [comment]
Included in PR #1786
