### ISSUE TITLE
Find Market only shows OPEN assets

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1320]
Can anyone confirm this? If I look for markets I only get open assets listed?

![image](https://user-images.githubusercontent.com/33128181/37407652-78250098-279a-11e8-8b53-c131498ed69b.png)

**Comment by grctest** [comment]
Can confirm this is occurring for me using the bitshares.org web wallet, if you start typing in the 'asset name' field it will proceed with the search, however I agree that openledger's UIA shouldn't be the absolute default for the reference wallet.

**Comment by wmbutler** [comment]
Can we get this regex for the search to look for asset names:

- [x] from the start of the asset
- [ ] from the beginning of the `.` on an asset

**Comment by svk31** [comment]
It defaults to open.x assets because when this search was added they were the only ones we had. It also populates default assets because people didn't understand they had to type something to search.

The asset search api only allows searching from the start of the asset so we can't really change that.

**Comment by calvinfroedge** [comment]
Working on this issue...have identified problem but will take some time to resolve.

**Comment by calvinfroedge** [comment]
Open PR which resolves issue...

https://github.com/bitshares/bitshares-ui/pull/1365

![update](https://user-images.githubusercontent.com/632938/38040730-bde25b2c-3275-11e8-897c-dcb9c0995183.gif)

Would love second pair of eyes to ensure another issue was not introduced.

**Comment by svk31** [comment]
I would prefer that we just remove the default assets here, making the user search for something manually. They were there for convenience back when we only had OPEN.X gateway assets, now we have many so the search shouldn't be biased.

Maybe add a gateway selector instead that will trigger a search for the assets of the selected gateway provider.

**Comment by wmbutler** [comment]
@svk31 the gateway selector is needed but I think it's a larger UX concern since we will wan to allow users to group and search by gateway throughout. I've broached this with @ahdigital

**Comment by calvinfroedge** [comment]
@svk31 Is there a problem with the PR?

**Comment by calvinfroedge** [comment]
I think I resolved the issue in my PR as it was reported...user wanted to be able to see all assets when visiting "Find Markets". I made sure OPEN, RUDEX, and UIAs are all visible in find markets up front. That resolves the issue as reported. I also diagnosed and resolved performance issues with loading the additional market data (which was even an issue before when only showing OPEN assets). The majority of my time I spent on the performance issue (~5 hours). The original estimate was 2 hours and I increased as we have been doing when an issue takes more time than in the estimate.

When I took the issue on, my expectation was that the issue had already been curated and that the desired solution was to make all of the assets appear by default, as well as  making search behave as expected (as in only assets which match search criteria should appear). My PR is here:

https://github.com/bitshares/bitshares-ui/pull/1365

It seems as if @svk31 is changing the scope of the issue entirely rather than critiquing my solution to the reported issue:

```
I would prefer that we just remove the default assets here, making the user search for something manually. They were there for convenience back when we only had OPEN.X gateway assets, now we have many so the search shouldn't be biased.

Maybe add a gateway selector instead that will trigger a search for the assets of the selected gateway provider.
```

My hope is that any issue that makes it into a sprint does not get materially changed in scope after it has been placed in the sprint, as whoever does the work essentially loses their time investment.

If it's about actual work going beyond the estimate, I'm happy to first explore an issue and submit a revised estimate. My contention is simply that the desired end result from a user perspective should already be settled before the issue makes it into a sprint.

**Comment by wmbutler** [comment]
@svk31 please review and let me know how to proceed. If there is a particular issue you have with Calvin's work, please voice it. It sounds as if Calvin dug a bit deeper and fixed some root issues.

**Comment by svk31** [comment]
I don't have any issues with the work, technically it looks fine. I'm just pointing out that the original issue was just a misunderstanding: he was changing the quote currency instead of searching for an asset, and expecting the list of searched assets to change.

Adding more assets to the default search doesn't fix that, and as calvin himself pointed out doing so caused performance issues.

**Comment by calvinfroedge** [comment]
I was able to work around the performance issues introduced by ignoring renders, though I'll agree it is not the most ideal solution. I do think it's a reasonable user expectation that anything under "Find Markets"  is a market for the given quote currency. This was not the case before and is now.

So what is the plan here...simply not to show any assets by default? I am happy to make the change, just hoping to receive at least a partial payment for the work done to resolve the original issue. The original issue may have been a misunderstanding but it did make it into the sprint.

**Comment by wmbutler** [comment]
@calvinfroedge It is definitely a problem if we try to list all assets before a user has typed anything in because of the network load.

**Comment by calvinfroedge** [comment]
@wmbutler @svk31 We can show nothing until the user starts typing. That's an easy change to make.

**Comment by wmbutler** [comment]
Placing this in 180415. Is there any reason this didn't get merged into 180401?

**Comment by sschiessl-bcp** [comment]
I think the reason was simply that we did not come to a conclusion yet. 

If it matters, I would also prefer lazy loading if the user actually selects a base asset, with optional gateway selection (could also be done via settings). Exchange view is already slow enough.

@calvinfroedge I don't think anyone wants to deny you the payment, but please do keep in mind that working 5h more on it does not justify per se adding 5 quality hours to it, such an adjustment always needs to be confirmed by @wmbutler (my statement is not meant as a judgement of your work, simply as explanation)

**Comment by calvinfroedge** [comment]
I agree that no conclusion has been reached. Need @wmbutler and @svk31 to confirm final approach.

@smokenetwork I have been working on the UI since last summer and we have always added time to estimates to adjust for overage. This has not been a problem up to now so that's simply what I'm accustomed to. My point was just that if there was no consensus on what the end result should be this issue should not have been placed in a sprint. Concerns like extra server load should have been taken into account prior to putting the issue into the sprint.

I think I resolved the issue (showing all assets) in the allotted time, but the performance issues made it unusable. The extra time was spent just diagnosing the performance issue. The actual fix was only a few lines of code. If you check out the branch, you'll see the UI loads the assets pretty quickly now without hanging. The only difference is no market stats show for a few seconds.

**Comment by calvinfroedge** [comment]
Ok, so...

1) No assets shown initially

2) Helper text

3) Show all assets on search

**Comment by wmbutler** [comment]
> 3. Show all assets on search

Show top 20 assets matching search regex on search. I think this will work to keep the list from being sluggish. Debounce of maybe 200ms?

**Comment by svk31** [comment]
Like I mentioned in another comment the asset search API is very limited, unless we have all assets cached locally which is unlikely. It's a very literal search, no regex capability, so searching `TC` will not give you `BTC`, nor will searching `BTC` give you `OPEN.BTC` or `RUDEX.BTC`. That's another reason why I originally decided to load the OPEN.X assets by default, since searching BTC in that case would actually give you OPEN.BTC.

There are thousands of assets now so loading them all (100 at a time) each time we load the GUI is not an option imo, nor is storing that many asset names locally a good idea. Perhaps the core team can provide a better asset search API call with regex capabilities? @abitmore @pmconrad

**Comment by startailcoon** [comment]
When I did some work on the Asset page on the Explorer section I came across the very same issue.

I then opened an issue on the core section addressing it.

https://github.com/bitshares/bitshares-core/issues/688

**Comment by sschiessl-bcp** [comment]
Since ES does not need to be enabled in the connected node,  should there be a two fold way of searching?
One using asset api with adore dumb search (like current one), one that replaces said logic with ES if present with proper indication.?

Or, should there be an option to configure separate ES connection?

**Comment by wmbutler** [comment]
I think a fallback position is the smartest way to do it. Check for ES, if non responsive, use traditional method.

**Comment by sschiessl-bcp** [comment]
There is an ES endpoint already provided for the GUI that you can use, I ll send you the URL later.

**Comment by sschiessl-bcp** [comment]
@calvinfroedge 

How is the status on this? Could you connect to the ES?

**Comment by calvinfroedge** [comment]
@sschiessl-bcp Unclaiming this, you are free to close it out

**Comment by svk31** [comment]
Fixed by @startailcoon in #1677, not sure what to do about the rewards here. @wmbutler ?

**Comment by wmbutler** [comment]
@startailcoon did you get paid fairly in #1677? If so, please remove the bounty and close this.

**Comment by startailcoon** [comment]
@wmbutler I would say yes. Removing bounty on this issue.
