### ISSUE TITLE
[2] Can't vote

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1341]
In testnet, I own the account `abit-test`. I can vote with it in this page: https://testnet.bitshares.eu/account/abit-test/voting.

xeroc added my account to his active permissions, see https://testnet.bitshares.eu/account/xeroc/permissions
So I should be able to do anything for xeroc which requires active permissions. For example, I can do transfers.

However, I can't vote on behalf of xeroc, all buttons are disabled on this page https://testnet.bitshares.eu/account/xeroc/voting.

**Comment by svk31** [comment]
I think the above commit should fix this, please confirm when you get a chance.

**Comment by abitmore** [comment]
I think this issue is not about fetching objects, but related to "IsMyAccount()" (or similar check).

**Comment by svk31** [comment]
No I really think it was due to the bug I fixed in that commit, it caused a setState call to fail which in turn made it impossible to vote. I can attempt to change Xeroc's votes just fine myself now, but when I try do publish it fails because I don't have the private key.

![screenshot from 2018-03-29 16-39-00](https://user-images.githubusercontent.com/6890015/38098382-d6198864-336f-11e8-85bc-d6acab84bd39.png)
