### ISSUE TITLE
[3][dot5enko] Display URI instead of address in QR Code for Deposit Beta

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1363]
We currently display the address for the asset we want to deposit embedded in a QR code. This is a good first step, however, ultimately we want to be able to include more detailed information. One looming problem is that URI's are unfortunately assembled using the full name of the asset `bitcoin:` instead of the abbreviation `btc:`. Unless I'm missing something, this poses a particular problem for us because I do not think we have a definitive list of the full name of each asset. This means generating the URI will require some creative thinking in order to scale.

I wish the world would adopt the abbreviation as the URI scheme. Anyhow, need some creative thinkers on this one so we can present a URI in the QR code for the deposit modal as:

`bitcoin:1eworuieoueoieureorueoreoi`

**Comment by calvinfroedge** [comment]
Well I think there are full asset names available in the coin props, the problem is knowing what URI scheme should actually be produced, as there are asset names with dashes, upper and lower case, etc. Do we know what the full URI should be for every asset?

**Comment by wmbutler** [comment]
Nope, open.btc:

![screen shot 2018-03-28 at 12 38 44 am](https://user-images.githubusercontent.com/1254810/38010852-6cff3fa4-3220-11e8-9794-44be0134d5bd.png)

**Comment by dot5enko** [comment]
think its quite impossible without hardcoding a global list of such full names for each asset

**Comment by wmbutler** [comment]
It's kinda crazy that the URI scheme doesn't just use the abbreviation for the coin.

**Comment by abitmore** [comment]
Please be aware that QR codes showing in deposit page are meant to be consumed by 3rd-party software, but not our own. That said, we need to be compatible with wallet software of other coins e.g. BTC/ETH when showing QR codes, otherwise the QR codes are useless. That means full URI's don't always work, at least, it's not our job to define/invent URI schema for other coins. What we need to do, is to check their docs, check their existing wallet software, and show QR code according to their rules.

**Comment by clockworkgr** [comment]
I think this issue possibly ties into this: https://github.com/bitshares/bitshares-ui/issues/775

Offering a QR code that works with ALL possible mobile clients will only be possible if we set up a unified deep-linking scheme for the wallet that BOTH the web wallet and a possible future mobile SDK support. So that mobile app providers can include the SDK libs into their apps and handle those deeplinks accordingly.

**Comment by wmbutler** [comment]
We could ask gateway providers to include `fullAssetName` on the `coin` api. This would allow us to build the URI in a responsible manner. We are currently displaying:

![screen shot 2018-04-03 at 6 41 27 pm](https://user-images.githubusercontent.com/1254810/38281124-af42dda0-376e-11e8-863f-bdf29d420d2a.png)

In this case, the full URI only allows us to include the amount. Scratching my head trying to figure out if it's worth the trouble or not.

**Comment by wmbutler** [comment]
Maybe we should limit the scope on this to a subset of common assets so we can have forward progress without causing undue harm. We can support the following for the time being and ease into a more comprehensive list in the future.

- BTC `bitcoin:<address>[?amount=<amount>][?label=<label>][?message=<message>]`
- LTC https://electrum-ltc.org/litecoin_URIs.html
- ETH `ethereum:<address>[?from=<sender_address>][?value=<ethamount>][?gas=<suggestedGas>]`
- BCH `bitcoincash:<address>[?amount=<amount>][?label=<label>][?message=<message>]`

**Comment by dot5enko** [comment]
sounds good. can i take this?

**Comment by wmbutler** [comment]
Yes, take great care with this and test test test.

**Comment by startailcoon** [comment]
@dot5enko does this issue have any updates? Should I remove your assignment?

**Comment by dot5enko** [comment]
@startailcoon don't remove, i'll fix it in few days

**Comment by dot5enko** [comment]
done
