### ISSUE TITLE
[8] Deposit/Withdraw Modal - Add BRIDGE.* Support

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1411]
## Withdraw

Since their coins api is conforming, I can't see why this would be any more difficult to implement than the existing RUDEX and OPENLEDGER items. Some initial discovery: it appears that the memo for cryptobridge uses the entire asset name rather than the generic asset name:

Unsure as to whether we should use

- cointype
- symbol
- walletSymbol

TO: cryptobridge
MEMO: `bridge.ltc:<address>`

![screen shot 2018-04-07 at 1 40 50 pm](https://user-images.githubusercontent.com/1254810/38458951-53a1b4aa-3a69-11e8-9b26-f8939649e3a6.png)

## Deposit

**Comment by startailcoon** [comment]
I can handle this

**Comment by startailcoon** [comment]
For the record, this Issue will depend on the successful merge of PR #1383 as it's going to be using the new way of adding gateways.

It will be worked on side-by-side with Issue #1384

**Comment by startailcoon** [comment]
BRIDGE does present partial issue to implement because they aren't setup as the others. 

OpenLedger and Winex has one wallet for their own coin, like OPEN.BTC, and one for the backed coin. Bridge does not have it that way. It will require some logic requirements for their specific case at the moment.

**Comment by startailcoon** [comment]
![bitshares-bridge](https://user-images.githubusercontent.com/12114550/38770293-0b87a49c-4011-11e8-864f-0518ff3404a3.gif)
