### ISSUE TITLE
[UX:3][ahdigital] Improved Witness Information Page

### ISSUE THREAD

**Issue by oflyhigh** [bitshares/bitshares-ui#1436]
In Bitshares UI (2.0.180402), When I go to "Explore->Witnesses" and click any witness (such as "in.abit") in the witness list, I was brought to the portfolio page of the witness.

I think It should be a better way to show witness details information instead of portfolio.

**Comment by grctest** [comment]
What witness information though? The only missing info is their witness URL & some don't provide one.

**Comment by wmbutler** [comment]
We don't really have a "witness details" page.

**Comment by abitmore** [comment]
@grctest witness info includes:
* signing key (we can even add a feature for witnesses to changing signing key from UI, although not useful as Steem where some witnesses use UI to disable block producing)
* URL
* last confirmed block number
* votes
* number of blocks missed
* price feeds  (no direct API to fetch so far)

In regards to the links, please be aware that they aren't validated and won't be enforced by core, so some of them may be empty or broken, or even linking to malicious website e.g. due to expired domain name or hacked.

**Comment by wmbutler** [comment]
@ahdigital need UX work here. This will require special thought because we don't really have a witness information page yet. Possible make it part of the explorer.

**Comment by kapeer42** [comment]
Can I claim this?
I could implement the page roughly and with feedback reach a good UX maybe.

**Comment by wmbutler** [comment]
I'd rather have @ahdigital work the UX first.

**Comment by apasia-tech** [comment]
Since there is 3+5 hours in the issue, i would consider proper management by @wmbutler as following:

@kapeer42 - 3 hours claim and implement the page roughly with all the needed witness data.
@ahdigital - 5 hours claim and get UX ready/pack after @kapeer42 

It would speed up the process of the issue being solved/developed and give Dominic more time to focus on other more important tasks. What are others thinking on this ? 

Cheers,

Luci.

**Comment by wmbutler** [comment]
It makes very little sense for @kapeer to do work prior to UX.

**Comment by apasia-tech** [comment]
UX - User Experience
UI - User Interface

Thx Bill, even though there is not UX work on this issue, It's just an info witness page. And on the other hand, I see that team has no much changes on the github for past 20 days, so this was a very PROFESSIONAL MANAGEMENT SUGGESTION how to speed up the process and help the blockchain. We wouldn't be happy for me to go there and research more, especially with amount paid out since 01.03 until 15.04 for UI team and Worker Proposal. Anyway, as I have asked, others thinking on this, please ?

Many thanks.

Luci.

**Comment by ahdigital** [comment]
@wmbutler Further to the initial comment from @grctest there's only 'signing key' and 'URL' that are missing according to the @abitmore's data list.

I think we should integrate the missing data into the existing table/cards.

**Comment by wmbutler** [comment]
Fine with me. Please post a mockup so we can hand it to @kapeer42

**Comment by ahdigital** [comment]
I added the 'signing key' and 'URL' into the table but then felt I could make some additional tweaks here (within context of existing design).  In order to create more room in the table for additional columns I:

1. Combined 'last block' and 'last confirmed' columns
2. Renamed 'rank' to '#'
3. Moved the table of statistics to the top of the page

As the signing key is a long string it would be better to open this in a modal by clicking on the key icon. The URL could have been an icon also, but because of the point raised about malicious links I thought it's safer to display it.

![image](https://user-images.githubusercontent.com/3088454/39621628-59a7cb5e-4f87-11e8-9e66-d920209abc1c.png)

**Comment by abitmore** [comment]
Mostly looks good, except the URL can be very long, so sometimes need to hide some of it.

**Comment by wmbutler** [comment]
What if, for the URL, you post an icon that indicates a link and embed the URL in that icon?

**Comment by ahdigital** [comment]
Coming back to the point about the URL's potentially being malicious I think it makes sense to show them, or at least partially in the scenario where they are very long and an ellipsis has been applied.

**Comment by wmbutler** [comment]
@ahdigital are you implying that a user could identify a malcious URL visually?

**Comment by wmbutler** [comment]
I don't know about that. I really don't think it's possible to visually recognize based on the URL whether a site is malicious or not.

**Comment by startailcoon** [comment]
@ahdigital has completed the UX of this task, as I can see.

I also believe that there isn't really a need to display the URL on the page, as it can be to long to view. A hover state would suffice, it's our witnesses here we are talking about. If one is unsure about an URL, it shouldn't be opened directly anyway.

@kapeer42, are you still interested in taking this task?
