### ISSUE TITLE
[1][svk] Unable to add new public keys in permissions

### ISSUE THREAD

**Issue by HarukaMa** [bitshares/bitshares-ui#1451]
When you try to add a new public key to active or owner permissions, the UI will always show "Unknown account", thus unable to add keys. Memo key changing is good. "Key is already in the list" error message is also not displayed.

Tested on wallet.bitshares.org, head of staging branch and a arbitrary version dated Apr 9. Seems that this issue has been there for a while.

This is a rather important bug IMO and needs to be fixed ASAP.

**Comment by christophersanborn** [comment]
It seems this issue persists or has reappeared.  I am unable to add account permissions by public keys in either standalone UI version 191120 or in the current version hosted at develop.bitshares.org.

Possible to re-open this issue?

One thing I notice is the text entry box only allows lowercase letters (as in account names), which makes it impossible to enter a valid public key.  So perhaps this is a different root cause from what initially prompted this issue?

@svk31 @sschiessl-bcp (Tagging some people just because I'm not sure if this comment will get noticed on a closed issue.)

**Comment by abitmore** [comment]
I think it's better to create a new issue.
