### ISSUE TITLE
[.5] Unable to remove manually added nodes

### ISSUE THREAD

**Issue by HarukaMa** [bitshares/bitshares-ui#1453]
Nothing happens when clicking on the black `x` mark in Settings - Nodes - Personal.

**Comment by wmbutler** [comment]
True... And I don't think the one listed for me is even a personal node.

![screen shot 2018-04-22 at 12 53 37 pm](https://user-images.githubusercontent.com/1254810/39098161-40e2a01c-462c-11e8-8ba2-7c4b1f839edf.png)

**Comment by abitmore** [comment]
@wmbutler the one was on the list, but the url has changed in latest release.

**Comment by startailcoon** [comment]
I'll handle this one

**Comment by startailcoon** [comment]
Due to an issue in how the removal modal was triggered, the modal never showed after the change of Icons in the list. This is now fixed in the PR, as well as a few translation fixes.

The unknown node you have in your list is due to the change of URL, which you figured out.

If a node is not a known node, and the user has it in its list, it's regarded as a personal node.
