### ISSUE TITLE
[20] Exchange Redesign 

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1477]
Please follow the UX shown on #1449 

_(This issue includes redesign of entire Exchange except Trading View redesign & Market Depth chart. For Trading View & Market Depth we have [separate issue](https://github.com/bitshares/bitshares-ui/issues/1484), (c) gibbsfromncis)_

_Ready for testing and final comments -> https://github.com/bitshares/bitshares-ui/issues/1477#issuecomment-414146761 //startail_

**Comment by abitmore** [comment]
@wmbutler where is the order-stacking feature?

**Comment by wmbutler** [comment]
@abitmore I don't think it is required in order to get the UI rewrite started.

**Comment by abitmore** [comment]
There is already a PR for that feature: https://github.com/bitshares/bitshares-ui/pull/1467, to avoid duplicate or wasted efforts, we need to think about when to merge it and arrange work appropriately. After the UI rewrite is done, that feature will certainly need to adapt.

BTW the developer is looking for something really challenges to work on. Wish we can find some in this project for him.

**Comment by wmbutler** [comment]
@abitmore If you have anything that interests you, I'd be happy to add it. We do have a challenging issue surrounding changing a user's keys, particularly the memo key since past memos rely on it having the old key.

Is your contact a backend or frontend resource?

**Comment by ahdigital** [comment]
@startailcoon 

1. It is just an example of how we could access other options added in the future so you can remove for now.
2. Appending sounds fine to me. It should be possible to drop in after the fee field.
3. I forgot to factor this in, but this could be a use case for #1 if @wmbutler agrees (screenshot below*).
4. The settings menu is intended to allow the user to control the exchange only. Initially, the only option we'll have is switching layout.

**\* Buy xxx / Borrow xxx**
Change 'advanced options' to 'additional options', which opens a menu from which the borrow/buy modals can be triggered:

![image](https://user-images.githubusercontent.com/3088454/39567370-ba870970-4eb6-11e8-872d-a41f9663ba8d.png)

**Comment by wmbutler** [comment]
This brings up the point that we are also missing

- Lowest Ask
- Expiration
- Market Fee

Maybe you can spend some more time with the trade widget. Keep in mind that you have already cut it in half by tabbing the control. Let's get everything in. Happy to extend UX time. @startailcoon can you work on other parts while we fine tune the trading buy/sell widget?

**Comment by wmbutler** [comment]
@startailcoon Looks like @gibbsfromncis was planning to work on this issue.

**Comment by gibbsfromncis** [comment]
@wmbutler I've updated the estimate and name of the issue. Also I've created new one about TradingView & Market Depth Redesign - https://github.com/bitshares/bitshares-ui/issues/1484)

**Comment by startailcoon** [comment]
> @startailcoon can you work on other parts while we fine tune the trading buy/sell widget?

No problem, I will start working on the other parts and await updates for the buy/sell widget.

**Comment by startailcoon** [comment]
@smogm please define what whitespace your referring to.

**Comment by smogm** [comment]
@startailcoon Here as an example, the red marked spaces. Guess in CSS it is called "padding" or "margin".

![image](https://user-images.githubusercontent.com/2078175/39751898-0b0fa2f6-52ba-11e8-8327-6d15c54ce246.png)

**Comment by wmbutler** [comment]
@startailcoon as long as your padding and margin values are flexible, just focus on the content for now. I think @ahdigital said he was going to be pretty busy this week so don't worry about the minor css details until he can address those directly. You can see I brought up a few as well.

**Comment by tbone-bts** [comment]
Not sure if this is currently the best place to offer general input re: the exchange redesign.  If not, please let me know where I should re-post this.

In any event, I mainly wanted to make sure a couple of subtle but important features don't get lost in the redesign:  

1. Primarily I'm talking about how each order book row has a running sum that includes all prior rows.  
2. Also, when the user clicks on any row of the order book, it's important for the running sum (of both quantity and price) to get populated into the buy/sell order form.  

I cannot express how inconvenient it is to use exchanges lacking these simple features.  I would argue that thoughtful features like this helped Poloniex dominate Bittrex (until Poloniex lost a lot of trust and many people left to Bittrex despite their inferior UI).

Unfortunately features like this are lost on some of the successful exchanges like Binance since they can get away with having great liquidity and a UI that at least **looks** good.  I'm not saying Binance UI is terrible...but they simply don't need to be as clever as we do in order to attract and keep users.

**Comment by startailcoon** [comment]
I can only agree with you and say that these functions are not to dissappear during this transition.

**Comment by startailcoon** [comment]
Another question is how we should handle smaller screens. Today it does this by wrapping lines for the boxes, but the current mockup does not view any handling of this.

**Comment by startailcoon** [comment]
# Current Issues and Questions for the new design
ping @wmbutler @gibbsfromncis 

Based on the design at https://www.behance.net/gallery/64871121/BitShares-Exchange

For easier understanding, I'm referring the layouts below as follows
Layout 1 = Vertical Order Book A
Layout 2 = Vertical Order Book B (identical, just mirrored panel)
Layout 3 = Horizontal Order Book A
Layout 4 = Horizontal Order Book B

## Applies to all layouts
- When side panel is hidden, should we put more than two content boxes in width, if the application is wide enough to do so? Having only two makes them very wide. We do this today.
- If screen is to narrow to allow the side panel, the content of it needs to be visible somewhere else. Where should this be, and in what order?

## Layout 1+2+3
- Layout 1+2+3 has a content box with many headers, what do we do when they can't fit sideways? See example below

- We still lack design for Buy/Sell content boxes for items like:
  - Market Fee
  - Expiration Time

- Settings Box
  - I have no preview images to use for this box. The design shows a layout preview to pick. Right now I've used the popup for the chart settings to pick a layout from a dropdown. 

# Preview

*Note that these are previews and in current rewrite. Most items are in limbo and not what they are supposed to look like in the end result*

## Layout 1+2 w/ side panel
![bild](https://user-images.githubusercontent.com/12114550/41286522-18c3b26a-6e40-11e8-95ae-5121c057f2d9.png)

## Layout 1+2 w/o side panel
![bild](https://user-images.githubusercontent.com/12114550/41286533-265675a2-6e40-11e8-97b8-98f3157f25f5.png)

## Layout 1+2 in narrow screen
Note in this licecap that when the screen is to narrow to contain all the headers of the "Market Trades...." box the side panel will dissapear and put the order book below. The "My Markets" box is not visible, but can be accessed through the market picker function.

![bitshares-newdesign](https://user-images.githubusercontent.com/12114550/41286834-247c91f2-6e41-11e8-9813-fc57114fa708.gif)

## Layout Picker
![bitshares-newdesign_picker](https://user-images.githubusercontent.com/12114550/41287595-8374cee8-6e43-11e8-9772-de83f398d3ab.gif)

**Comment by svk31** [comment]
Would be great if you could make a branch for this and push your changes there, that way we can try it out ourselves instead of looking at gifs.

**Comment by startailcoon** [comment]
Idd, I'll do that today.

**Comment by ahdigital** [comment]
> When side panel is hidden, should we put more than two content boxes in width, if the application is wide enough to do so?

I think that it makes sense to do this, and utilise the space available. As you say, the app does this now so it wouldn't be unexpected.

> If screen is to narrow to allow the side panel, the content of it needs to be visible somewhere else. Where should this be, and in what order?

I suppose it should appear at the end of the other stacked content boxes. Though depending on the implementation of this in the mark up, it seems to me that if the screen width is too narrow to display the side bar the user is likely using a smartphone - and for that scenario I've made a suggestion at the end of this post.

> Layout 1+2+3 has a content box with many headers, what do we do when they can't fit sideways?

Once fully integrated, ANT framework solves this problem by appending left and right arrow buttons to the tabs allowing the user to cycle through the options. E.g.

![image](https://user-images.githubusercontent.com/3088454/41464427-30891ae4-7092-11e8-806e-231ca8f76d7a.png)

> We still lack design for Buy/Sell content boxes (Market fee, expiration)

Can these not be added as inputs beneath what is shown, or added into the advanced settings link? Perhaps the advanced settings link could open a modal with tabs grouping logical settings.

> I have no preview images to use for this box. The design shows a layout preview to pick.

If I understand, all you want here is an image for each of the layout previews:

![layout-1](https://user-images.githubusercontent.com/3088454/41464853-a7a98b12-7093-11e8-9787-92cc1b171afd.png)
![layout-2](https://user-images.githubusercontent.com/3088454/41464854-a7c4eb78-7093-11e8-899d-e434b087f35b.png)
![layout-3](https://user-images.githubusercontent.com/3088454/41464855-a7e9fab2-7093-11e8-81f6-bb761b54f73b.png)
![layout-4](https://user-images.githubusercontent.com/3088454/41464856-a80ccd6c-7093-11e8-95a7-d5449d8d268a.png)


#### <768px layout proposal

Since the 4 layouts can realistically only be maintained for medium - large displays before element stacking happens by necessity why don't we have a single blanket layout for <768px widths? This layout could be a specific smartphone layout that all 4 layouts switch to when the screen is particularly small. Instead of just stacking and having the user scroll through a long page of content boxes we could be a bit smarter in the presentation and make the user experience more optimized. E.g.

![exchange mobile layout v1](https://user-images.githubusercontent.com/3088454/41467860-e86fbbd8-709f-11e8-97f8-946564915fca.png)

**Comment by startailcoon** [comment]
## Preview

Just wanted to show that the new AntD component works like a charm in the UI thanks to the work on bitshares-ui-style-guide.

![image](https://user-images.githubusercontent.com/12114550/41683884-411b0932-74dc-11e8-9d21-f224a057ded5.png)

**Comment by wmbutler** [comment]
Do hours need to be adjusted here?

**Comment by startailcoon** [comment]
@wmbutler I've been taking a little "creative" freedom on this and will post an update with a push of the code that can be explored by the devs and experienced users.

May need to be pushed to next milestone due to some issues with CSS and AntD components.

**Comment by startailcoon** [comment]
## Quick Preview
Here's a quick preview of the current state of the design. I've marked the visible changes.

### NOTE: This is not a final product

![bild](https://user-images.githubusercontent.com/12114550/42129343-9f23925e-7cc2-11e8-870f-39f62fdf0e98.png)

**Comment by sschiessl-bcp** [comment]
Nice!

So this is basically 5 areas that are predefined in size and location. How do you feel about putting that in a user configurable space (I think that would be awesome), like https://www.npmjs.com/package/react-grid-layout?

**Comment by startailcoon** [comment]
@sschiessl-bcp that package looks like an awesome thing, but may be a little out of scope right now. We should have it in mind in the future though, really.

**Comment by sschiessl-bcp** [comment]
Implementing those 4 different ways to arrange the components like shown in the mockup manually is effort in veign I think. 

I would suggest to only implement one arrangement then and implement this or another framework consecutively, which will give the other arrangement basically for free.

I disagree about having it in mind for the future..it seems it also facilitates responsiveness

**Comment by startailcoon** [comment]
I need some guidance here as I've already invested several hours in this.

Implementing the suggested framework would be possible, but hours would surely increase.

I agree that it would be beneficial to use this, but it would make the UX inaccurate.

Do we want this? Increased hours and time frame would be required if so. 

@ahdigital @wmbutler

**Comment by wmbutler** [comment]
@sschiessl-bcp is probably right. We will likely get requests for combinations that we cannot predict.

**Comment by startailcoon** [comment]
I've pushed another update to the fork for the new exchange layout, for those that wish to take a view at it and leave some feedback. Rember that I'm working out of the UX of https://www.behance.net/gallery/64871121/BitShares-Exchange, while adding a few changes to make it work with mobile.

 There are a few visual issues, but I've got Layout 1,2 and 3 functional pretty much 99%.

Layout 4 is still in process.

**Comment by startailcoon** [comment]
A new commit has been pushed to the forked version of the UI
https://github.com/bitshares/bitshares-ui/tree/1477-ExchangeRedesign

**Note that there are still changes to be made**

Right now I'd love to hear from you what you think about it

### What's done
We have four layouts, each with its own difference. You can now hide the panel, making the use of the space better. If you wish to hide the panel and still view the "Buy/Sell" section, you use the 4th layout. 

If the screen is less than 850px, the panel is automatically hidden. The Buy/Sell section will then move to the main screen instead, to make sure you can trade. "My Markets" and "Find Market" will not be visible, as they are long narrow lists.

Depending on the screen width, the different sections are moved around a bit. This was **not** included in the initial design, but rather included in the conversation of the issue.

### What's left
- [ ] Use `<Collapse />` ANT component for small screens.
- [ ] Change "Settings" to a Popin, rather than a modal (as the market picker)
- [ ] Go trough all the changes compared to `developer` branch

**Comment by svk31** [comment]
Some comments:

Minus
- I had to remove the 100% height on the vertical orderbook since that made it take up 1000s of pixels vertically
- I still dislike having a vertical orderbook since it makes it impossible to survey bids and asks independently, and you lose the sum information
- The asset name/price boxes (BTS / bitUSD) (bitUSD) in Buy/sell no longer align properly which makes them look weird
- None of the layouts are improvements on the current l layout for me personally, I'd prefer to have layout 2 with a horizontal orderbook, which is basically the same as the current layout with the new buy/sell and trades + open orders boxes.
- The scroll bars are offset slightly outside of their boxes, in market trades for example.
- It says advanced options but no action associated

Plus
+ I love the vertical bar collapse/expand toggle (will probably steal that for the current layout while we wait for this)
+ Antd Tabs look great
+ It seems to work on mobile, I'd love to see the My Markets tab included on mobile too though.

**Comment by startailcoon** [comment]
Thanks for your feedback svk31

There are some things that may be required to change, like your height issue. I'll see to that.

I'm working out of the exchange redesign UX, which has 2 vertical and 2 horizontal layouts. We can add more if required. But for now this is what I have to work from. Some may find vertical books easier, but I get your point.

I'll have another look at the scrollbar alignments. Advanced options isn't doing anything today. I'm hesitant to put the borrow/buy options there as I think they are to hidden.

The sidebar toggle is a nice thing, I see you've added it. Glad you like the AntD tabs as well. They take a little to get used to, but offer great feature for small spaces.

I've put much work to make sure this works for mobile, which is why it's taking some time.

I hope we can agree that this is a good push forward.

**Comment by startailcoon** [comment]
- [x] 100% height is apparently working different on browser/OS level. I see the issue on Chrome. *Fixed*
- Just don't use the vertical order book? :)
- [x] Asset Name/Price boxes was set to dynamic width. I'm changing back to fixed percentage as it does look better. *Fixed*
- It's more dynamic and mobile friendly. I think it's a step forward, but any changes can still be made to improve it.
- [x] Table headers wheren't 100%, making the scrollbars look outside. *Fixed*

Work will progress :)

**Comment by startailcoon** [comment]
I will build a fifth layout, as I understand what @svk31 is thinking here. Both horizontal order book layouts (3+4) has the Buy/Sell forms on the side. 

A fifth layout will be a merge of the 3rd layout, but with the buy/sell boxes.

**Comment by startailcoon** [comment]
Another update has been pushed to branch for review. Still work to be done.

This changes the MarketPicker and Settings to Modal types, as well as adding the "My Markets" to small screen view.

**Comment by startailcoon** [comment]
I'm getting very close to a final submission of this.

Collapse component is looking very good and a fifth layout will be applied that will look similar to what the user has today.

**Comment by startailcoon** [comment]
# Ready for Testing

The new layout is finally finished and ready for final approval. This redesign changes alot of the code and has various improvements on many sections, I will try to explain them below.

- The original +4 new layouts is now possible to pick from the exchange settings, where the original layout should be default.
- Mobile friendly Exchange!! This I'm very pleased with, and makes it much easier to mobile users. Layout choice doesn't matter here, as all use the same mobile layout.
- Added `tinyScreen` for even smaller screen checks as `smallScreen` isn't enough sometimes.
- The market picker and settings are now modals to acommedate the need to handle mobile devices as well as clicks outside the window. Settings will close on selection of layout or chart type. Market picker will close on selection. 
- Header is more dynamic for mobile. Decreased font by a few pixels. Fixed a few items not hiding properly causing overflow.
- Possibility to hide side panel (already in staging by svk)
- A VERY dynamic page that takes width, use of side panel etc in to account. This is very complex logic handling with CSS. Much testing has been put here.

And a whole lot of other minor issues on the way 💯 

This update doesn't handle anything else than design logic and should be safe for testing. What we are looking for is misses in logic that makes it render weird, not make the new Ant tabs selected etc.

**Comment by startailcoon** [comment]
# Mobile View

![image](https://user-images.githubusercontent.com/12114550/44312210-bba06980-a3f4-11e8-81a4-09b38b18075e.png)

![image](https://user-images.githubusercontent.com/12114550/44312213-d70b7480-a3f4-11e8-97b2-e514d9178a83.png)

![image](https://user-images.githubusercontent.com/12114550/44312203-a9263000-a3f4-11e8-92d4-6047256e7db4.png)

# Settings 

![image](https://user-images.githubusercontent.com/12114550/44312220-ff936e80-a3f4-11e8-886b-ca0243a5afa4.png)

# Layout 3
![image](https://user-images.githubusercontent.com/12114550/44312228-25b90e80-a3f5-11e8-8e6b-98857a078546.png)

**Comment by startailcoon** [comment]
Regarding clearing of the input forms

The forms will be cleared upon a successfull order submission.
There will be no clear button on the form directly, as it doesn't fit well with the layout.

![bild](https://user-images.githubusercontent.com/12114550/44946123-41a9b080-adf6-11e8-878a-e3e68a382105.png)

**Comment by dot5enko** [comment]
@sschiessl-bcp,@wmbutler this issue can't be closed, because from what i've seen on [staging](https://staging.bitshares.org/#/market/BTS_USD) it looks really freaky. I've seen really cool mockups made in https://github.com/bitshares/bitshares-ui/issues/1449, but current task not even close implementing them. I don't judge anyone, but we can't show this to the community: vertical order book is absent, everything is stretched up to the whole screen and most of the blocks are useless for trading
current staging: 
![image](https://user-images.githubusercontent.com/5626922/45268611-90ef8100-b487-11e8-8856-e4d6344e1ab6.png) 
mockup: ![image](https://user-images.githubusercontent.com/3088454/39463813-f49d2bae-4d11-11e8-829c-8e3d4af1dbe3.png)

i've seen that mobile ui was quite reworked, but did someone tried it even on top notch phone? - its buggy cause phone's cpu even most powerful can't handle such a bunch of components and requests this app do, and nothing helps with that - we need to rewrite whole frontend's backend :) to make some gain in usability and perfomance as well.

P.S. I use bitshares-ui to trade

**Comment by startailcoon** [comment]
Hi @dot5enko.

Appreciate any and all input, so no need to apologise.

First of all, you can choose different layouts by pressing the cogwheel on the right top menu. There you have 5 different layouts to choose from. 

You have the order book hidden, that's why you don't see it.

Please explain why you find 'all blocjs useless for trading'. They behave just like they used to do.

The mobile view is reworked, and I have not had any issues with jt on a mobile device. I find it easier and more responsive even.
However, I will look on the possibility to not load unused components on mobile, which would be a good idea to decrease any unnecessary usage.

I'm open for ideas, talks and discussions about anything that needs to be looked at.

**Comment by sschiessl-bcp** [comment]
> I've seen really cool mockups made in #1449, but current task not even close implementing them

Big difference is in the Buy BTS dialog, current staging looks like this
![image](https://user-images.githubusercontent.com/33128181/45280221-d5087300-b4d3-11e8-953d-2d23f9af96ec.png)
Was there a discussion to deviate from the mockup and stick to the current layout?

> its buggy cause phone's cpu even most powerful can't handle such a bunch of components
> However, I will look on the possibility to not load unused components on mobile, which would be a good idea to decrease any unnecessary usage.

I strongly agree with the sentiment. I tried it on my phone (Sony Z5 Compact). It is much better than before, but it is sluggish.

**Comment by dot5enko** [comment]
@sschiessl-bcp, @wmbutler, @startailcoon sorry, didn't seen that button and options (and that's sad - i need to research ui to get it up and shining)

Look at the binance, its a perfect ui for most of `usual` traders (not professionals). They have two (not five or ten) layouts: advanced and this, simple one: ![image](https://user-images.githubusercontent.com/5626922/45301072-c85a3e00-b518-11e8-8198-4e321576d314.png)
Three columns: order book on the left (with ~20-30 orders, we have thouthands of them, which eats a lot of memory i gues, and cpu, because this whole list is drawed in html), chart in the middle (own by default, not tradingview), and history and markets on the right. Buy/sell boxes not stretched and looks amazing on any device width because content width is fixed (and that's cool). 

 And now look at bitshares: 
![image](https://user-images.githubusercontent.com/5626922/45301303-56362900-b519-11e8-8db0-08fee22ac224.png)

Generally speaking i don't get some wow effect from big tradingview chart because we have lack of data to get some cool charts :) - and that's the problem, not cool animations or tabs. I don't even say its super slow comparing to old native chart library. 
 
Buy/sell input boxes look really ugly, doesn't they? 
- width is toooo big
- who cares that 0.1% of his order is 0.1*ORDER_SUM (i try to say this line is redundant) 
- expiry date 
- ...

Lets look at the heading of the page and compare mockup with actual result:
![image](https://user-images.githubusercontent.com/5626922/45301938-af528c80-b51a-11e8-9e82-3df7690d3876.png) looks really cool. 

![image](https://user-images.githubusercontent.com/5626922/45301999-d5782c80-b51a-11e8-95f3-873b3411a963.png)
not so cool, regardless its not same color scheme. I say it again: page not looks like on the mockup, although mobile is. I don't say we need pixel to pixel equality, but...

Look, i have made extension for myself which make main exchange page look more binance-like (read normal exchange)

![photo_2018-09-10_17-01-11](https://user-images.githubusercontent.com/5626922/45302226-64854480-b51b-11e8-80d1-7daa71d52592.jpg). Main content is fixed, most of useless features comboboxes, inputs, checkboxes removed, font-size is smaller and so on and it really ui-friendly for me as current release and much better than current staging. Things in current staging become event more complicated, ui is not standartized (something is new, something is in old style and so on): millions of buttons to make it look like an exchange. 

Are we really making decentralized exchange closer to simple people ?

**Comment by startailcoon** [comment]
First of all I'd like to say thanks for the feedback.

**My advice right now is that we delay the release of the new Exchange design for a later date, and address any open questions and issues before we merge it again.**

## So, let me try to summarize this.

I've worked out of the UX mockup as close as possible, which hasn't been easy since it hasn't been created with different window sizes in mind, just one static window size. 

### History Box width
The history box is extremeley wide because the window is extremeley wide. This is all in alignment with the mockup. 

### Buy/Sell Box
The Buy/Sell box is not exactly acording to the mockup, because there was a desire to save some space and not have the overblow headers on each form input. See comment here https://github.com/bitshares/bitshares-ui/pull/1786#issuecomment-414639600
Based on the mockup the Buy/Sell boxes uses tabs, which may be an unessesary thing. We could instead dynamically adjust based on screen size.

> who cares that 0.1% of his order is 0.1*ORDER_SUM (i try to say this line is redundant)

That's a whole other discussion. This has been on the table before on other issues and removing items isn't really where we are heading. It was forgotten on the mockup as explained here https://github.com/bitshares/bitshares-ui/issues/1477#issuecomment-386228706

### Header

> Lets look at the heading of the page and compare mockup with actual result:

I think you're being a little picky here. This is quite close to how the mockup is displaying the header and choice of tabs. It may be possible to fix a few pickles in fonts, but the design in code is not as easy as design in Photoshop.  I've been forced to slightly tighten the headers, as "Find Markets" was another missing item in the mockup.

### Mobile

I've had no issues on mobile device while testing the market, but I'm sure we can lazy load many of the components to lessen the load usage on less powerful devices. This shouldn't be an issue.

### Other

> Look, i have made extension (30 lines of css) for myself which make main exchange page look more binance-like (read normal exchange)

This issue based the design and work on a mockup, and what you display is not the same. I get your point, but we're discussing implementing the UX that was approved to be used.

The mockup also removed any third column (left + center + right) and wasn't something I was working on because of this. 

Other changes have been addressed on #1838 #1839 #1837 


## Finally
Since we're so close to a release I advice right now that we delay this implementation.

We have more questions to solve right now and to little time before a release.

We need to reanalyze and find a way to work forward, we might need to change our aproace to this design.

**Comment by startailcoon** [comment]
As we open this issues back up I see we have a few options here
I'm open for all suggestions.

### Option 1
Continue work and change whatever isn't working from the UX mockup.
This is an option I think would still be possible, but we need to iron out the design issues.

### Option 2
Keep the design we had, but implement a mobile view to enhance the mobile experiece.
This would be a good option for enhancing the mobile friendlessness. 
This would be placed in its own issue for mobile usage.

### Option 3
Rework the whole UX Design from scratch.
This would be an expensive option, but perhaps it's necessary.

**Comment by dot5enko** [comment]
@startailcoon of course there is no reason to rework whole UX, we should make something worse from what we have, so this is `option 1`

Please, make the default layout to be one with left or right orderbook (Horizontal layout) cause i guess nobody from people who trade now on bts would find the way to show it and this is most suitable for trading layout

**Comment by startailcoon** [comment]
I've assigned myself to these issues to work on the polishing. Work will continue on thebranch of this issue https://github.com/bitshares/bitshares-ui/tree/1477-ExchangeRedesign

This issue is kept open for general discussion and tracking outside the current open issues.

**Comment by wmbutler** [comment]
I've closed this so it can be paid. Please do not re-open.

**Comment by happyconcepts** [comment]
I can't stand it. You pay yourself thousands of dollars, but the redesign does not impress...and then new issues (many) are created to "polish" the design and the very same selfish Dev immediately claims the new bounties.

I suggest you let someone else take a shot so you don't stall the whole bitshares-core community another 3 months while you get paid to fool around.

**Comment by sschiessl-bcp** [comment]
> I can't stand it. You pay yourself thousands of dollars, but the redesign does not impress

 - The redesign followed the mockups
 - The issues, if they are a bug introduced through the new design, should be rated taking that into account (i.e. could be rated 0 depending on the case)

**Comment by dot5enko** [comment]
@sschiessl-bcp i support @happyconcepts 

- tons of issues are self assigned for month and that people do nothing -  thus removing possibility of taking this issues from another people.
- Cant say that this task was followed the mockups - they really look great, which i can't say about implementation. 
- @wmbutler, why this issue should be paid as its not completed (did bounty section of repo changed or i miss something ? - task is not finished nor merged into active branch) ? 
- i see 5 subtasks which are required to close this issue and here @happyconcepts  is right, because everybody would forget such a thing because 2500 USD bounty would be already paid for unresolved task. 
- I would suppose not paying untill all related  [Exchange Redesign]  tasks would be done (which, explicitly should be rated [0])

**Comment by sschiessl-bcp** [comment]
I have updated the new issues in two categories, my personal opinion and if not acceptable please restructure
- [Exchange Redesign]: 
This is a helper issue to finalize this task, *should* not be rated imo
- [Exchange Refinement]
The community feedback led us to new ideas how the exchange *should* look like. These issues are further refining the layout, are not part of this issue and should be rated

**Comment by startailcoon** [comment]
All acceptable 👍

Items related to "Exchange Redesign" issues will be without any extra charge. I'll assign these to me. 

New features and ideas, refinements, will be estimated.

**Comment by froooze** [comment]
The UI-Team needs to accept the [KISS principle](https://en.wikipedia.org/wiki/KISS_principle), and that means we don't need 5 different layouts, which have no advantage other than confusing.

We should only implement two different layouts with options to change/add/hide some things. 
A basic layout as simple as possible for people with small screens or beginners and one layout for advanced user or larger screens.

Boxes should always use the space as efficient as possible. The consumption of vertical space should be reduced to a minimum.

**Comment by startailcoon** [comment]
This is why I propose to scrap the layouts as part of #1888

We will make this work
