### ISSUE TITLE
[10][kapeer42] Account page, Proposed transactions

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1482]
UX in #1284

**Comment by kapeer42** [comment]
Can I claim this?

**Comment by kapeer42** [comment]
@ahdigital Can you clarify what the `Approver(s)` column's data is?

**Comment by ahdigital** [comment]
@abitmore Quick question. This was approved in #1284 but I wanted to check, in the example below should the approver circled in red technically be there since the first operation in that group is in fact multisig? I'm thinking not.

![image](https://user-images.githubusercontent.com/3088454/39856831-3b9f423a-5429-11e8-9a80-dd1314ce69d1.png)

In terms of the tool tip, I think the only thing we can use is something like "Failed to execute" until the issue 729 on core is complete. I think it's due to be included in the next hard fork, right?

**Comment by abitmore** [comment]
Show here the data in "required_xxx_approvals".

**Comment by abitmore** [comment]
> Right now I mark the proposals as failed when they are approved (>= 100%) but still in the list and show "Failed to execute." in the tooltip.

@kapeer42 please also check if the proposal has a `review_period_time`. If it has, don't show "failed to execute".

**Comment by kapeer42** [comment]
@abitmore Thanks!

@ahdigital Here is a peak at the work in progress, tell me what to change.
### Only one active key
![bts_1482_singlesig_wip](https://user-images.githubusercontent.com/35779885/39930568-5e380c10-553b-11e8-8847-640b56e7504b.png)
### Multiple permissions
![bts_1482_multisig_wip](https://user-images.githubusercontent.com/35779885/39930598-7146f5c8-553b-11e8-83c1-95ba28e853e0.png)
### Permission tree details
![bts_1482_perm_tree_wip](https://user-images.githubusercontent.com/35779885/39930614-79d42f58-553b-11e8-93b5-bebc40492c91.gif)

**Comment by wmbutler** [comment]
Probably not. What is your preference? Would you prefer to expand scope and add hours or limit scope and keep hours the same and address the additional work in a separate issue?

@abitmore might be nice to get your thoughts here.

**Comment by svk31** [comment]
I kinda thought I'd taken the recursion depth into account but maybe not. I suppose it's a ui issue in the sense that the ui should inform the user that the proposed transaction cannot be confirmed due to the recursion depth being too great.

**Comment by wmbutler** [comment]
@kapeer42 so, would you like me to extend the hours allotted in this to accommodate the extended scope of work?

**Comment by kapeer42** [comment]
@svk31 I will implement your solution
@wmbutler yes please

**Comment by wmbutler** [comment]
Bumping to 10.
