### ISSUE TITLE
Green and red feed price.

### ISSUE THREAD

**Issue by apiekarczyk** [bitshares/bitshares-ui#1486]
I think it'll be nice to have an eye on feed and settlement price change directions. 

![feedprice](https://user-images.githubusercontent.com/35542307/39662667-c4e7a63a-5065-11e8-9515-48149b5848a5.png)

Red when price go down from last publication and green when go up. 

That's all :)
Thank you.

**Comment by genievot** [comment]
Can i pick this one as well @sschiessl-bcp ?

**Comment by sschiessl-bcp** [comment]
This needs investigation into technical possibilities first. Is the old feedprice available from backend, or immediately dropped when new price is published? In the latter case coloring does not make sense IMO because it would be a local, non-deterministic solution.

Please report
 - [ ] what backend calls are used to fetch feedprice?
 - [ ] what information is available from such a call?
 - [ ] is any historic information available? 

I think there is no history, but you never know. Please open an issue in bitshares-core asking about possibilities of feed price history and link it here. The only one I have in mind would be using Elastic Search.

Estimate 0.75.

**Comment by sschiessl-bcp** [comment]
The answer is already here: #502
No investigation necessary.

Will treat this issue within #502
