### ISSUE TITLE
DEX margin features : base price

### ISSUE THREAD

**Issue by SimonzDiamondz** [bitshares/bitshares-ui#1494]
Hi guys, (new here but BTS investor and active for a longgg time)

Would it be possible to add on the margin position dashboard the base price of the acquisition made with the loan

e.g.: 
i borrow 100 bitusd to buy  
-100 BTS at 0.35
-100 BTS at 0.30
-100 BTS at 0.25
base price = 0.3

It would be easier to manage or to see the p/l.

Thanks!

**Comment by startailcoon** [comment]
How would be calculate this if a user already has a value of the asset it borrows?

Say that I have 100 USD since before, but I wish to aquire more of another asset. I then borrow another 100 USD and buy 200 USD worth of the new asset.

The user has now used 50% of the new aquisition with a loan and another 50% with its own assets.

**Comment by clockworkgr** [comment]
Quite impossible to track acquisitions properly after 1-2 trades & no further response from OP.

Closing.
