### ISSUE TITLE
[3] Support new operations in account activities and block explorer

### ISSUE THREAD

**Issue by tianyekuo** [bitshares/bitshares-ui#1547]
**Describe the bug**
[bsip-0027](https://github.com/bitshares/bsips/blob/master/bsip-0027.md) Asset Issuer Reclaim Fee Pool Funds: backend support the API in the next release, frontend should support the new operation.

**To Reproduce**
1. call the api by the latest cli_wallet: claim_asset_fee_pool GDEX123ABC0 100 true
2. Open the user activity page
3. Check the latest record
4. Click the block num in the record
5. Check the block info page

**Expected behavior**
Step3 and step5 should show the user claim asset fee pool funds info.

**Screenshots**
Activity page:
![activity](https://user-images.githubusercontent.com/1351064/40354844-76d7224c-5de7-11e8-8f6a-2940d748b89c.jpg)

Block page:
https://testnet.bitshares.eu/block/17531683
![block](https://user-images.githubusercontent.com/1351064/40354859-7e29fbbe-5de7-11e8-9847-10882f51f6af.jpg)

**Comment by abitmore** [comment]
Updated https://github.com/bitshares/bitshares-ui/issues/1493 to include this.

**Comment by startailcoon** [comment]
Please verify that the follow is correctly translated

### Account Transaction
![bild](https://user-images.githubusercontent.com/12114550/41378490-7bd30318-6f5f-11e8-9f10-86dd7337b7d1.png)

### Block Operation
![bild](https://user-images.githubusercontent.com/12114550/41378524-9417ddae-6f5f-11e8-917f-10020005d304.png)

**Comment by startailcoon** [comment]
## New OPs to support in UI from BitsharesJS
- [ ] fba_distribute: 44,
- [ ] bid_collateral: 45,
- [ ] execute_bid: 46,
- [x] asset_claim_pool: 47,
- [x] asset_update_issuer: 48

**Comment by abitmore** [comment]
Thank you @startailcoon.
* "claim pool asset" sounds a bit strange. Perhaps better name it "claim asset fee pool"?
* I think it's better to use "ACCOUNT claimed x YYY from asset ASSERT's fee pool" as description
* "transfered" is typo, should be "transferred".

**Comment by startailcoon** [comment]
@abitmore new snaps according to your suggestions
![bild](https://user-images.githubusercontent.com/12114550/41381560-a813c6d4-6f68-11e8-920a-e60fbb4fe83f.png)


![bild](https://user-images.githubusercontent.com/12114550/41381524-87aa034a-6f68-11e8-9537-392589e4e7ab.png)

**Comment by startailcoon** [comment]
# OP 45 - bid_collateral

### Block TX
![image](https://user-images.githubusercontent.com/12114550/41434540-691ea3a4-701c-11e8-9252-9cfa04f22267.png)

### Account History
Since I can't see the tx in the account history, since it's to old, this is how it would look like

```abit updated collateral with 2,000,000 BTS for 79.813058 bitGOLD```

# OP 46 - execute_bid
This operation is a virtual OP and isn't visible in the block. One is included in block [22513611](http://cryptofresh.com/b/22513611) for operation [1.11.102370951](http://open-explorer.io/#/objects/1.11.102370951).

### Account History
I'm not sure if this is visible in the account transaction history, but if so it needs a translation for the following. 

```
[46,{"fee":{"amount":0,"asset_id":"1.3.0"},"bidder":"1.2.12376","debt":{"amount":"283881176519","asset_id":"1.3.0"},"collateral":{"amount":79813058,"asset_id":"1.3.106"}}]
```

# OP 44 - fba_distribute
This operation is related to stealth operations, and handles routing of fees for FBAs (fee backed assets). 

This operation is also only a virtual OP, and isn't visible in the block explorer. One is included in block [22513611](http://cryptofresh.com/b/22513611) for operation [1.11.219853425](http://open-explorer.io/#/objects/1.11.219853425)

### Account History
This is the string that needs a translation. Note that it doesn't have any asset_id parameters, only an amount and a fba_id. The `fba_id` gives the asset_id relation for the fee backed asset, in this case it's [STEALTH](http://open-explorer.io/#/objects/1.3.743). The amount is the base asset (I presum).

```
[44,{"fee":{"amount":0,"asset_id":"1.3.0"},"account_id":"1.2.107093","fba_id":"2.16.1","amount":900000}]
```

I propose we use something like this
```Deducted 9 BTS from fee backed asset STEALTH```

**Comment by abitmore** [comment]
@startailcoon all these entries should be in account history.

For description for the 2 bid related operations please check [BSIP18](https://github.com/bitshares/bsips/blob/master/bsip-0018.md).

For the FBA operation, please check histories of these accounts:
* https://wallet.bitshares.org/#/account/stealth-buyback
* https://wallet.bitshares.org/#/account/stealth-mgmt

Unfortunately I didn't find technical specification documentation about it. Related code in bitshares-core is [here](https://github.com/bitshares/bitshares-core/blob/b28b0ce969e031610c4ddb6e2ef595d803832ee9/libraries/chain/db_maint.cpp#L525-L610).

**Comment by wmbutler** [comment]
Was your time fair on this?

**Comment by startailcoon** [comment]
I still need to fix the remaining OPs. Keep this open and increase to 3 hours in total.

It will need a second PR to be done.

**Comment by startailcoon** [comment]
I will still find time to look at this and verify the need for any missing logic. Pushing it to next release for now.

**Comment by startailcoon** [comment]
### OP 44, fba_distribute
I need some suggestions on how we should display this OP.

OP is virtual, and contains the following

```
{
  "account_id": "1.2.102338",
  "amount": 24314,
  "fba_id": "2.16.2",
  "fee": {
    "amount": 0,
    "asset_id": "1.3.0"
  }
}
```

It contains the account, amount and a link to the fba asset id.
Fetching the data from the fba asset id to fetch the details for it.

What does this operation actually do? Where does the asset go that is distributed? Is the following enough information and is it correctly displayed?

![bild](https://user-images.githubusercontent.com/12114550/49343507-d082cf00-f66a-11e8-9502-f8130b910a04.png)

**Comment by startailcoon** [comment]
All possible and necessary OPs included by today. OP44 isn't widely used.
