### ISSUE TITLE
[0.5] Hot Switching accounts in vesting balances screen

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#160]
When changing from one user to another, the wallet should load the appropriate vesting balances for each account. Currently, it's not updated.

See the two different accounts at the top, but the vesting data did not update.

![screen shot 2017-05-31 at 1 01 29 pm](https://cloud.githubusercontent.com/assets/1254810/26643996/4a88b6a0-4601-11e7-91e2-e4c791660dcf.png)
![screen shot 2017-05-31 at 1 01 19 pm](https://cloud.githubusercontent.com/assets/1254810/26643997/4a941770-4601-11e7-9a21-e9867ab70411.png)

**Comment by wmbutler** [comment]
#139 carried the hours for this issue.

**Comment by calvinfroedge** [comment]
Resolved by [PR 283](https://github.com/bitshares/bitshares-ui/pull/283). This issue was caused by component not triggering updates on account changes.

Vesting balances now update as expected.

![issue-160](https://user-images.githubusercontent.com/632938/29440368-c86d0362-8389-11e7-94ce-0e88dcafbac3.gif)
