### ISSUE TITLE
[2][gibbsfromncis] Improved Witness Information Page

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1636]
See UX at #1436

**Comment by gibbsfromncis** [comment]
On the mentioned UX was used old styles. Please make sure to use new styles from style-guide (like tables) - https://styleguide.bitshares.org/#/dark

**Comment by gibbsfromncis** [comment]
I've decided to take it

**Comment by gibbsfromncis** [comment]
@wmbutler Unfortunately Dominic didn't provide UX for Card View of witnesses:

<img width="1401" alt="screenshot 2018-07-03 05 01 58" src="https://user-images.githubusercontent.com/35899973/42196447-45fb03de-7e7e-11e8-9492-b3ae57b540ed.png">

Should I leave Card View as it or we can redesign it in scope of this issue? If we are going to redesign Card View too please set hours for UX to this issue

**Comment by svk31** [comment]
I say we just remove the card views. The committee member page also uses the same structure and could be updated as well.

**Comment by gibbsfromncis** [comment]
@svk31 is it proposal or already agreed decision to remove card view?

**Comment by svk31** [comment]
It's a proposal from me since the data can be presented in a much cleaner way using tables like the proposed UX from ahdigital.

**Comment by wmbutler** [comment]
I agree that removing the card views would be a good idea.

**Comment by gibbsfromncis** [comment]
@startailcoon I've updated both pages: Committee and Witnesses. Also I played with tabs content background because it looks terrible:

Production:
<img width="1400" alt="screenshot 2018-09-05 07 59 05" src="https://user-images.githubusercontent.com/35899973/45073898-93498800-b0e1-11e8-81a1-b472f32131a3.png">
<img width="1401" alt="screenshot 2018-09-05 07 59 18" src="https://user-images.githubusercontent.com/35899973/45073906-993f6900-b0e1-11e8-9df4-0c0c61e883c2.png">

After my fix:
<img width="1399" alt="screenshot 2018-09-05 07 59 39" src="https://user-images.githubusercontent.com/35899973/45073925-a6f4ee80-b0e1-11e8-88b5-b3424ecc3822.png">
<img width="1400" alt="screenshot 2018-09-05 07 59 32" src="https://user-images.githubusercontent.com/35899973/45073926-a6f4ee80-b0e1-11e8-85bd-a9314ffc8920.png">

@startailcoon can I ask you please to update estimate to 4h because Committee and Tabs Content background issues wasn't in scope (it wasn't simple fix of `background-color` property, I've tried to find the best solution to fix it in all themes and make them look good but in result I had just to update tab-content background for Explorer tabs and some elements background from Assets, Markets etc.)

**Comment by sschiessl-bcp** [comment]
Closed via #1815
