### ISSUE TITLE
Why 1 account per IP address ?

### ISSUE THREAD

**Issue by jealuc** [bitshares/bitshares-ui#1655]
**Is your feature request related to a problem? Please describe.**
1 account per IP is really a very bad move and impedes growth. It will result in more people not using Bitshares. Also it hurts privacy. It is not possible to understand why that move would be implemented in a decentralized platform.

**Describe the solution you'd like**
Removing the 1 account per IP restriction.

**Describe alternatives you've considered**

**Additional context**

**Comment by svstoneage** [comment]
Agreed.  Only one account per isp is crazy...  I do understand the reason.. Upgraded accounts earn fees and those fees can be stacked.  
Solution...  Only one UPGRADED  account per isp.  As many 'free' accounts per isp as a member would like.

**Comment by sschiessl-bcp** [comment]
Please do not open another issue on that, keep the conversation in here.

**Comment by clockworkgr** [comment]
Hello to everyone in the Compumatrix community that raised this issue.

Although we appreciate your enthusiasm, it makes the UI team's work much much harder if you are opening multiple tickets for the same issue, so please conversation in one place from now on.

Now, to the issue at hand, as I explained at your Discord server, BTS accounts are NOT free. There is in fact a registration fee attached. This is normally funded by the registration faucet which is partly self-funded  (from registrar fees) and partly community-funded (donations).

The faucet mechanism itself is maintained by a community member as a helpful service.

It is for those reasons and those reasons and only that a limit is in place to allow only 1 account per IP every 5 minutes to stop automated registrations that could drain the faucet and stop registrations altogether.

I have notified the faucet maintainer to check the limit is resetting properly so it should be ok.

I would suggest however that Compumatrix as a separate organisation, with its separate "gated" community of private Discord and limited access to bitshares information for its users, runs their own faucet rather than taking advantage of a service provided by a community they don't want to be a part of. 

If any Compumatrix members would like to know more about the BitShares ecosystem and the work of the community that Compumatrix leverages to provide its own services (whatever they are), whether it is the people developing the core software or the UI software/wallet or running and maintaining servers and faucets etc. etc., please check the following links:

https://t.me/BitSharesDEX
https://discord.gg/zYMc4Ak
https://bitsharestalk.org/index.php
https://steemit.com/created/bitshares
https://committee.bitshares.works

Thank you.

**Comment by sschiessl-bcp** [comment]
I reopened this issue for visibility of Alex's statement if any more Compuceeds members are coming

**Comment by hubba1** [comment]
I would still like to know WHY our IP addresses are being looked at...that is un-nerving

**Comment by hubba1** [comment]
BTS discord channel isn't welcoming of inquiries ....kind looked at like a cow with two heads...

**Comment by clockworkgr** [comment]
@hubba1 I explained why IP addresses are looked at above. To stop automated account creation that would drain the faucet.

If that is unnerving you should take a look at: https://www.compumatrix.com/privacy/

> Device information. We may collect information about devices you use to access the Services and how you use the Services, such as your IP address and which websites you visited before accessing our Services.
> 
> Logs. Our servers automatically record information created by your use of our Services to help us diagnose and fix technical issues and to improve the overall quality and user experience of our Services. Logs may include information such as your IP address, browser type, operating system, details of how you used our Services (such as your commands at the command line), diagnostic information related to the Services (such as crash activity reports), the referring web page, pages visited, location, your mobile carrier, device, and application IDs, search terms, and cookie information. 

I don't remember any inquiry from compumatrix members and I'm a mod there. Community discussion is more active on telegram to be honest.

**Comment by clockworkgr** [comment]
Your IP address is visible to anything you use / visit on the internet. The reference wallet faucet is very specific on what it's used for. If you don't like it, please petition compumatrix (whose privacy policy is much much worse) to run their own faucet instead of taking advantage of the community while fudding it at the same time.
