### ISSUE TITLE
Block Inquiries of member's accounts by non-members

### ISSUE THREAD

**Issue by netmla9393** [bitshares/bitshares-ui#1690]
1. **Is your feature request related to a problem? Please describe.**

The problem is that strangers are able to view your Openledger (wallet) accounts contents. You don't let strangers see what's in your bank account. Why would you want to let strangers see how rich or poor your are, what coins you have or don't have etc..?  

2. **Describe the solution you'd like**
 
I want all users to be logged in before they can view any account data. Currently Cryptofresh and bts.ai seem to be able to see your account data without being logged into it. The Openledger wallet needs to compare the owner with who is trying to view it.

3. **Describe alternatives you've considered**

If this is not or cannot be a private account, it should be publicized that it's not when you sign up. It should be in bold on the create screen when you sign up and you should have the option of backing out or of setting your information private and not viewable if you have both options (private/non-private).

4. **Additional context**

http://cryptofresh.com/u/<user-name>
http://bts.ai/username

**Comment by startailcoon** [comment]
Before I answer your comment I'd like to point out that this repository is **not** OpenLedger. This is the Bitshares Reference Wallet,. OpenLedger uses the codebase for their own wallet online. Any issues or requests you have with OpenLedger should be posted to them on [OpenLedger Support](https://openledger.freshdesk.com/support/home)

Now, let me try to answer some of your quests as well.

BitShares works the same way as any other cryptocurrency chain. The ledger is public and verifiable, meaning that anyone can look up any address, or in bitshares case names, to see that the ledger is correct. The pages you link to in the post follows the flow of the ledger and can easily calculate the sum of all accounts. 

You can't "force" people to log in before they can see an account, as the ledger is fully public. If you don't want certain people to know about your assets, I'd suggest you create an account with a name that aren't easily assigned to you in person.

Bitshares uses usernames rather than change addresses, and one "drawback" if you would say so, is that all transactions are always connected to the username.

Regarding your idea about having a bold sign on signup, I'd advice you to take this to OpenLedger which who you created your account with (if I understood you correctly).

If you find this an issue, I'd advice you to rethink the way you use the Bitshares network, which OpenLedger is opperating on.
