### ISSUE TITLE
Referral links don't work on bitshares.org (work on openledger.io)

### ISSUE THREAD

**Issue by o5j5vg55bv5hv5j5f8799f9** [bitshares/bitshares-ui#170]
I have tried creating several accounts using bitshares.org interface

for example https://bitshares.org/wallet/#/market/BTS_OPEN.BTC?r=mybtsname
or https://bitshares.org/?r=mybtsname

Using account model. Every time the membership said my referral was from openledger

Doing same thing but with https://openledger.io/?r=mybtsname
or https://openledger.io/market/BTS_CNY?r=mybtsname

did however register my referral from right username instead of openledger

Thanks.

**Comment by pmconrad** [comment]
The first is a user error. The part of the URL after the hashtag is not transmitted to the server. You must insert the referrer parameter before the hashtag, i. e. https://bitshares.org/wallet/?r=mybtsname#/market/BTS_OPEN.BTC should work.

The second is strictly speaking not a ui issue. Apparently the bitshares.org site doesn't forward the referrer parameter to the wallet. I don't know who operates / maintains that site.

**Comment by Ashaman-** [comment]
My experience was the exact opposite - it works on bitshares.org/wallet, but openledger seems to ignore it....

**Comment by happyconcepts** [comment]
This does not appear to be either satisfactory system behavior or user error. 

The referral link shown on my LTM screen is an openledger address. New account opened with that link is ok on openledger...but not on bitshares.org. Attempting login on bitshares will disappoint the new account because it will force a create account option _and_ inform the user that the accountname they just registered is taken (if they try to sign up again).

**Comment by happyconcepts** [comment]
Maybe Stan or cryptonomex can check it.

**Comment by wmbutler** [comment]
I've used the referral link successfully. Please provide evidence of the failure and will reopen.
