### ISSUE TITLE
Change Referral Link under Membership Tab

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#171]
Currently pointing to https://bitshares.openledger.info - OL recently changed to https://openledger.io as default domain,

https://openledger.io?r=ID should be the correct link

**Comment by landry314** [comment]
the ".io" address does not work for me.

but, actually, links on mobile phones in messengers will not highlight the entire link in this format without the / after .info ; the referral name will get lost if it is simply tapped on instead of copied and pasted.

this format will insure that tapping the link will include the referrer:

https://bitshares.openledger.info/?r=REFERRERNAME

**Comment by landry314** [comment]
please update the GUI to make the link highlight correctly by adding a "/".

**Comment by wmbutler** [comment]
Easy win by adding a `/` before the `?`

![screen shot 2017-07-21 at 3 14 08 pm](https://user-images.githubusercontent.com/1254810/28480643-43b26dd2-6e27-11e7-9926-afee9daede60.png)

**Comment by landry314** [comment]
super easy! i bet a lot of people's promotional distribution of their referral links didnt lead to them being the referrer due to the tap not using the whole link.

**Comment by landry314** [comment]
also, if there is a way to add the referrer in the light wallet there should be some help there about this too!

let's say i go to a friend's place and set up the wallet on his computer, how would i make myself the referrer? this should be explained there! (i acutally dont know and i need to know)
