### ISSUE TITLE
Include full serach results under the main Featured Markets search tab

### ISSUE THREAD

**Issue by jcalfee** [bitshares/bitshares-ui#1712]
Please consider including full results under the main Featured Markets search tab (just put the featured ones at the top).

We had a hard time finding the new open.EOSDAC pairs.  This is not easy to find on wallet.bitshares.org .. We found it only after loading the Exchange tab then using Find Markets on the right. 

![image](https://user-images.githubusercontent.com/204121/43012511-f85d0e24-8c0b-11e8-8100-dbae89689289.png)

**Comment by startailcoon** [comment]
Do I understand you correctly, that you wish to have a way to find pairs not listed in the featured markets to show up when you search for an asset?

As in your case, you can't find open.EOSDAC since it's not in the list to begin with, and you wish to have it show up when you search for it even though it's not in the list.

The current develop version, soon to be released, contains a feature on the Exchange tab that makes finding trading pairs much easier, especially if you're looking for markets with volume. The main page `Starred Markets` and `Featured Markets` have been discussed internally for a change though.

### Here's a preview of the feature I mention

![bitshares-marketsfinder](https://user-images.githubusercontent.com/12114550/43047044-46263e24-8dd2-11e8-95b7-5e03c2952140.gif)

**Comment by svk31** [comment]
Hey James, long time no see :) 

We've already had multiple issues about the search already, the main reason it's clunky is that the asset search api is shitty and always has been.

If open.eosdac is the official openledger eos asset we can add that to the list of assets included in the default markets list.

**Comment by jcalfee** [comment]
HI, come to Alacapulco and we can hang out!  Ken Code, Thom plan to go.  I usually see onceuponatime there too and I would like Luke Stokes is going again..  Lots of fun..  Modprobe is in that area too, we may see him.

If I recall, the open. ensures it must be an openledger asset..  If that is the case, that would be great, Luke is doing great work on that project..

Ok, hope you can find a low maintenance way to pull off the search.  If you add another html section after "featured" like "other assets" then it will be non-mission critical that it works.  If it works most of the time it will help over time..  Small things like this add up..
