### ISSUE TITLE
[1] White screen after losing connection or failing to ping/connect to any nodes

### ISSUE THREAD

**Issue by cogutvalera** [bitshares/bitshares-ui#1770]
**Describe the bug**
White screen only is seen on Ubuntu (16.04 and 18.04) for BitShares UI 180808 .deb release

**To Reproduce**
1. Go to `https://github.com/bitshares/bitshares-ui/releases`
2. Download `.deb` 180808 release
3. Install `.deb` on Ubuntu 16.04 or 18.04
4. Run 180808 release on Ubuntu and you will see only white screen

**Desktop (please complete the following information):**
 - OS: [Ubuntu 16.04, Ubuntu 18.04]
 - Version [latest UI 180808 release]

**Additional context**
1. https://pastebin.com/fwZeHQeQ  -  console errors on Ubuntu 16.04
2. https://pastebin.com/kwd0xYxF  - console errors on Ubuntu 18.04

**Comment by cogutvalera** [comment]
after some hours I've checked again on Ubuntu 18.04 and it works now well enough ! I close this issue !

**Comment by clockworkgr** [comment]
this happens on my android as well...white screen after intialising local databases

**Comment by BazkieBumpercar** [comment]
Nope, still happens on my Debian.

Solution: cleared application data. Now it works. This should happen automagically though (and ideally only the applicable keys)

**Comment by startailcoon** [comment]
@svk31 mentioned that this issue only required a refresh (F5). But if this is not the case it should have someone taking a deeper look at why this happens.

**Comment by cogutvalera** [comment]
Refresh (F5) didn't help me, just after some time it started to work on my both Ubuntu 16.04 & 18.04 magically well enough without white screen issue

**Comment by cogutvalera** [comment]
also @clockworkgr Alex mentioned the same issue on his Android devices

**Comment by webpubrepo** [comment]
This white screen is on Mac as well using Firefox.  Since the 180808 release 3 days ago it has been impossible to connect with the wallet.bitshares.org interface as usual.

**Comment by svk31** [comment]
The initial bug report is two different issues, the 18.04 issue is from using an API node that's out of sync, which apparently causes the init chain to fail.

The 16.04 is from failing to load the indexeddb properly, which is an issue we've encountered before and fixed but is apparently back. It's something that's extremely hard to debug since it's impossible to reproduce.

One thing that's essential to know is the browser and browser version you're using when encountering the issue, and whether it's in incognito or not. Incognito in firefox just doesn't work period.

**Comment by BazkieBumpercar** [comment]
I'm using the Linux gui client; if I open the developer console inside it, it seems to be running Chrome 61 internally.

**Comment by svk31** [comment]
OK I was able to reproduce this by accident, I had a wallet session open and while I was away the internet fell out and this happened, which allowed me to debug it. It's caused by all nodes failing and the Footer component ending up with an empty array of nodes that it tries to use to dispay current node information.

**Comment by RobJah** [comment]
People please help! I cant use any BTS wallet on any browser or downloaded wallet version anymore!
They all give me the white screen, after saying it has 'established a connection, initializing locel database'

i have downloaded the latest version of the wallet aswell but to no avail.
please help!

**Comment by startailcoon** [comment]
Please see if this solves your issue

https://github.com/bitshares/bitshares-ui/issues/1810#issuecomment-417947711
