### ISSUE TITLE
[Staging] Visualization issues with new Exchange Layout

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1822]
Visualization issue with new Exchange Layout

- [x] Contrast of fee in Buy and Sell are is insufficient in Light and Dark theme. Adjust for clear contrast
Example dark theme: Left is normal, right on hover
![image](https://user-images.githubusercontent.com/33128181/45153795-7ee6b780-b1d5-11e8-8197-f9f6b374eeb7.png)
- [x] When first opening the Exchange, neither My Markets or Find Markets is selected, empty gray area is shown. Set My Markets as default
- [x] Buying via bridge is prominently placed as "Quick buy" next to Market "Buy". Needs discussion
- [x] In Buy Orders: Volume and Group Button should be aligned
- [x] In Buy AssetName: In the default layout it had the little horizontal arrows to switch with Sell and also vertical errors. After clicking the vertical arrows, the arrow icons are gone.
Default Layout, nothing clicked:
![image](https://user-images.githubusercontent.com/33128181/45154092-a8eca980-b1d6-11e8-8359-3c581e79d864.png)
After clicking vertical arrows:
![image](https://user-images.githubusercontent.com/33128181/45154049-7d69bf00-b1d6-11e8-9190-db13d3d5b6f7.png)
- [x] Calling the exchange Settings only "Settings" is confusing with general Settings. Proposal: "Adjust" or "Personalize"

**Comment by grctest** [comment]
GDEX tooltip hover in market/exchange page shows a missing translation error.

![image](https://user-images.githubusercontent.com/15861527/45160804-3bdf1100-b1e2-11e8-863d-9675be772aec.png)

**Comment by startailcoon** [comment]
Thanks for testing this out. All issues will be ironed out an pushed in a new PR.

Keep them coming as I may have missed a few things.

**Comment by startailcoon** [comment]
# Regarding Quick Buy (Bridge)
Since before we used a simple `Buy xxx` in the header, together with a `Borrow xxx` we had to find a new place for these options.

I can agree that the `Quick Buy` isn't the best wording thinking on the close placement to the trading buy button. Perhaps a `Quick Deposit` is a better word to use. The usage of BlockTrades for quick deposits are indeed a very valuable spot for them, but are the only ones doing none gateway trades what I know of. When a gateway asset is selected, `Quick Deposit` should be through gateways.
