### ISSUE TITLE
[2][2] Implement new ANT tabs for Explorer

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1841]
Explorer to be found at
https://wallet.bitshares.org/#/explorer/blocks

It  has been gradually improvement in last release to include new table for committee and witnesses. This issue is to update the Explorer to generally use the new ANT tab component from BitShares Style Guide.

- [x] Evaluate current code, if not already the case then
  - [x] Move every Tab into a separate component
  - [x] Remove all cross-tab dependencies
  - [x] Use lazy loading of the tabs (meaning: Only initialize tabs that the user clicks on)
- [x] Integrate ANT tab from BitShares Style Guide

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp if you OK I'll assign myself

**Comment by sschiessl-bcp** [comment]
Needs rating first

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp 
> Move every Tab into a separate component
> Remove all cross-tab dependencies
Can you please clarify what do you mean? 

> Use lazy loading of the tabs (meaning: Only initialize tabs that the user clicks on)
Ant Tabs already have this feature. 

Tabs used in 15th places in our project. Some tabs replacing will be hard because there may be UX issues like for Asset Update:
<img width="1397" alt="screenshot 2018-09-13 04 25 05" src="https://user-images.githubusercontent.com/35899973/45463636-51d26180-b70d-11e8-9d10-f414857f06ba.png">

It's not possible to use buttons on Ant Tabs. So buttons should be moved on some "top" level or be placed on each tab because ant tabs should fit 100% of screen size to prevent any design issues. 

I would like to ask you to clarify first two questions. 

My estimate approximate estimate is 6h

**Comment by sschiessl-bcp** [comment]
There are no buttons in explorer. Did you mix it up with asset details page?

**Comment by gibbsfromncis** [comment]
> There are no buttons in explorer. Did you mix it up with asset details page?
Yeah.

> My comments are only with respect to the one Tabs layout of the explorer, and inter-tab dependencies within the explorer.

@sschiessl-bcp I suppose it's better to replace our tabs by ant tabs everywhere right away. I don't see any reasons to keep old tabs somewhere if we start its replacement.

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp what kind of refactoring are we talking?

**Comment by startailcoon** [comment]
I would agree that we should implement the new ANT tabs for the whole application, but we should make one section at the time. I understand your point in replacing all Tabs at once @gibbsfromncis, but as buttons aren't possible in the ANT tabs, we would be required to make a new UX for those places. 

If a section with Tabs needs to be reworked, we should do it within their own issues. Create/Update assets has its own issue #1816, which should include this change as well.

We could include the following places that has tabs that isn't requiring an updated UX proposal
- Manage Accounts (Accounts in Drop-down list)
- Voting
- Assets
- Signed Messages
- Membership Stats
- Vesting Balance
- Whitelist

If we wish to be consistent, this should be done at the same time as #1816. 
I'd set 1 hour for this work.

The only other page that needs a new UX because it has buttons in the Tabs navigation is `Permissions`.

**Comment by gibbsfromncis** [comment]
@startailcoon Do you want to replace tabs for a whole application in a scope of #1604 issue?

**Comment by gibbsfromncis** [comment]
@startailcoon I remember some problems I met when start to use ant tabs in our app. I'm not sure actually that 1h estimate is enough but lets see when I finish

**Comment by startailcoon** [comment]
We can increase hours if required of course

**Comment by gibbsfromncis** [comment]
@startailcoon I've added label, project and sprint to this one.

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp PR: #1904

**Comment by sschiessl-bcp** [comment]
Closed by #1904
