### ISSUE TITLE
 application initialization issue

### ISSUE THREAD

**Issue by CharlesZHENG** [bitshares/bitshares-ui#1850]
**Describe the bug**
I set up a private testnet, but when i refresh the web wallet,i always get the webpage

![Uploading 图片.png…](https://note.youdao.com/yws/api/personal/file/CA45827A59C34CAF9C600B6588D1C387?method=download&shareKey=c5d48071550b20f4701bd3fb7a68f5b6)
try local node is no luck.
then I switched the other node,click `retry` button is ok.Then I click `Settings`-->`Nodes`, select my local node is ok.
please help me

**Comment by grctest** [comment]
I'm also getting this. If I select a public api node (non-private testnet) it will connect, to which I can switch to my private testnet servers but upon attempting to import the nathan WIF keys into the client it gets stuck and eventually I get kicked back to this application initialization issues page.

I've changed the chainId and default asset names for my private testnet.

semi-related issue raised due to the above error: https://github.com/bitshares/bitshares-ui/issues/1772

**Comment by nathanhourt** [comment]
I'm having this problem as well, and it's super annoying. This screen should clear once the node status goes to `CONNECTED`... but can we at least get a button to go back to the normal UI? This deadend page is extremely frustrating; it's the moral equivalent of "The backend is working, and I'm connected to it, but screw you just because"

**Comment by dls-cipher** [comment]
Keep the BTS to yourself and try this:

Deploy Let's Encrypt SSLl certificate bot with nginx as handler of SSL requests and try connecting with "wss://" instead.

UI will not connect to an API node without SSL protection on it, only cli_wallet (and any custom apps) will.

I'm not sure about my statement above, but it cost you nothing and I believe it work.

Chee®s

**Comment by sschiessl-bcp** [comment]
This is likely due to the chain id. Will be adressed with #2044

**Comment by nathanhourt** [comment]
@dls-cipher Finally got that done, as it did need to be done anyways, but alas, it does not improve the situation. I still get funneled to the _Application initialization issues_ deadend page, even when my node is hosted over wss://
