### ISSUE TITLE
[0.5] Non divisible asset vs Non divisible asset in the DEX allows fractional pricing in orderbook

### ISSUE THREAD

**Issue by steempower** [bitshares/bitshares-ui#186]
Whaleshare and Beyondbit are non divisible assets. On the DEX for example Whaleshare:Beyondbit the GUI is allowing decimal pricing despite BOTH assets being non divisible.

In the GUI orderbook it display's as a whole number followed by a decimal place but no decimals. For example a price of .76 or 1.26 displays on the GUI DEX as '1.' if a user was to click on that order in the orderbook then the actual price of 1.26 is populated into the price field but when you proceed with the buy order it is rounded up to the next integer e.g 2.

Example: I tried to buy 1 beyondbit for 1.26315789 Whaleshare which resulted in the price being rounded up and me paying 2 whaleshares and only receiving 1 beyondbit. Blockchain shows price of 2 whaleshare/beyondbit for both the place order and the fill order operation.  

http://i.imgur.com/xawP0HM.png

I was thinking this was a blockchain issue as the prices underlying the display bug in the order book are fractional but it seems (as mentioned above) if i place a fractional order in the GUI then look at the TX in the chain it shows a round number not the fractional price that was entered in the GUI.

**Comment by wmbutler** [comment]
Seems like the front-end should do the rounding as the user enters the value based upon the known precision of the currency.

**Comment by wmbutler** [comment]
@svk31 @xeroc This warrants some discussion so the GUI is intuitive and guides the user appropriately.

**Comment by svk31** [comment]
Similar to #314 , although non-divisible assets have some additional issues with respect to rounding in the orderbooks that I can look into.

It is obviously not possible to buy 1 beyondbit for 1.26315789  Whaleshare, since Whaleshare is a non-divisible asset, however that price is valid for the quantities defined in the existing order that you clicked on. To perform a partial match you then have to offer the next possible better price, which in your case was 2 whaleshare for 1 beyondbit, that is correct and how it should work.

__In general trading with non-divisible assets is a bad idea and will result in very confusing pricing.__

**Comment by svk31** [comment]
![image](https://user-images.githubusercontent.com/6890015/30053652-d338d5ba-9229-11e7-9b93-3b811685070d.png)
