### ISSUE TITLE
[Exchange Refinement] Personalize option to hide chart

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1902]
I often have the case that I know exactly what I want to sell or buy, and on the phone the TradingView overhead is simply killing all the fun ...

**Tasks**
- [x] Add an option that hides the complete chart, via "Personalize"
- [x] Ensure that the "Personalize" modal is available in mobile and mobile friendly

**Comment by startailcoon** [comment]
Isn't the hiding of the chart enough on mobile? It uses the `<Collapse />` component. If it isn't toggled it wouldn't load at all.

I could see this as an option when you use a mobile device that's slighly larger than the trigger for a mobile device, and wish to hide the chart though, if that is what you think about, otherwise it wouldn't be an issues in my opinion.

I'll add the "Hide chart" option though.

**Comment by sschiessl-bcp** [comment]
> I could see this as an option when you use a mobile device that's slighly larger than the trigger for a mobile device, and wish to hide the chart though, if that is what you think about, otherwise it wouldn't be an issues in my opinion.

Pretty much, I also sometimes feel on my laptop that TradingView is simply taking forever. It is also quite intrusive, I am thinking about re-introducing the native chart again and let the user choose (I never cared about the chart anyways, but that's for the future and I am not an active trader..)

**Comment by startailcoon** [comment]
> re-introducing the native chart again and let the user choose

It's been up before, while I think it would be a step backwards again, it could make sense to explore ways to see if we can make Trading View less resource hogging. In worst case we could take the legacy one back for "simple" charts, if the difference is large.

**Comment by startailcoon** [comment]
I had to revert my branch thread. New commit for this fix is https://github.com/bitshares/bitshares-ui/commit/9524f4373f7e30f1123399b6892eaf1bbed38077
