### ISSUE TITLE
Refactor HeaderDropdown.jsx and Header.jsx

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1908]
The Header contains heavy code duplication and somewhat inconsistent logic how items are rendered.
A first step was introduced in #1895 for the new "or Legacy" menu items.

This issue targets refactoring of both components.

- [ ] Analyze the existing header row and menu item format. What is different, what is always the same? What special cases are needed? This should be reported back and discussed before moving on
- [ ] Define a dictionary format that will be used for the population of the Header row items (Dashboard, Exchange, etc.) and one for Menu items. See for example https://github.com/bitshares/bitshares-ui/blob/9e153ba8a4bbcd28ed52313b88f29de7457acfbe/app/components/Layout/HeaderDropdown.jsx#L191
- [ ] Abstract the item generation logic. Ideally the items are generated by a method that is fed the dictionary (both header row and menu)
- [ ] Remove code duplication (e.g. in the DOM creation abd the dynamicMenuItem)

My suggestion for the implementation is @kapeer42 as he has already started this with his PR. My estimation for this tedious (and sadly not much visible for the users) task is ~9 hours. It will prepare in the next step to easily define the header and menu style and allow for nested menus.

**Comment by kapeer42** [comment]
Refactoring is love, DRY is beautiful :smile:

(aka "I'm in")

**Comment by sschiessl-bcp** [comment]
Can you clarify what needs discussion? Or what does that label mean? @startailcoon

**Comment by startailcoon** [comment]
`needs discussion` is set due to this in your task description

>  Analyze the existing header row and menu item format. What is different, what is always the same? What special cases are needed? **This should be reported back and discussed before moving on**

It's to highlight that there will/is a discussion thread as well.

**Comment by sschiessl-bcp** [comment]
@kapeer42

Have you started on this task yet by any chance?

**Comment by kapeer42** [comment]
Yes, pls bear in mind this is WIP so might be incomplete but,
This is a unified format for both header items, dynamic items, and burger menu items.
I think we should go with a structure like:
## Object structure:
```es6
{
  name: "undefined" || "string",
  //  a key used to generate default values
  pinned: "undefined" || "boolean",
  // if true, the item will always be displayed in header but never in drop down menu
  dynamicOnly: "undefined" || "boolean",
  // if true, the item will not be displayed in the burger menu
  // used to generate a dynamic menu item for sub items for example
  icon: "undefined" || "string" || "{ name: string, title: string, ...etc }",
  // if undefined, sets itself to the name string
  // if a string is specified, it will replace it with { name: `${icon}`, title: `icons.${icon}` }.
  // if name contains `-` it will be replaced by `_` for the account title
  // Feeds the resulting props to the <Icon /> component
  text: "undefined" || "string",
  // translation key, if undefined, will be replaced by `header.${name}`
  path: "undefined" || "string" || "null", 
  // path for this page, will make the item active if the current browser path starts with this string.
  // If set to null, item will never be active
  // If set to undefined, will be replaced by `/${name}`
  // If not null, by default, a click on the item will navigate to the path
  strictPath: "undefined" || "boolean", // if set to true, path will match only if current browser path is exactly path
  prefix: "undefined" || "string,"
  // if a string, the prefix will be added before the path
  account: "undefined" || "boolean",
  // if true, forces the prefix to be `/account/${currentAccount}`
  // A lot of menu items are links to account pages that start with this prefix
  navigationPath: "undefined" || "string",
  // path to navigate to on click, if undefined will be set to `${path}`.
  callback: "undefined" || "function",
  // if a function, this will be called instead of navigating to the path
  // if path is undefined and a callback is set, it's like path is set to null.
  // used for opening modals for example
  subText: "undefined" || "string",
  // if a string, will add a sub-item to the item, this is the translation key
  subPath: "undefined" || "string",
  // if set, clicking on the sub-item will navigate to this,
  separator: "undefined" || "boolean"
  // is set to true, will display a line after it in the burger menu
}
```

If an item definition is bad (missing name and text prop for example, one of them must be defined) it should just ignore the item and spit a warning in the console I think.

It could be in a .js(x?) file in a config folder so it becomes easy to configure custom header items.
Something like (might contain errors): 
## Definition example:
```es6
const headerItems = [
    {
        name: "dashboard",
        pinned: true,
        account: true,
        path: "",
        strictPath: true,
        hidden: ({currentAccount, createAccountLink}) =>
            !currentAccount || !!createAccountLink
    },
    {
        name: "exchange",
        pinned: true,
        path: "/market",
        navigationPath: ({lastMarket}) =>
            lastMarket ? `/market/${lastMarket}` : "/market/USD_BTS",
        icon: {
            name: "trade",
            title: "icons.trade.exchange"
        }
    },
    {
        name: "explorer",
        pinned: true,
        navigationPath: "/explorer/blocks",
        icon: "server"
    },
    {
        name: "login",
        callback: ({showLoginModal}) => showLoginModal,
        separator: true,
        text: ({locked}) => `header.${locked ? "unlock_short" : "lock_short"}`,
        icon: "power"
    },
    {
        name: "transfer",
        disabled: ({showAccountLinks}) => !showAccountLinks,
        text: "header.payments",
        callback: ({showSendModal}) => showSendModal,
        subText: "header.payments_legacy",
        subPath: "/transfer"
    },
    {
        name: "transfer",
        text: "header.payments",
        dynamicOnly: true
    }, 
    {
        name: "deposit",
        icon: {
            name: "deposit",
            title: "icons.deposit.deposit"
        },
        disabled: ({enableDepositWithdraw}) => !enableDepositWithdraw,
        text: "modal.deposit.submit",
        callback: ({showDepositModal}) => showDepositModal,
        subText: "header.deposit_legacy",
        subPath: "/deposit-withdraw"
    }, 
    {
        name: "withdraw",
        disabled: ({enableDepositWithdraw}) => !enableDepositWithdraw,
        text: "modal.withdraw.submit",
        callback: ({showWithdrawModal}) => showWithdrawModal,
        subText: "header.withdraw_legacy",
        subPath: "/deposit-withdraw"
    },
    {
        name: "deposit-withdraw",
        icon: {
            name: "deposit",
            title: "icons.deposit.deposit"
        },
        dynamicOnly: true
    }
    {
        name: "settings",
        separator: true,
        icon: "cogs"
    },
    {
        name: "news",
        text: "news.news"
    },
    {
        name: "help",
        separator: true,
        icon: "question-circle"
    },
    {
        name: "voting",
        account: true,
        icon: "thumbs-up"
    },
    {
        name: "assets",
        account: true,
        text: "explorer.assets.title"
    },
    {
        name: "signedmessages",
        account: true,
        icon: {
            name: "text",
            title: "icons.text.signed_messages"
        },
        text: "account.signedmessages.menuitem"
    },
    {
        name: "member-stats",
        account: true,
        icon: {
            name: "text",
            title: "icons.text.membership_stats"
        },
        text: "account.member.stats"
    },
    {
        name: "vesting",
        account: true,
        icon: "hourglass",
        text: "account.vesting.title"
    },
    {
        name: "whitelist",
        account: true,
        icon: "list",
        text: "account.whitelist.title"
    },
    {
        name: "permissions",
        account: true,
        icon: "warning",
        text: "account.permissions"
    }
];

export default headerItems;
```
See that every prop can be replaced with a function that takes props provided by the header like the `currentAccount` or any other prop that can be useful for a header item.

It would be probably nice to write a bit of doc to explain the system, explain the item definition object structure, list props passed by header, etc..

**Comment by sschiessl-bcp** [comment]
This is quite the extensive list you found there, important research!

Here my 2 cents:
- `name` -> `identifier`
- `text` -> `title`
- remove `pinned` and `dynamicOnly`, introduce `inHeader` that takes 0 (not), 1 (only dynamic), 2 (always)
- introduce `inMenu` that takes `true` and `false`
- `prefix` -> `pathPrefix`
- `account` necessary? I think can be removed
- remove `navigationPath` and `callback` and introduce `target`, which can be string or function handle
- remove `subText` and `subPath` and introduce `alternative`, which is an object that can contain all the keys that a normal item can have (with restriction)
- remove `separator` and introduce a distinct item for it, e.g. if `identifier` is equal to `separator`

Does that sound reasonable?

**Comment by sschiessl-bcp** [comment]
Any news?

**Comment by sschiessl-bcp** [comment]
> Agreed but maybe use: false, "dynamic" , true as valid values instead?

Your choice

> I'm ok with this but this will be a UI change too since the separator is a border on an item currently.

Yes, that is OK

**Comment by startailcoon** [comment]
Are we just waiting for integration on the suggested structure on this?

**Comment by sschiessl-bcp** [comment]
Yes

**Comment by sschiessl-bcp** [comment]
Any life sign @kapeer42 ?

**Comment by startailcoon** [comment]
As @kapeer42 is MIA, this issue is open for claims

**Comment by TBAPI-0KA** [comment]
I'd like to claim this one.

I've made some investigation of existing code to understand what dynamic menu items, submenu/alternate, etc are. Here are some questions/notes, and scope breakdown:
1. https://github.com/bitshares/bitshares-ui/blob/develop/app/components/Layout/Header.jsx#L1298
What is the purpose of this line? this is the only place where "submenu" variable is used (which is a pretty large piece of layout), but I wasn't able to find when this condition is true during a quick debug session. I have a feeling that it's some kind of obsolete code, but maybe I'm not just diving deep enough?
2. `strictPath` in data definition - I can't see anything similar in the existing code. Is it really required?
3. `prefix` - is it required?
4. The distinction between `path` and `navigationPath` - is it required? Makes a little bit more sense with `target`, but still, what is the purpose of `path`? To add dynamic items? As far as I see, we don't have dynamic items with behavior which is different than simple navigation.
5. `identifier` - I agree. In fact, we don't use `name` anywhere, except keys for elements.
6. However, I'd change the logic for `inHeader`, `inMenu`, and `separator`. Dividing separator by `identifier` breaks the SRP - `identifier` has a different purpose. I think this should be an enum, which specifies the element behavior. Should it be one property with a lot of values, or two ones - depends on how much data structures we define. See my proposal regarding this one the breakdown below.
7. I understand what `subText` and `subPath` does currently, and agree that `alternate` is a better name. However, I hardly understand this sentence: "which is an object that can contain all the keys that a normal item can have (with restriction)". You mean, the same data definition as regular menu items have? But current sub elements are just links, with a completely different layout. I assume your proposal mentions something more complicated, like real submenus, but I think it's too much complicated, counting that we don't have any of such elements at the moment?

Scope breakdown:
1. Move repeatable layout of regular header menu items into the separate component with parameters, replace usages everywhere.
2. Move repeatable layout of hamburger dropdown menu items into the separate component with parameters, replace usages everywhere.
3. Define data structure for header menu items, render them based on the data structure.
4. Define data structure for hamburger menu items, render them based on the data structure.
5. (requires discussion) Merge data structures into one, render both menus from the same data structure. I think this is the real purpose of the whole refactoring. On the first look, it doesn't make a lot of sense, since hamburger menu items rarely are shown on the header menu, and mostly as a dynamic item here. However, even counting that we have only one dynamic menu item at a time, we still need to define all of them in the data structure, and this structure will be almost equal to a hamburger menu one. I think it makes sense to just differentiate behavior based on the properties mentioned in #6 of the notes, and use different renderers of the same data structure. What do you think?
6. (requires discussion) See my question #1 - if I understand everything correctly, maybe it makes sense to cleanup all the related code?
7. (requires discussion) At the moment, layout and all the logic for deposit/withdraw modals is defined in Header.jsx. But it's never called from here, only from HeaderDropdown. This makes these two components tightly coupled, and I don't see any real need for this. Except if it's not possible to render modals inside DropdownMenu without breaking UI. However, if it is, this is the first thing I'd do, before doing anything else on this task.

All of the features could be separated on the separate issues, especially the last two.

Please let me know what you think, and I'll provide estimates on every point in the breakdown.

**Comment by sschiessl-bcp** [comment]
Can you please post an update to the structure 
https://github.com/bitshares/bitshares-ui/issues/1908#issuecomment-430347304 accounting for all comments inbetween including any change you would suggest

**Comment by gibbsfromncis** [comment]
@TBAPI-0KA 

> https://github.com/bitshares/bitshares-ui/blob/develop/app/components/Layout/Header.jsx#L1298
What is the purpose of this line? this is the only place where "submenu" variable is used (which is a pretty large piece of layout), but I wasn't able to find when this condition is true during a quick debug session. I have a feeling that it's some kind of obsolete code, but maybe I'm not just diving deep enough?

Try to scale your window and you will see how it works
<img width="277" alt="Screenshot 2019-07-13 16 19 52" src="https://user-images.githubusercontent.com/35899973/61172232-1c471080-a58a-11e9-933e-930c5e2a0aa1.png">

<img width="290" alt="Screenshot 2019-07-13 16 19 55" src="https://user-images.githubusercontent.com/35899973/61172233-1cdfa700-a58a-11e9-846a-c294ed6c6b66.png">

**Comment by sschiessl-bcp** [comment]
Thanks. What would be nice now (also thinking about the upcoming redesign) is the ability to define submenus (list of the same items). The `behavior` way is fine I think.

This https://github.com/bitshares/bitshares-ui/blob/develop/app/components/Layout/Header.jsx#L1298 would just be a submenu then, and all the submenu items have the parent settings header when active.

**Comment by TBAPI-0KA** [comment]
@gibbsfromncis Seems like I've missed when this one appears.
@sschiessl-bcp I saw this in the code, and this was a most confusing thing I've found because I wasn't able to find it on UI during quick research. Thanks to @gibbsfromncis, it's clear now.

So, this way, I see that we have two things which are defined as "submenus" currently:
1. Link to "obsolete" features on the same menu item;
2. Real submenu for items.

For these ones, `alternative` was discussed as a solution. However, it doesn't make a lot of sense now - i.e. there's no need to accept a function, at least for the current implementation. Why not call it `submenu`, which accepts an object (for the first case), or array of objects (for the second one)? What do you think? Also, changing submenu rendering to data-based one instead of component-based should be a separate part on the breakdown. As far as I understand, we're talking about submenu for burger menu only at this moment, and we don't render for a header menu submenu. Thus, it'll be supported on data definition level anyway.

Regarding `behavior` - actually, I had doubts even when was writing this. In fact, `behavior` is just a multiplication of `inMenu` and `inHeader` enums, and we already have too many values here. If we add another kind of menu item behavior - this will lead to further growth of `behavior` parameter. Don't you think that `inMenu` and `inHeader` is easier for understanding? We can call them `inMenuBehavior` and `inHeaderBehavior` to make them even more clear.

Would you like to see the structure with all the changes which look appropriate to me at this point?

**Comment by sschiessl-bcp** [comment]
> Why not call it submenu, which accepts an object (for the first case), or array of objects (for the second one)?

'alternative' is meant as a single drop-in replacement for deprecated menu items, whereas a `submenu` is something completly different. You could combine that behavior by checking the object type of the `submenu` like you suggest since I don't expect that we have alternative and submenu present for the same menu item

> Also, changing submenu rendering to data-based one instead of component-based should be a separate part on the breakdown

I don't understand what you mean with it?

>  As far as I understand, we're talking about submenu for burger menu only at this moment, and we don't render for a header menu submenu.

Yes, the headrow is merely a shortcut for often used panels and will not render a submenu, only present in burger menu. Regarding `behavior`, proceed what you think works best while keeping the code clear and understandable.

**Comment by TBAPI-0KA** [comment]
> 'alternative' is meant as a single drop-in replacement for deprecated menu items, whereas a submenu is something completly different. You could combine that behavior by checking the object type of the submenu like you suggest since I don't expect that we have alternative and submenu present for the same menu item

The thing that deprecated menu items are called `submenu` in existing code, and I was quite confused about what it is at all. With the latest information that I have, it's obviously better to separate these properties logically, even if we can merge them technically.

> I don't understand what you mean with it?

I've posted a scope breakdown in my first comment, for easier and clearer estimation on each point. I thought that only `alternate` concept exists, and `submenu` should just be removed. Now, submenu implementation through data definition should be added as well.

> Yes, the headrow is merely a shortcut for often used panels and will not render a submenu, only present in burger menu. Regarding behavior, proceed what you think works best while keeping the code clear and understandable.

Will do so. I'm trying to define as complete data structure as possible, but I guess some slight changes will be required during the process anyway.

**Comment by sschiessl-bcp** [comment]
Please tell me what milestone you want this to be in. This would also be our expectation for you to finish this task.

**Comment by TBAPI-0KA** [comment]
It slightly depends on the final scope we agree on. Let me shortly pull together a simplified list (based on https://github.com/bitshares/bitshares-ui/issues/1908#issuecomment-505598402, with changes according to further discussion):

1. Header menu items to component
2. Hamburger menu items to component
3. Data structure for header menu
4. Data structure for the hamburger menu
5. Merge data structures
6. Move modals code from Header.jsx if possible
7. UI for separator in hamburger
8. UI for separator in header
9. Data structure for submenus and it's rendering for hamburger
10. Data structure for submenus and it's rendering for header
As far as I understand after all discussions, we:
- Definitely need 1-5, 7, 9
- Nice to have 6
- Not sure about 8
- Don't need 10

Please tell me which ones from the latest three we need, and which don't.

Anyway, I think the best milestone for this is 190830. Most likely, I'll be able to deliver everything in 190816, but if you prefer a strict deadline - 190830 is better.

**Comment by TBAPI-0KA** [comment]
@sschiessl-bcp Maybe it will be faster to connect on Telegram to resolve remaining questions, so I can start to work on this one?

**Comment by sschiessl-bcp** [comment]
I'm sschiessl in Telegram.

**Comment by sschiessl-bcp** [comment]
8 is not needed 

9 submenu items should have same structure as parent, and they can choose to display in header with the parent icon or their own,  or none

**Comment by TBAPI-0KA** [comment]
Regarding 9.

By "data structure" I mean not a definition - it's already defined here, in the ticket. I mean, moving of existing menu items on this structure, and rendering for them. Like "1 + 3" or "2 + 4", but for submenu.

However, by "they can choose to display in header with the parent icon or their own, or none" you mean more like 10, as I feel. Is it correct? And what exactly about icons? I thought just replicate current behavior we have for a hamburger, but with dropping "down" instead of "right".

**Comment by sschiessl-bcp** [comment]
For example: Settings has several submenues, but all are rendered with the header entry of the main Settings entry.

In contrast would be spotlight. All childs would have their own header item and not the parent ones (currently spotlight has no submenu, but I plan on adding one)

**Comment by TBAPI-0KA** [comment]
I feel like we're talking about quite different things. Let me better illustrate with screenshots. That's what we have for submenu in hamburger:
![2019-08-21 10_15_50-Window](https://user-images.githubusercontent.com/1467276/63442153-48806780-c43b-11e9-97b4-fc2ec257e7c6.png)
![2019-08-21 10_15_55-Window](https://user-images.githubusercontent.com/1467276/63442154-4918fe00-c43b-11e9-812b-bf28f74c1a9c.png)
Point 9 is intended to use the same way of rendering, but using nested data structure. We discussed this quite well - the only change for rendering might be an icon on every submenu item, that should be easy.

By "header" I mean this menu:
![2019-08-21 17_48_03-Window](https://user-images.githubusercontent.com/1467276/63442571-04da2d80-c43c-11e9-8d2b-d689bba2a5d6.png)
And by point 10 something like this:
![2019-08-21 10_16_40-Window](https://user-images.githubusercontent.com/1467276/63442634-1cb1b180-c43c-11e9-9bd6-aa45d196fdc3.png)
So my question is - do we need it at all?

I assume by spotlight you mean this one:
![2019-08-21 10_14_00-Window](https://user-images.githubusercontent.com/1467276/63442754-4f5baa00-c43c-11e9-8cd0-7a7cb1c7ad03.png)
And by "header" you mean "parent item", right? So, this should look very similar to the Settings menu (first two screenshots here), but with icons on every child item?

**Comment by sschiessl-bcp** [comment]
I see, 10 is not needed yes. A submenu for spotlight is also not needed at the moment, that was just for illustration.

**Comment by TBAPI-0KA** [comment]
Done, PR #3054 sent.

Notes:

* Some of the icons are missing translation titles - i.e. direct_debit, prediction-large, etc. I haven't checked all of them because it's clearly out of scope for this particular task, but I assume there's a lot more.
* Logo in the header, technically, is a menu item as well. However, at the moment it has a different look, layout, and principle (uses branding). So, it kept "as is", but perhaps it's possible to convert it to the regular menu item as well.
* "Accounts" menu almost didn't touch - it's dynamic, and uses different layout. To be honest, it's something very similar to "header submenu" that I mentioned earlier.
* Legacy Deposit/Withdraw (/deposit-withdraw) doesn't have an icon at the moment - there's definitely existed one, but such icon filename doesn't exist anymore. Perhaps it worth to use "Send" icon?
* Modals code kept in Header.jsx. It's possible to move it out of here to achieve better architecture (why header menu should deal with modals at all?), but I don't see much benefits from it, while effort is larger than I thought. If you like this to be done, please create a separate issue.
* Submenus refactoring also added some more abilities while preserving logic - now it's possible to add as many submenus as you like, just by setting "submenu" property on data definition object. Such menu will properly render, set event handlers, UI, etc.

The final structure is also a little bit different. I've added a description for all fields, even obvious ones, so it can be used as a reference/documentation.

```javascript
{
  hidden: "undefined" || "boolean",
  // Hides or shows the element

  disabled: "undefined" || "boolean",
  // Applies "disabled" styling to element, disables click handlers

  inHeaderBehavior: "undefined" || "MenuItemType",
  inDropdownBehavior: "undefined" || "MenuItemType",
  // Defines behavior for menu item in burger menu, and in header. MenuItemType enum has the following values:
  // Never - element never shows in this particular menu. Default value
  // Always - element always shown
  // Dynamic - dynamic behavior. If "target" is string, and point out to the current URL - element is shown in the menu
  // Divider - separator for this type of menu

  icon: "undefined" || "string" || "{ name: string, title: string, size: string }",
  // If string - uses it as name, and prepends "icons." for title
  // Size by default set to 2x for dropdown menu items, and 1.5x for header ones, but could be overriden

  text: "undefined" || "string",
  // Translation key for menu item

  target: "undefined" || "string" || "function", 
  // If string, acts as an URL for navigation on click
  // If function, acts as a callback on click. In this case, matching for dynamic elements isn't possible
  // Automatically sets for full-sized submenus

  includePattern: "undefined" || "string" || "string[]",
  // Current URL should contain appropriate string(s) to assign "active" class for current menu item
  // Also, used to assing hideClassName for header menu items

  excludePattern: "undefined" || "string" || "string[]",
  // Works in pair with includePattern, but current URL should not contain string(s) from this property

  hideClassName: "undefined" || "string",
  // Used only for few menu items in header - name of the class which should be assigned to hide this element on small screens

  additionalClassName: "undefined" || "string",
  // Used only for dropdown menu items, adds an additional CSS class to them 

  submenu: "undefined" || "{target, text, disabled}" || "[{target, text, hidden}]" ,
  // If object - shows additional link with it's target property
  // If array - renders as full-sized submenu
  // This property works only for dropdown menu items at the moment
  // Sub-properties acts exactly the same as for parent element in this structure
}
```

**Comment by sschiessl-bcp** [comment]
I'd like to invite anyone to come look at the menu structure @ develop.bitshares.org

Todo:
 - make sure header items disappear when small screen, and appear in burger
 - streamline and reduce code duplication more

**Comment by TBAPI-0KA** [comment]
Some comments:

> make sure header items disappear when small screen, and appear in burger

Is it a request for testing by community, or you have found some bug? I implemented visibility exactly in the same way as it was, for every menu item, even if I don't understand completely why it is as it is.

> streamline and reduce code duplication more

I believe it's only possible with significant logic change. I tried to avoid any possible duplication inside the data structure. Elements that are present in both menus are only defined once, and every field which could be optional - is optional. Rendering code doesn't have duplication as well - it uses loops over the data structure, no elements are rendered twice. Do you have any specific suggestions that could be simplified further?

Also, Gibbs asked me to post the hourly report here ASAP. So, 4 hours 52 minutes are spent on related tasks - communication, code investigation, data structure definition in the text, etc. And 15 hours 46 minutes on pure coding.

**Comment by sschiessl-bcp** [comment]
The current solution at develop coming from your work is acceptable. Please state your bounty request, otherwise we'll make a suggestion.

**Comment by sschiessl-bcp** [comment]
> The current solution at develop coming from your work is acceptable. Please state your bounty request, otherwise we'll make a suggestion.

Closing because considered done. Bounty discussion not affected by that.

**Comment by TBAPI-0KA** [comment]
@sschiessl-bcp 
Guys, I always trust your suggestions. On the other hand, you see the code committed, and I hope clearly understand that work on it indeed takes the time I posted. I can send a very detailed minute-exact report if required. On this ticket, 20h 6m was spent in total, and, in this particular case, a very small amount from it on pure communication - definition and description of the data structure in some sense were even more complicated than coding.

I know we (meaning "Bitshares" as "we") have some funding issues. So, I think 15 hours is a good compromise for both sides.

**Comment by sschiessl-bcp** [comment]
> @sschiessl-bcp
> Guys, I always trust your suggestions. On the other hand, you see the code committed, and I hope clearly understand that work on it indeed takes the time I posted. I can send a very detailed minute-exact report if required. On this ticket, 20h 6m was spent in total, and, in this particular case, a very small amount from it on pure communication - definition and description of the data structure in some sense were even more complicated than coding.
> 
> I know we (meaning "Bitshares" as "we") have some funding issues. So, I think 15 hours is a good compromise for both sides.

The Bounty does not necessarily reflect the actual hours spent, e.g. one of my last contribution was a bounty of 14.5 for 30:53 hours spent. I do not doubt that your reported time is accurate.

Let's get @startailcoon or @clockworkgr s opinion as well.

**Comment by sschiessl-bcp** [comment]
It seems I have the only opinion.

**Comment by TBAPI-0KA** [comment]
@sschiessl-bcp Stefan, I just don't know how the bounty is calculated in comparison with the hours spent. Everything I can do on my side - do good work, and send how much time was spent. In all the rest - I trust you, like, totally :) I know you make weighed decisions, and I never had a feeling that bounty is unfair. In this case, I think 12.5 hours is a good balance with the actual time spent and current funding possibilities. Thanks!
