### ISSUE TITLE
[Exchange Refinement] Visualizations

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1979]
The Open Orders / Settle Orders Panel should stay below the Trades Panel when vertical Order Book is selected. Currently it moves below "Buy BTS" in the screen
![image](https://user-images.githubusercontent.com/33128181/46719653-c5b14c80-cc6e-11e8-82aa-275e902d35a7.png)

**Comment by startailcoon** [comment]
This is due to the fact that the panel is so wide that the next spot is on the next row.

I have two solutions for this.

# 1

Wider panels, making them align better

![bild](https://user-images.githubusercontent.com/12114550/46755487-79452b80-ccc5-11e8-9392-1ad9874c7f4d.png)


# 2

Stack them differently

![bild](https://user-images.githubusercontent.com/12114550/46755543-a1cd2580-ccc5-11e8-8a57-152ebdb7f144.png)

**Comment by startailcoon** [comment]
Fixed part of PR #2008 

If order book is vertical, an empty placeholder will make the Open Orders / Settle Orders Panel still remain at the same place below My Trades / Market Trades.

**Comment by sschiessl-bcp** [comment]
> If order book is vertical, an empty placeholder will make the Open Orders / Settle Orders Panel still remain at the same place below My Trades / Market Trades.

Nope xD
![image](https://user-images.githubusercontent.com/33128181/46943806-c2ec9800-d070-11e8-975e-3d50f1031cc9.png)
