### ISSUE TITLE
[0.5][frooze] Include Ratio to be lockable in Margin Modal

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2005]
When the DEBT field has an open lock and the COLLATERAL field is locked. 

Changing the DEBT, the COLLATERAL is changed despite the lock and not the RATIO.

Version: BitShares2-light_2.0.181010_amd64.deb

**Comment by froooze** [comment]
Which Verification is needed? Is Bug not reproducible?

**Comment by startailcoon** [comment]
`Needs Verification` is that it needs a verification by another user or by a liceCap screen.
My testing doesn't let me redproduce the bug you supply.

**Comment by froooze** [comment]
![lock-ignore](https://i.postimg.cc/dtqFMmn4/lock-ignore.gif)

Have added the version in first post.

**Comment by froooze** [comment]
Can we remove now "Needs Verification" ?

**Comment by startailcoon** [comment]
The lock is used for the ratio slider. This is not clear enough though. I see your confusion on this.
I've added this issue to the parent task of https://github.com/bitshares/bitshares-ui/issues/2127

**Comment by froooze** [comment]
We have three variables:
- Debt
- Collateral
- Ratio
at least one of them needs a locked lock. 

Would be good to have the lock option on all three variables.

**Comment by startailcoon** [comment]
> 
> 
> We have three variables:
> 
>     * Debt
> 
>     * Collateral
> 
>     * Ratio
> 
> 
> at least one of them needs a locked lock at the time. The other two can have a open lock.
> 
> Would be good to have the lock option on all three variables. Closing one look could unlock the other two.

I've started to work on this on, and what I've come to work best is the following

- Either Debt or Collateral is locked by default. 
- Locking one unlocks the other
- Ratio can be locked, which overrides any locked Debt or Collateral fields. When either of these changes, ratio sticks and forces the other input to change accordingly. Ratio can still be moved manually, but will not change based on the ratio of the input fields.

Thoughts?

**Comment by sschiessl-bcp** [comment]
What is the current logic?

**Comment by froooze** [comment]
@sschiessl-bcp: the actual logic drove me nuts 

@startailcoon: Your logic looks good, and I want to add this:
* Collateral and Ratio needs to be default locked
* Default CR = 2*MCR
* Default Target Ratio = MCR
* Locking Debt should unlock Collateral and vice versa

**Comment by startailcoon** [comment]
> What is the current logic?

The current logic is that when you change an input it will change the ratio, as either debt or collateral is locked. The problem is that you may want a specific ratio, like 2, and that is not possible today as any input will change the ratio.

So to set a dept of 10 and collateral of 100 with a ratio of 2 you may need to adjust one or more fields several times to get to the solution you desire.

> Collateral and Ratio needs to be default locked

Why? As I see it debt should be locked, and perhaps ratio. Say you want to borrow 100 bitUSD, if collateral is locked it will not change when you change the debt you want.

> Default CR = 2 * MCR
> Default Target Ratio on = MCR

Do we have a consensus for this value from anywhere?

> Locking Debt should unlock Collateral and vice versa
Yes, that's the logic already and isn't changing.

> Ratio slider min value = MCR (not 0 as now)

That I can agree on as nothing below MCR is possible anyway. Same for TCR.

> Ratio slider max value = 6 * MCR

Nothing against that either.

> Remove slider for target collateral ratio, because it is useless

Quite true, as the slider on the Ratio is to see the change in debt/collateral directly and TCR doesn't have any visual changes.

> Change the order to, because most people start with a certain amount of BTS.

Not sure about this. Who are "most people" and what do you base it on? I usually start out with debt, as I wish to borrow a certain amount.

**Comment by froooze** [comment]
@startailcoon:
- Using the default lock between Debt or Collateral is a personal preference. I second opinion is needed here, if a borrower starts with BTS or with Debt. 

- The lock is needed at the beginning to prevent ratio changes during editing collateral or debt
- We have some consensus for default value of MCR = 3 (because BTS lost about 67% in a row on the hardest crashes)
- We have also a consensus on TCR = MCR, when looking at the bitUSD/bitCNY markets

**Comment by froooze** [comment]
I did a poll on the Telegram Bitshares channel:
![Coll-debt](https://user-images.githubusercontent.com/40874087/59190104-22596400-8b7c-11e9-8f97-7c0038643a9d.png)

Most users start with the collateral. Therefore collateral should be first and default locked.

**Comment by sschiessl-bcp** [comment]
Thanks for your contribution @froooze. I suggest 0.5 bounty for those efforts @startailcoon

**Comment by froooze** [comment]
#2004 to not loose overview

**Comment by startailcoon** [comment]
@froooze  thanks for the details collected. Agreed with a 0.5 bounty for you on this.

**Comment by startailcoon** [comment]
Bounty for Frooze on this issue, total UI work on parent issue #2004
