### ISSUE TITLE
[2] Dropdown Improvements

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#2149]
Issue extracted from #2020 

By @wmbutler 
> The color of the selected item in the dropdown is a little ambiguous. I'd typically expect highest contrast to be the selected item but this is clearly not possible on the Midnight view. See this screenshot to illustrate my point. Maybe we use the blue universally? This is a tough one.

![bild](https://user-images.githubusercontent.com/1254810/47528829-ce5b7280-d86b-11e8-8b9f-be91c41c5887.png)

**Comment by startailcoon** [comment]
Here is a licecap that visualizes it a bit more

![bitshares-dropdown](https://user-images.githubusercontent.com/12114550/48317779-87090c00-e5f7-11e8-8793-d1d28b369ee8.gif)

**Comment by gibbsfromncis** [comment]
@startailcoon to be honest I'm not following the idea... can you clarify please?

**Comment by sschiessl-bcp** [comment]
Please check that you can also select with keyboard (up and down moves the selection, enter confirms it)

**Comment by startailcoon** [comment]
@wmbutler, could you clarify your thoughts on this matter?

**Comment by wmbutler** [comment]
I'll claim this.

**Comment by wmbutler** [comment]
Here is my proposed change. I think what was most confusing was the hover color. Typically, I'd expect a higher contrast for the selected item. The midnight view makes higher contract virtually impossible with a background color, so I updated the style guide to reflect only a blue color for active/hover states on the menu items. I think it looks pretty good.

It took me two hours to hunt through all the variations.

![select](https://user-images.githubusercontent.com/1254810/49333824-2a13cc80-f58b-11e8-937b-aadba3438e89.gif)

**Comment by wmbutler** [comment]
https://github.com/bitshares/bitshares-ui-style-guide/pull/4

**Comment by gibbsfromncis** [comment]
@wmbutler Unfortunately your changes will work but only till next update from my side, because you changed source file instead of config file which uses to build themes.

There is instruction how to update styles on the right way - https://github.com/bitshares/bitshares-ui-style-guide/blob/master/INSTRUCTIONS.md#how-to-manage-styles-of-style-guide-components-

I'll open new issue to fix it

**Comment by wmbutler** [comment]
Oops. Sorry. I'll review.

**Comment by wmbutler** [comment]
Your instructions are a bit ambiguous. Every directory is /dark/ ?

![screen shot 2018-12-03 at 11 08 43 am](https://user-images.githubusercontent.com/1254810/49389420-e08ec300-f6eb-11e8-92f6-085fa143b347.png)

**Comment by gibbsfromncis** [comment]
@wmbutler my bad.. Updated.

https://github.com/bitshares/bitshares-ui-style-guide/blob/master/INSTRUCTIONS.md

**Comment by gibbsfromncis** [comment]
@wmbutler There are few ways to get your task done. 

1) Update specific ant's variable which is responsible for that.
2) If ant has no variable to handle your situation you should do the next:
- Provide your own variable for Select (ant calls it Select)
- Add override of Select for specific state you need

@wmbutler Lets make it more faster - give me color you need, I'll update it and we will keep your hours and I'll put my hours and we finally will close this task.

**Comment by gibbsfromncis** [comment]
@wmbutler this is how it should be updated:

1) Add specific variables for each 3 themes:
https://github.com/bitshares/bitshares-ui-style-guide/commit/a244b099f1624b9e55f2f56c2da22e79c6847048#diff-0416afb78c680a498fad03bd9c360a87
https://github.com/bitshares/bitshares-ui-style-guide/commit/a244b099f1624b9e55f2f56c2da22e79c6847048#diff-d0cdf296af98dee69ff46bdf7d34256c
https://github.com/bitshares/bitshares-ui-style-guide/commit/a244b099f1624b9e55f2f56c2da22e79c6847048#diff-c2e6b709522384151775775a33686b4b

2) Add overrides for select (because select doesn't have its own variables for this kind of styling)

https://github.com/bitshares/bitshares-ui-style-guide/commit/a244b099f1624b9e55f2f56c2da22e79c6847048#diff-bd9e7d6072b9e6de78f2e08cd951e508
