### ISSUE TITLE
[.5][Investigation] Edge Browser stuck on Loading

### ISSUE THREAD

**Issue by toi16** [bitshares/bitshares-ui#2175]
**Describe the bug**
When navigating to https://staging.bitshares.org/ a white loading screen appears and that is all that is rendered.
**To Reproduce**
1. Go to https://staging.bitshares.org/
2. See error 'Loading ....'

**Expected behavior**
When navigating to https://staging.bitshares.org/ the Bitshares Wallet should be displayed.

**Screenshots**

![edge loading error](https://user-images.githubusercontent.com/23018324/48619607-f0d93b00-e994-11e8-9f3c-134b850e8164.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge 
 - Version 42.17134.1.0

**Additional context**
See console log in screenshot, script error.

**Comment by bieglich** [comment]
Same here

Edge Version 42.17134.1.0
Microsoft EdgeHTML 17.17134

**Comment by sschiessl-bcp** [comment]
I think a little research is in order, might just be a small issue. OpenLedger works on Edge afaik

**Comment by startailcoon** [comment]
>           I think a little research is in order, might just be a small issue. OpenLedger works on Edge afaik

Ineed it does. Let's see if someone can figure this one out then 👍

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp would you like to take care of it or let me do it?

**Comment by sschiessl-bcp** [comment]
So far lots of research, but no viable fix yet

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp I can create separate task for investigation to track my hours and get bounty for it. In result of investigation I'll post results and ideas of possible fixes. I want to create separate task because this Edge fix may take a lot of time without any results. I'm not ready to do it without bounty..

**Comment by wmbutler** [comment]
Add incompatible browser message and close this since M$ will eventually not support Edge.

![screen shot 2018-12-15 at 1 44 37 pm](https://user-images.githubusercontent.com/1254810/50046808-9a344f00-006f-11e9-9e52-61d1914a5fd1.png)

**Comment by sschiessl-bcp** [comment]
This issue is used to payout for investigation into the issue, hours spent is 4.

References for the interested dev
https://stackoverflow.com/questions/44455083/error-script-1028-expected-identifier-string-or-number-with-ie11
http://mikemclin.net/fixing-error-script1028-expected-identifier-string-or-number/
https://github.com/jsforum/jsforum/issues/5
https://github.com/rollup/rollup/issues/969

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp should I update hours to 4?

**Comment by sschiessl-bcp** [comment]
Jap, and change the label from estimated to finalized once you have reviewed
