### ISSUE TITLE
[1.5] BlockTrades bridge is broken because wallet tries to use URL to winex

### ISSUE THREAD

**Issue by dnotestein** [bitshares/bitshares-ui#2285]
**Describe the bug**
When you go to legacy deposit-withdraw page to access the blocktrades bridge, it uses an invalid url to winex.pro instead. Then it reports that blocktrades.us is not responding.

**To Reproduce**
See above

**Expected behavior**
If it used the correct URL, it would show the blocktrades bridge instead of the error.

**Screenshots**
I can't, because I tried switching to "Winex" to see what that would do, and now it locks up completely like this:
![image](https://user-images.githubusercontent.com/5102968/49667162-3a62f600-fa28-11e8-8fe4-d3fd3c1f0f18.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 70

**Additional context**
None

**Comment by startailcoon** [comment]
Can verify that something weird is going on here. We should try to fix this, even though we will soon remove the legacy functions, we should make sure they work as expected until then.

**Comment by dnotestein** [comment]
If the legacy deposit is removed, I don't see another way to access the blocktrades bridge. Is there some way I'm missing?

**Comment by startailcoon** [comment]
The problem with BlockTrades not loading had nothing to do with WinEX. The error output is missleading due to the way the components have been coppied by the one developing the connection to WinEX. 

BlockTrades issue was due to an error with populating coin pairs, most likley due to an updated asset on the API side. This has been fixed.
