### ISSUE TITLE
[1] Datetime picker Expiration - Missing tooltip

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2356]
**Describe the bug**
1. The Datetime picker expiration is missing the tooltip once the default (1year) is clicked.
![181212rc-1_datetime_picker_1_capture](https://user-images.githubusercontent.com/18186497/50130857-509d5d00-0245-11e9-8a11-28eb7406bc57.JPG)

2. It is not clear for the user that they can specify the expiry date and time outside of the specific pull 
   down. 
3. Clicking on specific lastly contains specific twice.![181212rc-1_datetime_picker_1_specific_capture](https://user-images.githubusercontent.com/18186497/50130847-44b19b00-0245-11e9-89ee-89712677b975.JPG)
4. Clicking the second specific closes the pull down list.

  

**To Reproduce**
1. Go to Exchange tab
2. Click on the BTS tab for BitCNY:BTS pair
3. Scroll down past the chart to buy/sell
4. Click on default expiration of 1 year
![181212rc-1_datetime_picker_1_1yr_capture](https://user-images.githubusercontent.com/18186497/50131521-1f725c00-0248-11e9-8461-760b0bb1dbfe.JPG)

5. See error of missing timedate picker tooltip; see specific timedate picker tooltip
![181212rc-1_datetime_picker_1_capture](https://user-images.githubusercontent.com/18186497/50131531-2c8f4b00-0248-11e9-9f31-44f63465faf8.JPG)

6. Click on specific tooltip noting a second specific in the pull down list
7. Click on the second specific in the pull down list noting it closes the pull down list
8. Click the default timedate shown noting a calendar popup
![181212rc-1_datetime_picker_1_2_capture](https://user-images.githubusercontent.com/18186497/50131648-ca831580-0248-11e9-96b7-85c6e5c46e55.JPG)
![181212rc-1_datetime_picker_dec_capture](https://user-images.githubusercontent.com/18186497/50131707-0b7b2a00-0249-11e9-9206-4aab7c8180f7.JPG)

**Expected behavior**
1. Timedate picker tooltip if default (1year) is clicked
    for a better user experience and self help
2. Clicking specific or the current datetime picker (after clicking default 1 year) opens up the calendar (as in previous releases I think)
3. Consider removing the second _specific_ from the pull down list if possible to eliminate confusion. Or, replace the second word "specific" with "advanced"(same # letters) that opens up the calendar. The other options of 1 hour to 1 year are quick and easy.

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser Opera 
 - Version 56.0.3051.116
 - Release 181212rc-1

**Additional context**
Please see #2355

**Comment by startailcoon** [comment]
@calvinfroedge please notify if you still intend to submit a PR for this task. Otherwise, free for claims.

**Comment by MikhailKavalenka** [comment]
@startailcoon , I can take this one.

**Comment by startailcoon** [comment]
Great, it's yours Mikhail

**Comment by OpenLedgerApp** [comment]
It took more time(6 hours) then planned, because:
-it was necessary to change logic for both forms(limit/scaled).
-Had some difficulties with implementation a datePicker into option of Select and re-change of "Specific" option.

**Comment by sschiessl-bcp** [comment]
What exactly were the changes (in words) that were done?
Any reason it was not switched to styleguide DatePicker?

**Comment by OpenLedgerApp** [comment]
what was done:
1. Added tooltips for options from 1 hour to 1 year
https://user-images.githubusercontent.com/42674402/56679132-07ff2000-66cd-11e9-8df7-6984823c786e.png
2. new logic for specific option:
- To open up the Calendar you should click on "Specific" option
(we hide DatePicker and then through datePicker ref we open it)
https://user-images.githubusercontent.com/42674402/56679173-1a795980-66cd-11e9-90d7-71ee835ce55e.png
- After choosing a date dropdown will look like. And you can always click on the date in dropdown to change it in the Calendar.
(had dificulties with reopening of calendar when specific option was selected, because onChange didn't work in this case, therefore we use onClick and onBlur events to open calendar)
https://user-images.githubusercontent.com/42674402/56679192-26651b80-66cd-11e9-8c3f-386ac8bc30cd.png

No, we didn't use a new datePicker from "antd", but we can do it

**Comment by startailcoon** [comment]
Please solve this with using Style Guide components available.

**Comment by OpenLedgerApp** [comment]
@startailcoon done
