### ISSUE TITLE
Exchange ETH tab - Obits, BTSR, other OL assets 

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2366]
**Describe the bug**
Suddenly when clicking on an Openledger asset in the ETH market of the Exchange there is no chart, no price feed, no suggested buy/sell feed, no history or market trades.
For me on first time, it broke the site
Please see comments below

**To Reproduce**
1. Go Exchange ETH tab
2. Click on OBITS (for a pair of ETH:OBITS)
3. See errors
![181212rc-1_obits-eth_1_capture](https://user-images.githubusercontent.com/18186497/50247099-9de01280-039c-11e9-9afd-05d90575159c.JPG)
![181212rc-1_obits-eth_2_capture](https://user-images.githubusercontent.com/18186497/50247137-afc1b580-039c-11e9-859b-f097fe22f716.JPG)

**Expected behavior**
If OL is restricting access to their site, access to funds should not be disabled via core.
A feed is required for an informed trade. 

**Screenshots**
![181212rc-1_obits-eth_3_capture](https://user-images.githubusercontent.com/18186497/50247585-dd5b2e80-039d-11e9-990f-1b98cd937991.JPG)
![181212rc-1_obits-eth_4_capture](https://user-images.githubusercontent.com/18186497/50247592-e8ae5a00-039d-11e9-8b7e-38e648eee921.JPG)

**Desktop (please complete the following information):**
 - OS:Windows 8.1
 - Browser Opera
 - Version 56.0.3051.116
 - Release 181212rc-1

**Additional context**
The ETH market list seems extremely long, maybe duplicated
Checked and BTC market looks the same (extremely long, maybe duplicated).
No tradingview chart on some assets (but feeds). Some others broke the site.

**Comment by startailcoon** [comment]
The reason the list is long is because it has all the Quote pairs. This means that the ETH tab has all *.ETH pairs like:
- bitETH/OBITS
- OPEN.ETH/OBITS
- GDEX.ETH/OBITS
- BRIDGE.ETH/OBITS
- ... etc

I believe that the WOD issue you have is when a market doesn't have a trading history and is fixed by PR https://github.com/bitshares/bitshares-ui/pull/2339

I've tried all the *ETH/OBITS markets available using the latest develop branch, and none of them broke the UI for me. There will be a release today which has these fixes.
