### ISSUE TITLE
[3][dot5enko] New Gateway API Drafting

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#2477]
Parent Task: Gateway/Bridge Codebase Enhancements - #2010 

The current Gateway communication is built on a system that was used by OL in the start of the bitshares UI platform. While this most likley served its purpose in the start, it's becomming increasingly difficulty to both diagnose, opperate and add new gateways that are added to the application.

The purpose of this issue is to allocate a few hours for analyzing the current system to draft a new API based on requirements needed by Gateways today. 

Proposed API should work side-by-side of current structure. 
This task is **not** about implementation.

Tasks
- [ ] Review current structure and demands
- [ ] Draft a propsal for API structure for later implementation

**Comment by dot5enko** [comment]
Api structure
---

Don't think we need to add something to a list of possible interacting with gateway requests as everything is covered by available ones - from coin names to fees and min amounts. As the main purpose of gateways is getting coins in and out of bts system i think described scheme is fully capable of this. 

Code
---
The other situation is with [code](https://github.com/bitshares/bitshares-ui/tree/develop/app/components/DepositWithdraw) itself - its a bit messy and copypasted (at least render methods of `{name}Gateway.jsx` such as `onSelectCoin`,`changeAction`). I think we could introduce Gateway component and simply extend it with properties or substitute default behaviour as mentioned in [other cases](https://github.com/bitshares/bitshares-ui/wiki/Gateway-Integration-Requirements#other-cases)  and `register` in some `GatewayManager` in order to add new gateway. Now each gateway has its own folder with bunch of code which is weird if they follow api rules described in documentation (probably its because of legacy deposit/withdraw left on the wallet), 

Documentation
---
[Given](https://github.com/bitshares/bitshares-ui/wiki/Gateway-Integration-Requirements) doc on gateways seems descriptive to me, probably we could improve `notes` with json exmples by making full description on endpoints we require and schemes for requests params and results they respond including info on types of field values and textual description if needed

**Comment by startailcoon** [comment]
## API Structure
Lets then keep the current system we have, though in the long run try to refine the code around it so it will be easier to understand for developers. Good documentation is key and the wiki article can be improved with more notes and examples.

## Code
There are currently two different code bases, one which will be removed.
1. Legacy Gateway, where each gateway had a single page (i.e. [here](https://github.com/bitshares/bitshares-ui/tree/develop/app/components/DepositWithdraw)). This system is built on a folder system where each gateway has sepperate, and highly redundant code. When we introduced the new gateway system the goal was to remove this. **The goal here would be to strip it out from the app**.
2. The new Gateway system, where assets dictate and gateways are selected by the selected asset. This needs some added features and code refactoring. **The goal here would be to streamline the code**.

This task will be considered closed and future refactoring work will be in parent task https://github.com/bitshares/bitshares-ui/issues/2010.

**Comment by dot5enko** [comment]
@startailcoon ok, i'm ready to start with Legacy Gateway code removal as you mentioned above alongside with refactoring of rest code. We need either create new issue for this particular aim as a child of #2010 or i'll do this job directly in that task. So in any case you can assign that task to me

**Comment by sschiessl-bcp** [comment]
Can we work out specifications (for API) beforehand, and discuss if they make sense like they are?

Cutting out the legacy should be the last step in the refactoring, with grace period and notification to all involved gateways.
