### ISSUE TITLE
Visual Issue: Fee in trading currency displayed wrong

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#249]
When trading currencies and using the currency to trade as the fee currency, paid by the fee pool, the value is misleading. The fee is correct, but displayed wrong to the user.

The value is the same whether you use BTS or the trading currency, resulting in some confusion.

On the confirmation screen the value is correctly displayed in BTS again.

### Fee displayed correctly in BTS
![bitshares_feeinbts](https://user-images.githubusercontent.com/12114550/29313084-518b4218-81b8-11e7-9d7b-490d93d3fbd7.PNG)

### Fee incorrectly displayed in GRC. Expected to see the value in GRC
![bitshares_feeingrc](https://user-images.githubusercontent.com/12114550/29313083-518a0f92-81b8-11e7-884a-e474620d19a9.PNG)

### Fee correctly displayed in BTS, but GRC was selected and could be confusing for some
![bitshares_fee_confirm](https://user-images.githubusercontent.com/12114550/29313085-518fcdd8-81b8-11e7-92ed-1560666c1e65.PNG)

**Comment by wmbutler** [comment]
This dropdown is not present in the light wallet. Please specify the URL for this site.

**Comment by startailcoon** [comment]
It's from the light wallet, version 170522 for Windows from https://bitshares.org/download/

![bitshares_lightwallet_windows](https://user-images.githubusercontent.com/12114550/29316454-6fb773a0-81c8-11e7-92df-39dde76e9bb3.PNG)

**Comment by wmbutler** [comment]
Interesting, because the dropdown is not present on the MacOS version. Might need @svk31 to duplicate this or explain the difference on it.

![screen shot 2017-08-15 at 7 50 10 am](https://user-images.githubusercontent.com/1254810/29316657-72987d7e-818e-11e7-9ad8-75c6b957f7e3.png)
![screen shot 2017-08-15 at 7 50 04 am](https://user-images.githubusercontent.com/1254810/29316656-728fdcbe-818e-11e7-9948-7d91724829d8.png)

**Comment by startailcoon** [comment]
That is really strange. You're using the `BTS:openGRC` trading pair?

**Comment by wmbutler** [comment]
Yes

![screen shot 2017-08-15 at 7 55 52 am](https://user-images.githubusercontent.com/1254810/29316883-3495f3ca-818f-11e7-83a9-ab37e4ad6137.png)

**Comment by svk31** [comment]
It's only present if you actually have the asset. There are actually multiple issues here, first of all the fee is the same because the Core Exchange Rate of OPEN.GRC is 1 OPEN.GRC/BTS, so that's correct. Since that rate is terrible you really shouldn't pay your fees in GRC anyway but that's a different issue.

Secondly, the OPEN.GRC fee pool is empty, so even though you attempt to pay your fees using it, the transaction will default to BTS to pay the fee.

What I can do is add a fee pool balance check that will remove the option of selecting that asset if the fee pool is empty.

**Comment by wmbutler** [comment]
Cool, and this would also display insufficient funds per #231 if there were no BTS.

**Comment by svk31** [comment]
Should be fixed in https://github.com/bitshares/bitshares-ui/commit/f1141a587a8977ff1c34dd914c97bc377a39c565
