### ISSUE TITLE
[Exchange] No complete order book for BitEUR/BTS market

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2562]
**Describe the bug**
Showing the complete order book does not work on the BTS/BitEUR Market

**To Reproduce**
Go to the BTS/BitEUR and click on "show all bids"

**Expected behavior**
To list all open orders

**Screenshots**
![Biteuro](https://user-images.githubusercontent.com/40874087/55347047-28640200-54b4-11e9-986b-125d000f3856.png)

**Desktop (please complete the following information):**
- MX-Linux
- BitShares2-light_2.0.190410-rc1_amd64.deb

**Comment by startailcoon** [comment]
Clicking `Show All Bids` reveals a longer list of open orders to me when testing. The list viewed is limited by a maximum node limit as far as I know, if you expected it to view more than what is viewed.

**Comment by froooze** [comment]
I get for the BitCNY/BTS market a lot more entries on the same node. Other markets look fine only bitEUR/BTS looks very limited.

**Comment by sschiessl-bcp** [comment]
bitEUR is quite a thin market ....

**Comment by froooze** [comment]
@sschiessl-bcp:
Yes bitEUR is a thin market, but why do I get only half of the possible entries, compared to other markets?
What is your last order you see in the market?

**Comment by startailcoon** [comment]
Smallest order in the UI client is 0.034602, which is probably because there are a lot of tiny orders on that price.

When the client requests the list of orders it's limited to a maximum amount of orders in the response. With this many small orders it's not going to view the smaller ones.

![image](https://user-images.githubusercontent.com/12114550/55567166-67d15f00-56fd-11e9-9474-c5b3a2de8393.png)

**Comment by startailcoon** [comment]
Closed as no new input was submitted for this issue

**Comment by abitmore** [comment]
I guess @froooze enabled "Order Book Grouping". Amount of the last order in the screenshot was much bigger than 0.0002 EUR.
