### ISSUE TITLE
[Exchange] Add asset info to BUY/SELL ORDERS

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2566]
**Is your feature request related to a problem? Please describe.**
When a users has the order book on top of the layout, there is the asset info missing.

**Describe the solution you'd like**
Add asset info to SELL and BUY ORDERS

**Additional context**
![Oders-Asset-Info](https://user-images.githubusercontent.com/40874087/55361503-a685d000-54d7-11e9-9eda-6879bb57167b.png)

**Comment by startailcoon** [comment]
Not sure I see the reason for this. What I assume you refer to is the fact that the order form has the asset name in the title, while the orders list doesn't. 

If any I'd rather state that the order form should be named "Buy Form" / "Sell Form" rather than having the asset in it. The asset you trade is already state once in the header.

Secondly the title would be to long to be able to include everything like
"Buy Orders 'InsertVeryLongAssetNameHere' Arrows Arrows Pin MarketDepth Group"

Not sold on this idea.

**Comment by froooze** [comment]
I found it confusing, to not see the asset name of what to buy and to sell on top anymore.

**Comment by startailcoon** [comment]
Not all assets have an icon to display

**Comment by froooze** [comment]
https://github.com/bitshares/bitshares-ui/pull/3199
