### ISSUE TITLE
[6] Make sign-up newbie friendly

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#258]
A lot of support requests start with people not knowing how they registered their account. 
followed by "what's a .bin?"

Proposal: Only offer Account Model, hide full wallet behind an explanation

+ Display a Link to a Secure Password Manager: https://www.keepassx.org/

![](https://i.imgur.com/iLM7cwu.png)

**Comment by landry314** [comment]
I highly disagree that the Account model should be the default and the Wallet model be a small link somewhere because the Wallet model is the most secure of the two.

I can imagine people using the account model with the name of their dog followed by the digits in their birthday and then having someone hack their account and steal all their funds. It really is not safe.

I do think that it needs to be clearer what the difference is, yes, and the backup process should be explained more. We should explain that the backup file needs to be copied to a flash drive and moved offsite in case of fire or theft. This is very important.

**Comment by wmbutler** [comment]
Further discussion: I think there are 3 options for anyone arriving at the reference wallet for the first time:

- Wallet
- Login
- Restore

I think that wallet and Login should carry equal weight as well. I also believe that the restore operation should stand on its own. I think we need recognizable icons for each with descriptions that are revealed when the user hovers over each. I'll start submitting some UX for this as well so we can comment.

**Comment by landry314** [comment]
Excellent idea to add Restore to the options, this will make it clearer.

I suggest "New Wallet" and "Restore Wallet" to further clarify.

**Comment by wmbutler** [comment]
Is there a Restore function for the user account with a brainkey?

**Comment by btsfav** [comment]
@wmbutler @landry314 excellent ideas! I'd like to test this one please

**Comment by flux627** [comment]
Maybe if the names were just a little more descriptive it wouldn't be as confusing. The wallet model could be called "Local Wallet", and the account model could be called "Cloud Account" or "Anywhere Account" or something else memorable. All with different contrasting icons. When someone is signed in using a "Cloud Account", it should show a cloud by their name.

Right now the differentiation between "wallet model" and "account model" is wallet vs. account, which is confusing because *wallets contain accounts*. I've done a lot of customer support, and most people, even ones who don't have a problem (yet), don't know which account model they used, and assume that since their wallet contains an account that it must be the account model. Using words like "Local" and "Cloud" make it much more clear as to what is happening.

**Comment by o5j5vg55bv5hv5j5f8799f9** [comment]
I, as a user, am mostly concerned about what I have to back up when I choose.

So I see choices as 

- I have to save (1) account name (2) strong private key

or

- I have to save (1) account name (2) password (3) file

for me saving and keeping track of files is not an option. I cannot think of a way to do that securely, so I stick with account model which is closest to what I use for 99% of other crypto via HD wallets.

**Comment by btsfav** [comment]
so with the flood of new users, it's very clear that giving the user a choice at sign-up is a bad idea.

please make account model default, or make the decision process more obvious and seamless for the new user

**Comment by wmbutler** [comment]
## Welcome
The welcome page has options for Creating a New Account (Account Model) or logging in (Account Model). Wallet Model will be hidden behind Advanced. 

![screen shot 2017-10-05 at 6 03 29 pm](https://user-images.githubusercontent.com/1254810/31256343-8846be6a-a9f7-11e7-8d11-3b808fa909c4.png)

## Register
Much less verbose but still has appropriate warnings. Adopts upcoming tables look.

![screen shot 2017-10-05 at 6 04 14 pm](https://user-images.githubusercontent.com/1254810/31256357-a06c5176-a9f7-11e7-9a1b-ec9f137fb63f.png)

**Comment by wmbutler** [comment]
Related to #301

**Comment by knifewine** [comment]
I like these new mock ups

+1

**Comment by btsfav** [comment]
+1 need this asap

**Comment by wmbutler** [comment]
I really like "Your Decentralized Exchange" better.

**Comment by kimchi-king** [comment]
@wmbutler The new layout is fantastic. Great work.

Could we switch the default theme to the "Light Theme"? Makes everything fresher and easier to read.

**Comment by wmbutler** [comment]
- [ ] The generated password field cannot be highlighted/selected for copy/paste on the iPhone. I think we will want to allow for this.
- [ ] We need to reduce the font size so the entire password is visible.
- [ ] Need a bit of javascript that automatically selects the entire contents to reduce the chance of a copy/paste error.

![register](https://user-images.githubusercontent.com/1254810/31280814-37e92210-aa73-11e7-8ce2-7c4b3955f688.gif)

**Comment by wmbutler** [comment]
Change to: Cloud Wallet Login

![screen shot 2017-10-06 at 8 53 21 am](https://user-images.githubusercontent.com/1254810/31281012-d7acd6f2-aa73-11e7-8518-65b324b7f10c.png)

**Comment by jojapoppa** [comment]
there are issues related to conversion to wallet mode from account mode, already tracked in git.  if those issues can first be resolved,  then this proposal would be great for new users.  is it also possible to enforce a password strength policy? or better yet require a pass phrase as they are stronger and easier to remember?

**Comment by btsfav** [comment]
@jojapoppa bitshares.org uses strong passwords by default. it's pre-created

**Comment by jojapoppa** [comment]
ah.  then the passwords are covered then.  i noticed that you do allow spaces in them, so if folks know to write out an easy to remember phrase, they would be in good shape.  (that is if they decide not to use the unintelligible auto-generated sequence of random characters...) ;-)  It just seems a shame that everyday people don't know to use phrases, as they are stronger than sequences of characters, and usually very easy to memorize.  But, okay, I get it...

But, I do still think the Account conversion to Wallet mode needs to be ironed out better in order to achieve your goal... tx for creating this ticket though!!!  It's badly needed.

**Comment by svk31** [comment]
So something like this? 

![image](https://user-images.githubusercontent.com/6890015/31305807-55ba7c6a-ab42-11e7-8875-44a33156a05b.png)

**Comment by btsfav** [comment]
it's deployed here https://r.bitshares.eu/e15712aee74b4732/ - looking very good (+ref working).

one thing is missing: tips on account name. people need to know the criteria for new acc names.

**Comment by wmbutler** [comment]
@jojapoppa the purpose of this issue it to make onboarding easy, not to "iron out account conversions".

**Comment by wmbutler** [comment]
- [ ] Double check that this bug is not present before release: #521 
- [ ] Redirect to Account/Dashboard after login and after registration #522

**Comment by jojapoppa** [comment]
I see.  Yes, this "Cloud Wallet" language looks like a solid improvement.  Thank you.

**Comment by o5j5vg55bv5hv5j5f8799f9** [comment]
1st: This looks amazing. Black background, those colors, what a difference. Wallet model behind advanced is going to solve so many problems.

Here is something key I've noticed.

**People don't understand they are making a blockchain account.**

example why:

> Welcome to BitShares
> Your Decentralized **Exchange**
> Your share in the Decentralized **Exchange**

They think they are making an exchange account. Like a website account. Someone was upset it was hard to remember password and no 2fa - when has someone been upset they couldn't remember bitcoin's private key or that it doesn't have 2fa.

> GENERATED PASSWORD
> I UNDERSTAND THAT NO ONE CAN RECOVER MY PASSWORD IF I LOSE OR FORGET IT
> I HAVE WRITTEN DOWN OR OTHERWISE STORED MY PASSWORD

**People don't generally associate losing password with losing money.** Ever.

That's great. Still nothing mentions this being a blockchain account and money. 
I rarely reed check marks honestly.

Here are words we need to hear: **money**, **wallet**, **lose**

![registration](https://user-images.githubusercontent.com/22536095/31322614-fede6dca-ac68-11e7-8d85-8fd7f382f38f.jpg)

Maybe it will be less glanced over if only a little text is used at a time: A user is slowly walked through it like in many good websites. Rough drawing of suggestion.

Thanks!

**Comment by wmbutler** [comment]
Your UX is truly dizzying :). @svk31 let's concede the point that we need to mention funds can be lost:

- [ ] I understand that I will lose access to my funds if I lose my password

**Comment by svk31** [comment]
I agree we also need to make people understand they're making a blockchain based account, here's an example confused user from Telegram right now:

![image](https://user-images.githubusercontent.com/6890015/31328682-a5b85a76-acd6-11e7-8f2d-a509fa0e1fc2.png)

**Comment by btsfav** [comment]
@svk31 perhaps too philosophical for this discussion, but I'd start calling BitShares either a Decentralized Trading Platform or Blockchain Trading Platform, a trading platform is a top level term and includes wallet, exchanges and so on.

**Comment by landry314** [comment]
Since many people do not understand that your name is your address in graphine blockchains, I think this should be made a little clearer upon account creation.

"The account name you choose needs to be unique, as it will be registered publicly on the blockchain and will be your identifer for any transactions you make." is good but how about adding another line to make it very clear:

"Your Account Name is your BitShares Address"

Also, "Your Web Browser is your Wallet" is a little confusing. My web browser? Like Firefox? If the user is using a web browser to interface then "You use your browser to interface with your wallet" is a little clearer. But what if the person is using the stand alone client? Then, it isn't clear that this is what you are referring to. How about:

"Your Web Browser or BitShares Client are how you interface with your Wallet"

I think these two lines clearly placed on this screen will help new users understand better the BitShares system.
