### ISSUE TITLE
Add "Active Markets"

### ISSUE THREAD

**Issue by destenson** [bitshares/bitshares-ui#267]
Instead of, or in addition to, the "My Markets" section of the Exchanges screen, there should be an Active Markets section. It should show only markets that are "active", those which have had orders filled "recently" (in the last few months). There should also be a way to select, search for, or get a list of all markets that have open orders waiting to be filled. I'm sure that more people would be trading on the lesser known markets if they were aware of the bargains that may exist there.

**Comment by grctest** [comment]
Perhaps taking the closeness of open orders to feed price for MPA trading pairs into account would be wise, otherwise I could create bitUSD:randomUIA at an inflated rate to spam the active section.

I do like this idea, trying to find possible trades (without the use of a bot to monitor favourite trading pairs) is quite difficult.

**Comment by landry314** [comment]
@destenson, I agree that the markets section is a bit wonky and misnamed but did you know that you can click on the star to the left of the asset to label it as a favorite then click on "SHOW [STAR] ONLY" at the top to turn it into the My Markets it actually should be?

I think that "MY MARKETS" should be renamed to "MARKETS". It is only "MY MARKETS" when "SHOW [STAR] ONLY" is selected.

**Comment by wmbutler** [comment]
Markets needs an overall rewrite. Leaving this open for discussion.

**Comment by o5j5vg55bv5hv5j5f8799f9** [comment]
This is my rough idea to make it generalized (just quick edit in paint, can be done better) :

![qbwqrf8](https://user-images.githubusercontent.com/22536095/29631922-3e2b70dc-880f-11e7-8808-83898bbd00f3.png)


No find markets tab - not necessary - the filter should be finding markets
- wild card assumed so typing btc should search anything containing bitBTC and open.BTC like *BTC* while typing. can limit to only top N by volume pairs (lets say top 20-40)
- if star only is checked, then the filter only looks  for stared items (Faster)
- needs asset information page readily available (instead of going through explorer) like a small letter i next to each one for info or mouse over pop up or something similar - so people can see permissions, who issued, description, and so on - security and education reasoning. some do have mouse over info, but not all, and asset description is much more detailed. could even include similar things to cryptofresh asset info.
- by default assets should be ranked by volume highest to lowest
- top assets ranked by volume highest to lowest
- volume should be in default units just like the estimated total balance on top bar and clearly stated and adjustable - hence blue link - maybe can rotate between the 2 currencies selected on top and default currency
- when both fields are blank it should list top volume of every pair so bitCNY:BTS  would be in same list as  bitUSD:open.BTC with (lets say) default volume units set to bts
- list should be sortable (but still show only top N volume pairs to avoid pointless tokens which could be found with better filters)
- for base currency can provide some suggestions via drop down arrow and top assets which will replace base currency (in case suggestions become outdated for some reason). I think top assets are useful for discovery purposes. 
-  interchange arrows between pairs switch contents of each box

**Comment by svk31** [comment]
As always the main issue here is the API: there is no way of getting active markets, top markets, markets with open orders etc from the current API. Also, since any asset can be paired with any other asset, the number of combinations are staggering, which is why there needs to be a search functionality.

**Comment by wmbutler** [comment]
It's conceivable that rather than display active markets, we could consider harnessing the coinmarketcap API and just list the top cryptos by market cap. For those assets that trade on the dex we might offer jumping off points to the dex

**Comment by o5j5vg55bv5hv5j5f8799f9** [comment]
That's fair. Ideally would be nice for each asset to have some that information within its parameters that can be continuously updated.

How about this: to reduce the number of combinations, fill the blank sorting list of length N by observing blocks as they appear every 3 seconds. Higher volume tends to have higher activity from bots and will make it trivial to fill. Replace contents of list when a better combination is found or additional rules are added.

**Comment by wmbutler** [comment]
#1007 will cover this.
