### ISSUE TITLE
[1] Vertical order book width is sometimes to small

### ISSUE THREAD

**Issue by shulthz** [bitshares/bitshares-ui#2734]
![图片](https://user-images.githubusercontent.com/34892308/58608929-54dfa300-82d8-11e9-8fc0-56149a6a47ba.png)
![图片](https://user-images.githubusercontent.com/34892308/58635767-49649a00-8321-11e9-91c4-9989cb5e4575.png)

I think need to low the NUMBER OF DECIMAL POINTS and asjust the font.

https://www.huobi.co/en-us/exchange/btc_usdt/
![图片](https://user-images.githubusercontent.com/34892308/58609568-8e191280-82da-11e9-8e1d-aa9af898535c.png)

![图片](https://user-images.githubusercontent.com/34892308/58635597-da874100-8320-11e9-911a-8e71c02b12f3.png)

**Comment by abitmore** [comment]
It's not due to number of decimals after the decimal point, but the numbers before the decimal point. HB's order book is not as thin as GDEX. For this kind of extreme case, I guess it's necessary to show the horizon scrollbar.

By the way, the `0.00001000` amount is clearly a bug, because GDEX.ETH's precision is 6, aka at most 6 decimals after the decimal point.

**Comment by startailcoon** [comment]
Indeed, when an orderbook is so narrow it displays all the obscure orders at the end of it we have a few markets with up to 10000x the market price, making the table unable to hold all the digits. 

We need to look closer to the horizontal order book view for this. The vertical orderbook doesn't have this issue as it's limited to how many orders it displays initially.

**Comment by shulthz** [comment]
https://olddex.cybex.io/market/JADE.BTC_JADE.USDT

**Comment by sschiessl-bcp** [comment]
Would introduction of scientific notation help in that case? Is that feasible towards traders minds?

**Comment by startailcoon** [comment]
I will take a closer look at this again. The panel has a fixed width, as it would grow when required, but never shrink, making the orderbooks with less space requirements be extremely stretched. The size only changed once reloaded.

**Comment by startailcoon** [comment]
I propose that when the price of a bid/ask goes away from the median to much, it's not going to be visible. This problem only persists mainly because the market has to few bids, and the edges are either 0.0000001 or 10000000. 

We should only allow +1 digit from the median price. If the median is 1.0 we allow up to 99.9 to be visible. If the median is 10, we allow up to 999 etc.

Markets that has enough liquidity orders will not have this problem because the UI will never receive the edges of the order book.

However, there is also a requirement for a better handling of dynamic width, with is problematic with current structure and needs more time.
