### ISSUE TITLE
Accept terms of service for CryptoBridge

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2748]
**Describe the bug**
Cryptobridge requires to accept the term of service to use their platform, now.
Using the Deposit function does not show this and coins do not show up in balance.

**Expected behavior**
Show a button to accept terms of service, if terms of service were not already accepted.

**Desktop (please complete the following information):**
- Bitshares.190424

**Additional context**
https://crypto-bridge.org/2019/02/26/urgent-announcement-terms-of-service-identity-verification-requirements/

**Comment by sschiessl-bcp** [comment]
@mindphlux1

**Comment by christophersanborn** [comment]
I got bit by this today on the withdrawal side.  Bought some bridge.BTC and tried to withdraw it.  CryptoBridge would neither remit the BTC nor refund the bridge.BTC until my account would "accept" the ToS.  Unfortunately, this seems to be something that can only be done through CB's custom API.  I don't think it can be done through any of the general use BitShares API servers.

Safest option may be to remove Crypto Bridge from the list of supported deposit/withdraw options.  Otherwise users may lose funds or endure a grueling customer support process.  (CB did eventually make it right with me.)

**Comment by froooze** [comment]
The ToS requirement kills the whole integration.

**Comment by sschiessl-bcp** [comment]
No reaction so far.

**Comment by froooze** [comment]
> No reaction so far.

Time to remove CB from the reference wallet.

**Comment by sschiessl-bcp** [comment]
@mindphlux1 Deactivated CB for now

**Comment by froooze** [comment]
Cryptobridge is out.
