### ISSUE TITLE
[0.25][3.1.190618-rc1] - Prevent margin position columns from resizing  

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2777]
**Describe the bug**
Clicking on the margin position columns to switch from normal to cumulative does resize the columns.

**Expected behavior**
- using the **Σ** sign before the description instead of the **(CUMULATIVE)** afterwards
- adding a blank before the description for normal mode to have same word length

**Comment by sschiessl-bcp** [comment]
Agreed. This is the component in question
![image](https://user-images.githubusercontent.com/33128181/59608315-5fda6600-9115-11e9-8d95-379249f77e6a.png)

See e.g. https://develop.bitshares.org/#/asset/USD asset info on the bottom.

Put the blank after the description though, otherwise the normal view is not aligned.
