### ISSUE TITLE
Link from exchange/trading view to the asset detail page?

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#280]
What do you think about including subtle links on the exchange page '/market/BTS_USD' to the '/asset/USD' and '/asset/BTS' pages (one or both)? (bts/usd for example)

Rather than having to click the following to access the full asset details:
settings cog -> Explore -> Assets -> Pick asset type -> Search for asset -> Click correct asset name

**Comment by wmbutler** [comment]
I do fundamentally like the idea because it allows a user to get to all the details of the asset. We have a conflicting control on the pair `ASSET1:ASSET2` in that the user can opt to swap the trading pair, but I think that we could provide a different control for that and let a click event take the user directly to the asset explorer.

Setting as a proposed feature to allow for discussion.

**Comment by svk31** [comment]
Fixed in https://github.com/bitshares/bitshares-ui/issues/416
