### ISSUE TITLE
[1.5][happyconcepts] Remove Trollbox

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#289]
Based upon votes on #281

**Comment by happyconcepts** [comment]
Please consider repurposing trollbox window functionality instead of
throwing it away.

That anchored window popup could be a useful way to deliver error messages
to users, for example.

Plus I liked seeing how many other people were online ...

Please!



On Aug 18, 2017 7:50 AM, "Bill Butler" <notifications@github.com> wrote:

Based upon votes on #281
<https://github.com/bitshares/bitshares-ui/issues/281>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bitshares/bitshares-ui/issues/289>, or mute the thread

**Comment by happyconcepts** [comment]
So I would like to claim this, it is marked for the 170914 sprint. Thank you.

**Comment by wmbutler** [comment]
@happyconcepts it's yours but the issue specifically states it's for removal only. A separate issue can be opened at a later date for a new feature. This PR will only be paid for removal.

**Comment by o5j5vg55bv5hv5j5f8799f9** [comment]
Can the trollbox be done on chain to allow global platform communication with fee cost of course. and not random UI specific chat? Possibly reserved for important announcements that way. Fees can go towards development.

**Comment by btsfav** [comment]
please add a link to discord too: https://discord.gg/GsjQfAJ

**Comment by wmbutler** [comment]
Added .25 to have this added to discord as well @happyconcepts

**Comment by happyconcepts** [comment]
I have removed the trollbox locally and it tests fine; my plan is to submit the PR later today. 
....but where exactly would you like the discord link? For now I just added it to the readme.

**Comment by btsfav** [comment]
@happyconcepts check how its done @ bitshares.org/wallet

**Comment by wmbutler** [comment]
I think it's fine. Disabling the trollbox from a security/stability standpoint was my biggest concern.

**Comment by svk31** [comment]
So what exactly is this issue for? The trollbox is already disabled in the code and has been for a long time.

**Comment by happyconcepts** [comment]
I took the further step, to remove dependencies for it and remove the react
component. It seemed the logical way to fulfill the requirement e.g.
"Remove trollbox"

So there is no place to put a discord link. But if you will keep it
bountied at 1.5 I think that is more realistic for the task. This can even
push with the Sept 1 release, as its ready.

**Comment by wmbutler** [comment]
Updated to 1.5 and thanks for removal.
