### ISSUE TITLE
[3] Ability to hide UIA's

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#311]
There are cases where a user might want to create an asset and then decide that they do not want to use it. A good example is WHALESHARES. This asset was created likely in an effort to deter a squatter from taking it and tricking users into purchasing it. Unfortunately, the asset is still searchable. As such, if I am interested in purchasing a WHALESHARE UIA, I perform a search for 'WHALE" and am presented with both the WHALESHARE and WHALESHARES tokens.

If the UIA holder could choose a flag to hide the token, they could minimize confusion to the end user.

**Comment by wmbutler** [comment]
IMHO we don't need to change the core. For example:

```
get_asset WANGCHANGE
{
    ...
    "description": "{\"main\":\"Promoting projects and awareness with creative, original and sometimes provocative entertainment that inspires and challenges the viewer to overcome obstacles or \\\"Rethink Everything\\\" in the blockchain ecosystem\\n\\nThis is not legally binding.\",\"market\":\"USD\",\"short_name\":\"Promoting projects that inspire\"}",
    ...
}
```

There are 3 fields encoded in description, it's done in GUI, so GUI already knows how to deal with the additional info. If we want the feature described in this issue, just add more fields there.

**Comment by wmbutler** [comment]
Got it. So we could encode "visible":"false" upon asset modification in the GUI and have the search respect that flag...

**Comment by calvinfroedge** [comment]
To hide permanently, an API call will need to be made to update the user preferences vs just putting something in local storage. Is there already a preferences API? @wmbutler @svk31

**Comment by wmbutler** [comment]
Let me clarify. This feature is not intended to allow the average user to hide random UIA's. This feature is intended to allow the **creator** for the UIA to specify a hidden flag that frontends could respect. It would also be important for the search indexing to respect the hidden flag.

**Comment by o5j5vg55bv5hv5j5f8799f9** [comment]
Since issued assets have editable asset description pages, simply making it easier to read description of UIA in market or search would make it easy for creator to describe purpose of each.

Right now I see having mouse over SOME asset names gives hovertext of their description. Sometimes it doesn't work until I click on names. I think it should give full description for ANY asset/coin in market list or in search. I can see my own assets with a description do not have hovertext right now when I mouse over them in market page or in search page. I am not sure how people get that hover text in first place.

Right now mouse over changes cursor to cursor with question mark while showing tooltip at same time, I think cursor change is not necessary as the hovertext is obvious when it shows up at same time. A more obvious symbol for information could be even better and even be clickable (from another mock-up the "i" symbol or similar https://i.imgur.com/QBWqRf8.png)

**Comment by wmbutler** [comment]
@o5j5vg55bv5hv5j5f8799f9 Your comment, while a good suggestion has nothing to do with this issue. If you wish to suggest a feature, please open a new GitHub issue.

**Comment by happyconcepts** [comment]
Will this visible setting be dependent upon props like token ownership? What would stop a bad actor from issuing a UIA in exchange for BTC and then hiding it, for example.

**Comment by wmbutler** [comment]
It would be dependent on ownership. It wouldn't stop a bad actor at all. It's really intended for those who reserve similarly named coins so they can reduce confusion. For instance, if I have a UIA called WHALESHARE, I could also reserve WHALESHARES and hide it.

**Comment by calvinfroedge** [comment]
@wmbutler Can you provide a UX or at least a path that represents the area I need to cover for this? I.e. creating user issued asset and then marking the asset as hidden.
