### ISSUE TITLE
[2] (Research time) Fetch additional data for chart as user pans left

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#321]
If a user wants to review historical data on the exchange, fetch it as the user pans to the left.

**Comment by calvinfroedge** [comment]
@rrag I'm having trouble triggering an onPan event. I've tried including `EventCapture` inside a `ChartCanvas`, but it seems like this is more for internal use. In any event, I can't figure out a way to easily capture the pan event so that we can load more data. Is this something you could provide some guidance or an example on?

**Comment by calvinfroedge** [comment]
Did a bit of exploration here...

`onLoadMore` prop on `ChartCanvas` method allows us to capture the pan event. This gives us some numbers which are presumably some positioning.

The next step would be loading new market data. Most of this happens in `actions/MarketData` in the `subscribeMarket` method.  We need to refactor this method a bit (maybe split it up), and then call it after pan, probably showing some loading indicator while loading new data.

**Comment by wmbutler** [comment]
@calvinfroedge should I push this to next Sprint?
