### ISSUE TITLE
Chart not rendered correctly when margin call order is in orderbook

### ISSUE THREAD

**Issue by ppitonak** [bitshares/bitshares-ui#326]
Buy side of order book is not displayed correctly in chart when there is a margin call order with feed price +10%.

![bts_call_not_in_chart](https://user-images.githubusercontent.com/445100/29709359-571ba886-898c-11e7-8a4f-a57a773d8977.png)

**Comment by svk31** [comment]
Please explain what's incorrect.

**Comment by ppitonak** [comment]
I would expect that buy and sell orders in tables at the bottom would be represented in graphical form in chart.

If you look on screenshot, highest buy order is 82800x bigger than lowest sell order but in the chart they are similarly high. It seems that the order to buy 0.00000140 bitbtc at the price of 35714 bts/bitbtc is the one displayed in chart but the buy order for 27 bitbtc is not displayed.

**Comment by svk31** [comment]
The big buy order is a call order and is visible in the screenshot as the big yellow wall. Because it's so big it's hard to make out the highest bid and lowest ask on the chart but they're there. 

Margin calls are a special order type with slightly different rules which is why they're plotted separately.
