### ISSUE TITLE
Tradingview for Charts

### ISSUE THREAD

**Issue by malcolmjmr** [bitshares/bitshares-ui#361]
- [x] [1.5] Research #774
- [x] [20] UDF Wrapper #773 
- [ ] [10] Swap old charting for Tradingview #905 

![screen shot 2017-10-07 at 12 49 56 pm](https://user-images.githubusercontent.com/1254810/31310445-0c202a34-ab5e-11e7-9d09-c21d12c54d72.png)

TradingView has probably the best charting functionality that I've used while trading crypto. It's really simple to use for novices and has all of the indicators and charting functionality that you would want if you are an experienced trader. 

Currently, when trading on Bitshares I don't use the charts at all. It's not very usable. We need to integrate better charting libraries to retain more traders. 

https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/

**Comment by wmbutler** [comment]
That is pretty slick. We are updating to the latest react charts this month. Maybe you can re-evaluate after 9/14 and see if there are any improvements. #350

**Comment by svk31** [comment]
I like TradingView as well and have considered it on many occasions. I'm not sure we would get a license though, since we're not a traditional organization and the library will not be used on only one website but on any website running the BTS GUI. There's also an issue with respects to the documentation, which is only available to pre-approved users of their library.

**Comment by wmbutler** [comment]
I'll talk to them.

**Comment by o5j5vg55bv5hv5j5f8799f9** [comment]
possibility additional charting tool demonstrating how to use it 

permission thought bitshares.foundation 

see another (sort of) dex platform using it 
![image](https://user-images.githubusercontent.com/22536095/31235400-751cef54-a9bf-11e7-88ce-7da607649b5e.png)

**Comment by wmbutler** [comment]
Hi Bill,

The charting platform is perpetually free for any public use (including commercial). Don't worry! It's free, there are no fees.

You can grab the free charting platform here. Fill out all fields, sign and upload the provided form.



Best regards,
Aziz J. Kenjaev
Account Manager
www.tradingview.com
LinkedIn / Twitter
On 06.10.2017 15:24:19, Bill Butler <bill@butler.net> wrote:

If we add the tradingview charting capability to the dex product, will there be monthly fees to account for? How does your billing work? Since none of us directly derives revenue (other than investment in the bts token) would you put bts in a category of non profit and waive fees?

These are the types of questions that keep us from moving forward with implementing. 

Thanks so much for your time. 

Sincerely,

Bill Butler

On Fri, Oct 6, 2017 at 7:17 AM Aziz J. Kenjaev <aziz@tradingview.com> wrote:
Hi Bill,

Thanks for reaching out!

Please share your concerns and we will discuss them.

Best regards,
Aziz J. Kenjaev
Account Manager
www.tradingview.com
LinkedIn / Twitter


From: Bill Butler <bill@butler.net>
Date: 10/5/2017 7:03:55 PM 
Subject: Bitshares DEX Inquiry 
To: founders@tradingview.com

Mr. Bokov,

My name is Bill Butler and I am heading up a UX rewrite for the Bitshares Distributed Exchange. We are interested in incorporating the TradingView library into the DEX. We believe it will solve many issues that we have on our exchange pages and will provide significant benefits to our user base.

Bitshares is a cryptocurrency whose function is to act a Decentralized Exchange. It is based on a  high-performance graphene blockchain and has been around since 2012-2013.

There are some underlying concerns about licensing and how this might be handled. We do have resources and governance that would allow us to pay for the use of trading view. We are also open to any other arrangements that you might suggest.

Thanks for your time.

Sincerely,

https://bitshares.org

**Comment by leandrovaldez** [comment]
this is a really powerfull feature to improve the UI of bitshares, it's a must to get the real and usefull tools to drawing for TA

**Comment by calvinfroedge** [comment]
Has anyone downloaded the source package and confirmed the code can be implemented all client side? Want to be sure this doesn't involve adopting a backend as well.

**Comment by tximiss** [comment]
I'm concerned about the TV integration as it may mean a servitude towards external agents.

**Comment by wmbutler** [comment]
@calvinfroedge go ahead and spend time on this and I'll credit research hours to you.

**Comment by svk31** [comment]
@wmbutler I don't think this offers depth charts, so the current depth charts will have to remain and issues related to them should stay open.

**Comment by calvinfroedge** [comment]
@wmbutler I will download the source code for TradingView and check it out

**Comment by calvinfroedge** [comment]
I have officially requested access to the source code and am awaiting acceptance. Time spent so far: 0.25 hours.

**Comment by wmbutler** [comment]
Any word yet?

**Comment by calvinfroedge** [comment]
@wmbutler I have access to the source. It appears that the library requires a "UDF Compatible Data Feed", which needs to be implemented server side. This seems to be something that is specified to TradingView. I do not think it's possible to use their client side library without a server side component that operates in this way and thus far I have only found a node js implementation that indicates what a "UDF Compatible Data Feed" actually is. Here's an example bit of JSON the server would spit out:

```

		result.d.push({
			s: "ok",
			n: ticker,
			v: {
				ch: +(quote.ChangeRealtime || quote.Change),
				chp: +((quote.PercentChange || quote.ChangeinPercent) && (quote.PercentChange || quote.ChangeinPercent).replace(/[+-]?(.*)%/, "$1")),

				short_name: quote.Symbol,
				exchange: quote.StockExchange,
				original_name: quote.StockExchange + ":" + quote.Symbol,
				description: quote.Name,

				lp: +quote.LastTradePriceOnly,
				ask: +quote.AskRealtime,
				bid: +quote.BidRealtime,

				open_price: +quote.Open,
				high_price: +quote.DaysHigh,
				low_price: +quote.DaysLow,
				prev_close_price: +quote.PreviousClose,
				volume: +quote.Volume,
			}
		});
```

It may be possible to use a middle server that translates the data coming out of the bitshares API to what the trading view library can consume, but that would take more investigation and frankly may be a dependency we don't want to adopt.

It's not like a react component where you just consume some props and pass them down, the server dependencies are built into the code.

Which brings up another point about the trading view charting bundle:

- All dependencies are packaged together (minified)
- The trading view source code is minified in the package I have access to (so it's not truly the source code)

**Comment by wmbutler** [comment]
OK,

Hoping to get some feedback from others here. Thanks for your work. Please put the appropriate hours in the header.

**Comment by svk31** [comment]
Formatting the data like that shouldn't be a problem in the GUI, the data is already parsed and formatted extensively in MarketsStore.jsx. Feeding updated data may be trickier, as it may require a special react component with shouldcomponentupdate returning false and us handling the update cycle manually. That's certainly doable though.

**Comment by ai3d-brodie** [comment]
Having the settled and open orders on the chart ala Coinigy is so important for frequent trading.  I still dont do regular day trading on Bitshares or Binance due to them missing on chart order display.  Also regarding tradeview , a guy i was talking to on a slack channel made this nice little project https://www.multicoincharts.com/   Im guessing the problem with tradeview is going to be having all of the assets on their database, unless you can somehow add your own.

**Comment by smogm** [comment]
Would be nice to have this implemented as soon as possible!

**Comment by wmbutler** [comment]
Still looking for a volunteer. Wrapper is wriiten and ready to go.

**Comment by smogm** [comment]
@wmbutler what are the steps that have to be done?
Just placing the widget into the page layout and feeding it with data?

**Comment by wmbutler** [comment]
We have the UDF wrapper. I'm not sure how complex it will be but I assume there are a number of things that could present problems. If you want to see how it's been incorporated already with bts feeds and the UDF wrapper, take a look at this:

http://bitshares-explorer.io/#/markets/CNY/BTS

**Comment by svk31** [comment]
Cool, I didn't realize he'd already implemented it. I guess I'll have a crack at it then, we're also dependant on replacing stockcharts for react-16 compatibility so it'll be nice to get this done.

**Comment by smogm** [comment]
@svk31 Would be a really **huge improvement** if you could implement it!
The current chart feature is the most annoying part of the gui.

Keeping my fingers crossed!

**Comment by wmbutler** [comment]
The issue is technically #905 This is just tracking all the work required thus far.

**Comment by startailcoon** [comment]
Issue #905 has been closed, expiring this issue tracker.

**Comment by rahulpagada** [comment]
**_ERROR TypeError: Cannot read property 'UDFCompatibleDatafeed' of undefined_**

> please give me this error solution?

**Comment by sschiessl-bcp** [comment]
How can we reproduce it?

**Comment by TechsUsInc** [comment]
@sschiessl-bcp 
![openexplorer_capture](https://user-images.githubusercontent.com/18186497/53441459-86408e00-39cc-11e9-9571-2db96e4e3e83.JPG)
![openexplorer_2-capture](https://user-images.githubusercontent.com/18186497/53441864-5f368c00-39cd-11e9-9b97-6ea5576c4fd3.JPG)


``` function Cb() {
        var a = !0
          , b = this;
        this.debugEnabled = function(b) {
            return r(b) ? (a = b,
            this) : a
        }
        ,
        this.$get = ["$window", function(c) {
            function e(a) {
                return a instanceof Error && (a.stack ? a = a.message && -1 === a.stack.indexOf(a.message) ? "Error: " + a.message + "\n" + a.stack : a.stack : a.sourceURL && (a = a.message + "\n" + a.sourceURL + ":" + a.line)),
                a
            }
            function f(a) {
                var b = c.console || {}
                  , f = b[a] || b.log || m;
                a = !1;
                try {
                    a = !!f.apply
                } catch (g) {}
                return a ? function() {
                    var a = [];
                    return d(arguments, function(b) {
                        a.push(e(b))
                    }),
                    f.apply(b, a)
                }
                : function(a, b) {
                    f(a, null == b ? "" : b)
                }
            }
            return {
                log: f("log"),
                info: f("info"),
                warn: f("warn"),
                error: f("error"),
                debug: function() {
                    var c = f("debug");
                    return function() {
                        a && c.apply(b, arguments)
                    }
                }()
            }
        }
        ]
    }```
