### ISSUE TITLE
[24] Tables Rewrite - Dashboard

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#378]
The idea behind a tables rewrite is to change the look without worrying too much about functionality. This amounts to a facelift while establishing some best practices for the future. The wallet has a somewhat haphazard approach to accessing certain features. Some items are in a top menu and others are on a side menu. Side menus are notorious for wasting horizontal space. I think they should go away ultimately, but don't want to change so much at once that it confuses users. With that in mind, I'm going to submit a table concept for the **Overview** page. As you can see, I've suggested that we call it **Dashboard** instead.

Rather than the user scrolling down and accessing other menus to get to other areas, I've created pills at the top. Areas that contain balance detail also display the total balances in the pill for a glance.

You should notice that the functionality of the table is identical but instead of clickable text, we have meaningful icons. I have also created separate columns for symbols and quantities so our data lines up in a more pleasing way.

![screen shot 2017-09-19 at 2 31 14 pm](https://user-images.githubusercontent.com/1254810/30611523-3a8170c4-9d47-11e7-86f7-db3bf9d43016.png)

As you view this, realize that the top and side menus aren't visible in my mockup. This table would be displayed in place of:

![screen shot 2017-09-10 at 6 17 11 pm](https://user-images.githubusercontent.com/1254810/30253907-49e04f30-9654-11e7-9a59-5affc943151e.png)

As we get closer to consensus, I also need to propose a light themed version of this.

**Comment by btsfav** [comment]
great!

**Comment by wmbutler** [comment]
Open Orders

![screen shot 2017-09-11 at 5 12 58 pm](https://user-images.githubusercontent.com/1254810/30299257-861d5de2-9714-11e7-8337-d9caf443579e.png)

**Comment by wmbutler** [comment]
Margin Positions

![screen shot 2017-09-11 at 6 08 54 pm](https://user-images.githubusercontent.com/1254810/30300808-54b16b2e-971c-11e7-9266-29444968fee2.png)

**Comment by wmbutler** [comment]
![screen shot 2017-09-12 at 10 05 03 am](https://user-images.githubusercontent.com/1254810/30333144-e00edb54-97a1-11e7-9929-b408a7eb002e.png)

**Comment by wmbutler** [comment]
Activity

![screen shot 2017-09-12 at 11 19 07 am](https://user-images.githubusercontent.com/1254810/30336896-3cd1a11e-97ac-11e7-9d3b-a0db6a9455d8.png)

**Comment by o5j5vg55bv5hv5j5f8799f9** [comment]
These look amazing. 

Few comments

1. whenever you estimate price of USD I think it should say "~" or "EST. USD" before number. B/c on non liquid assets this can be really random. specifically at the top
2. not clear why in open orders you have asset 1 and asset 2 as the same, shouldn't they be pair specific orders?
3. I don't understand what markets the markets tab shows
4. margin positions - this one needs most work. units are jumping around here. 

- maybe switch places for 1st and 2nd columns and get rid of separator so it's clear DEBT is -8000 bitUSD. whenever you have  units to the right of a number, number should be right adjusted and units left adjusted, so can even get rid of the separator between them. (see random space before BTS/bitUSD for e.g.) 
- Then collateral units need to be specified. I can't remember if it can be something other than BTS, but that needs mention in title of column like COLLATERAL (BTS) or to the right of the column. If to the right, might as well have two units there per debt. one in BTS and one in units used for ratio calculation marked as estimate. so for bitUSD it would say 460,000 BTS and right below it ~51341 bitUSD
- need some more info of when getting liquidated here. easiest might be CURRENT PRICE next to CALL PRICE. 
- I simply don't understand what VALUE(USD) means here. Shouldn't it be like USD value of collateral minus USD value of debt? I assume this is the only place locked collateral would count for holdings calculation and not in portfolio. I can't get 1345 USD out of 8000 USD and 460k BTS collateral anyway.
- update row adjustment seems pointless on all of them. should just be sorted by column
- update position field is missing
- very bottom does nice job of summing it up. could make it clearer by putting default units on it and summing up total debt in usd with negative sign, total collateral in usd with negative sign, and net difference for value where it does now (I think). both value column sum and addition of all collateral minus all debt should lead to same number at cross section where 700,000 is written now.

honestly I like having it all on one page with title and black space in between, but I'll manage w/o it too.

5. since portfolio is where the coins you have right now are, available to send, maybe it makes sense to call it just "wallet". there's been some confusion about bitshares dex and where bitshares wallet is and whether people should withdraw from the dex to be safe. It's obvious but having the words wallet written somewhere might finally get people to understand this IS the "wallet". They are literally viewing their account on blockchain.

Hope this helps. cheers.

**Comment by wmbutler** [comment]
1. Maybe a blanket disclaimer somewhere. Easier and cleaner
1. So there are 2 separate columns for those who want to export to a speadsheet. I'm open to combining them.
1. Doh, posted the wrong image. Will repost.
1. It's just a mock :)
    - Not sure I agree with numbers vs asset. I like to see the asset first.
    - What else can act as collateral?
    - That's the value of the collateral.
    - Not adding new features yet. Just changing the look of the tables. Patience grasshopper.
    - Value of the collateral (same as current data but with a different table style)
    - That allows the user to update their collateral position
    - See above
    - Units are in the header. Do we really need it at the bottom too?
1. Wallet is a bad word because it might make people think they are in the wallet mode rather than account mode.

**Comment by o5j5vg55bv5hv5j5f8799f9** [comment]
**re: what else can act as collateral?** - from asset creation menu if you check smartcoin: https://i.imgur.com/XGm0ufl.png for example (no idea if works)

**re 5:** as has been suggested before, wallet-model is extremely confusing and leads to most common questions in support. word "wallet" is used in "wallet model", bitshares.org/wallet, web wallet (which is what all web UI are), light wallet (software wallet, downloadable client has it directly in file name), and generally wallet is "A cryptocurrency wallet is a secure digital wallet used to store, send, and receive digital currency".  generally, wallet is "where your money is".

I have 50+ crypto and they have all generally referred to wallet as software and location in UI where you see your balances: most common wallet design: https://i.imgur.com/bY8j4if.jpg or e.g. steemit web wallet literally has a tab called wallet for balances. openledger.io (most used ui?) under simple mode writes out "wallet" at the top too. 

**the only phrase that has the least business of having the word "wallet" in the name is "wallet-model"**

wallet model is extra confusing because people who are trying to get a wallet pick it because it's called wallet. account model users are confused how do they withdraw money to their wallet from the dex. bts predates a lot of crypto, but should be consistent with terminology to make it easier to understand.

The main difference is in backup requirements (file) and having multiple accounts - hence I think "wallet model" should be renamed - "file model" or "multi-account file model" with the first option hidden unless advanced user. Someone restoring from a file will quite obviously figure out file one is the one to use.

**Comment by wmbutler** [comment]
Regarding the wallet naming, I think we are stuck with it. I think if a user picks an account model and then sees their wallet balance, it's going to get very difficult to support them, whereas, their portfolio can be referred to as such whether they choose the wallet model or the account model.

**Comment by wmbutler** [comment]
Markets

![screen shot 2017-09-19 at 11 42 29 am](https://user-images.githubusercontent.com/1254810/30604226-ce49634c-9d2f-11e7-9f57-cc3dee7e3b3c.png)

**Comment by wmbutler** [comment]
Colors:

Top Left Holdings: 27384B
Top Bar: 1A242F
Dimmed Header Text: 606060
Table Header: 1A242F
Table Cells: 27384B
Bright Text: 000000
Green: 7ED321
Table Cell Border: 323131

**Comment by wmbutler** [comment]
On side bar:

- Change Overview to Dashboard.
- Remove Open Orders since it gets incorporated into the Dashboard.

![screen shot 2017-09-19 at 11 57 46 am](https://user-images.githubusercontent.com/1254810/30604898-ca2a25c4-9d31-11e7-85f8-0eb862ccfc38.png)

**Comment by svk31** [comment]
Holdings vs Portfolio is confusing to me, they mean the same thing.

**Comment by wmbutler** [comment]
Agreed. I'll change that label to Portfolio.

**Comment by tbone-bts** [comment]
I really like the new design of these tables.  One thing confuses me, though.  What is the purpose of the Markets table?  Unless I'm missing something, it really doesn't seem to belong here.

**Comment by wmbutler** [comment]
Well, the problem is.... it doesn't really belong anywhere. Right now it's located above the hierarchy of a chosen account, which, for the majority of our users is kinda silly because they only have 1 account. This means that they have to migrate up in hierarchy to view the market and then choose their account after that. So..... I was thinking, why not just put the market in the dashboard? It's still available to all accounts but it's not in the awkward spot it's in now.

**Comment by svk31** [comment]
The table layout of activity is very problematic due to the amount of different transaction types (~40). Trying to fit them all in a table  will require a lot of columns, making it confusing imo. It also does not handle proposed transactions very well, I'll see if I can find an example of how that looks atm.

Due to the amount of columns its also very bad for smaller screens and mobile, that's a general concern of tables.

**Comment by tbone-bts** [comment]
> Well, the problem is.... it doesn't really belong anywhere. Right now it's located above the hierarchy of a chosen account, which, for the majority of our users is kinda silly because they only have 1 account. This means that they have to migrate up in hierarchy to view the market and then choose their account after that. So..... I was thinking, why not just put the market in the dashboard? It's still available to all accounts but it's not in the awkward spot it's in now.

I'm not just confused about why the Markets table is in the dashboard.  I really don't even understand what its purpose is, or how it's specific to a user.  What is its equivalent in the current UI?  Sorry if I'm being dense!

**Comment by wmbutler** [comment]
@svk31 The motivation behind activity was to make it useful for exports. I've reposted it with a new look but left the layout and functionality the same as the old one so we can move forward and tackle a better exportable activity screen at a later date.

**Comment by wmbutler** [comment]
@tbone-bts I just explained it. It's current equivalent in the UI is this:

![screen shot 2017-09-20 at 10 07 37 pm](https://user-images.githubusercontent.com/1254810/30677222-223ce458-9e50-11e7-88d9-1760b51f52a2.png)

**Comment by svk31** [comment]
Does that mean you want to remove the current Dashboard?

**Comment by happyconcepts** [comment]
Is there a specification for this dashboard  rewrite? I ask because I share some of @svk31 's concerns such as small screen usability, for example.

My higher level concern is that this dashboard page needs to be simplified and not crammed with all the collateral data columns etc for advanced users at the expense of basic or casual users. I would urge breaking the content into two separate screens; back when there were 3 coins it made sense to show them too on this screen, but now no longer IMHO.

Although the dark blue #27384B table cell bg is quite pleasing to me, the trained UX part of me recognizes that the table itself already has a different background color from the rest of the page, and the table header color is effective too. I would urge us to reduce color clutter in the table(s).

I support UI improvement and especially UX improvement, and I want to encourage you @wmbutler for undertaking this rewrite.

**Comment by wmbutler** [comment]
@svk31 I think we should have a screenshare to go everything. @happyconcepts the contents are identical to the current contents, just with a more natural table style. Regarding clutter, that will need to be a separate issue. I don't think it's realistic to change the functionality and the style at the same time. I fear we will never get anything completed.

**Comment by tbone-bts** [comment]
Oh, that.  Why not just leave that as is on the dashboard page (behind the Bitshares logo in the main menu)?  It really makes no sense on the account page alongside all of those account-specific tabs.  

> @tbone-bts I just explained it. It's current equivalent in the UI is this:

https://user-images.githubusercontent.com/1254810/30677222-223ce458-9e50-11e7-88d9-1760b51f52a2.png

**Comment by wmbutler** [comment]
I already explained why.

**Comment by tbone-bts** [comment]
Maybe I should have been more specific.  Your reason for moving it doesn't make sense.  Why would a user need to "migrate up in hierarchy to view the markets and then choose their account after that"?  In fact, why would a user "need" to view the Top Markets table to begin with?  Of course they _can_, if they like.  But they can also go straight to the exchange, and from there choose the market they are interested in viewing.  And if they ever find themselves on the exchange page with the wrong account selected, they can always change that right on the exchange page.  Absolutely no need to jump around the way you are describing.

So I don't understand the problem.  Although perhaps what you're getting hung up on is the fact that the page behind the Bitshares logo, which currently houses the Top Markets table, is called "dashboard" and has some dashboard-y stuff that you want to move to a new dedicated "dashboard" page.  That makes sense, but just leave the Top Markets table where it is, rename its page "homepage" and perhaps add anything else that makes sense on a home/default page to make a good impression on (or be helpful to) first-time visitors.

**Comment by wmbutler** [comment]
I guess my real point is....who really looks at top markets? In the context of trading, I care about my specific holdings and their values? I don't really give a crap about how BTWTY:BTS is trading... Why should I be forced to see that first thing?

I care about My Portfolio on My Dashboard. Sure, I should be able to look at markets if I want, but giving it such prominent placement makes very little sense to me, other than maybe some small indicators for the largest markets like BTC, LTS, ETH.

**Comment by tbone-bts** [comment]
@wmbutler The point I made in my prior post is that the home/default page is for new visitors.  Looking at the websites of Bitstamp, Bitfinex, Bittrex and Poloniex, each has a home/default page that is geared towards new visitors in a similar manner.  That is appropriate and sensible.  Also, 3 of the 4 cited exchanges display Top Markets or some kind of market data on that default/home page.  

I really don't think this is even a minuscule problem for existing users.  They will simply go directly to the page they like to start on via any number of methods including bookmarks, quick links, auto-fill of recently visited sites, etc.

**Comment by landry314** [comment]
Are we to ignore any visual problems with the tables as they are to be replaced? The semi blue border that appears on "See More" after you click on it, for example, I was about to create an issue, but it will probably just be closed and referenced to here...

**Comment by svk31** [comment]
Yea just ignore that for now. 

The tables are almost ready but I won't include them in the next release since we need some color schemes for the other themes and more testing.

**Comment by wmbutler** [comment]
@svk31 There is a black background color that you are missing. It's designed to provide more contrast because of the dark blue.

My mockup:
![screen shot 2017-10-01 at 6 02 50 pm](https://user-images.githubusercontent.com/1254810/31060112-f96751c2-a6d2-11e7-9628-e70ff91ab865.png)


Your progress:
![screen shot 2017-10-01 at 6 04 51 pm](https://user-images.githubusercontent.com/1254810/31060117-0b6ebcc0-a6d3-11e7-9bfe-1870fd420a8d.png)

Also, the header bar should flex width wise so it feels like it encapsulates the contents of each section.

**Comment by wmbutler** [comment]
I did some testing and I think we need:

- 12px left/right padding for headers. Be sure to account for left or right justification
- 10px left/right padding for td's
- I think we can bump up the font size a small amount.
- % Total Supply to abbreviate?

Portfolio Page:
- Add Header title: Hide
- Icon for hiding asset

![screen shot 2017-10-01 at 6 15 29 pm](https://user-images.githubusercontent.com/1254810/31060170-893bf50e-a6d4-11e7-83f1-2b317f4bc503.png)

**Comment by wmbutler** [comment]
Thoughts for Visible vs Hidden Assets. 

- Note Visible/Hidden controls at top.
- Hide / Show controls on last column

![screen shot 2017-10-01 at 6 33 25 pm](https://user-images.githubusercontent.com/1254810/31060316-13fbe684-a6d7-11e7-960b-5d93cfda64ec.png)

**Comment by wmbutler** [comment]
- [ ] Remove Markets Tab/Header. Leave Markets where it is on the current wallet with no style changes. We can tackle that another time.

**Comment by wmbutler** [comment]
- [ ] Remove gray borders from header

![screen shot 2017-10-01 at 7 57 20 pm](https://user-images.githubusercontent.com/1254810/31061079-e074b910-a6e2-11e7-81ca-c56c8e2be11e.png)

**Comment by wmbutler** [comment]
- [ ] Updated open orders (see above open orders UX)

**Comment by svk31** [comment]
Your open orders ux needs to include buy and sell orders, and I definitely think the price of the order still needs to be included.

With only the qty column it becomes hard to know what that actually refers to with no units shown anywhere.

**Comment by svk31** [comment]
Also, how do you navigate from the open orders to a market?

**Comment by wmbutler** [comment]
- [ ] Let's let the Market be accessible by clicking on the Bitshares logo in the upper left and remove it from here. That will keep things consistent for now.

**Comment by svk31** [comment]
I went ahead and implemented Open Orders the way I think it has to be:

![image](https://user-images.githubusercontent.com/6890015/31135705-20aaa880-a866-11e7-927d-c01ee8335206.png)

QTY in this case always refers to the first asset, Total is the second. Clicking the shuffle icon flips the price and switches the Qty and Total columns. I can still get confusing for accounts with many orders, as shown below.

For accounts with orders in many markets I felt it was necessary with some virtual separation between markets, like this:

![image](https://user-images.githubusercontent.com/6890015/31135791-64bbcb58-a866-11e7-9bb8-9d76d9aeca51.png)

**Comment by wmbutler** [comment]
I think visually it would look better if you:

- Centered the markets on the swap symbol (see my open orders mock, this probably requires 3 columns with the swap symbol being in the center column with the other columns are justified right and left respectively).
- Keep the row height the same at all times
- aligned all decimals (even if it means introducing padded zeros)

**Comment by svk31** [comment]
Ah yea the centering is just an oversight from some columns that got merged.

It gets very cramped without any spacing between markets, I'll play around with it to check.

The decimals will vary from market to market due to varying precisions of the assets so it's impossible to have them be the same everywhere I think

**Comment by svk31** [comment]
How about this in Activity:

![image](https://user-images.githubusercontent.com/6890015/31148608-7d62027c-a88d-11e7-9a0a-e3c626a48036.png)

I put the filter select box, csv and 'More' buttons in the final row, and changed the buttons/text for icons. Should I move it to the top maybe similar to the Active/hidden switch in portfolio?

**Comment by svk31** [comment]
![image](https://user-images.githubusercontent.com/6890015/31148895-636ed1be-a88e-11e7-9332-173a4a15db1b.png)

vs 

![image](https://user-images.githubusercontent.com/6890015/31148923-7f2ff59a-a88e-11e7-90db-9d314a3cdf62.png)

**Comment by wmbutler** [comment]
Yeah, that takes care of line height, so now just 

- [ ] decimal padding
- [ ] centering on the switch symbol.

![screen shot 2017-10-03 at 5 09 19 pm](https://user-images.githubusercontent.com/1254810/31151580-ac52ebf8-a85d-11e7-9d90-9e8dc32a2592.png)

**Comment by wmbutler** [comment]
I think the filter controls need to be at the top. I'll get a UX for that.

**Comment by svk31** [comment]
I removed the order expiration time since the GUI doesn't allow you to set it anyway, meaning all orders have 5 year expiration times.

Not sure what you mean by the padding for decimals.

**Comment by wmbutler** [comment]
Regarding expiration times, if we have the info I think it makes sense to display it. Users often look at it in the exchange and don't see the year. By displaying it here, we are providing relevant information and it paves the way towards allowing the exchange interface to accept date/time restrictions on orders.

Here is the difference in look wrt decimal padding.

with_padding | without_padding
----------: | ------------:
3,431,231.20 | 3,431,231.20000000
1.587458 | 1.58745800
1,231.00 | 1,231.00000000
345.6789 | 345.67890000

My point here is that if you always pad to 8 decimals, you end up with a more readable table, one that aligns values making it easier to perform math operations and determine value more easily. After looking at it, I can see arguments both ways. This might be a configurable option in the future, I suppose, if you are opposed to it.

**Comment by wmbutler** [comment]
This screencast demonstrates two subtly adverse behaviors that would be resolved with my suggestions above:

- Column shifts due to changing decimal precisions will go away
- The user will not need to reposition their cursor to swap pairs

![shift](https://user-images.githubusercontent.com/1254810/31153542-56c7cd8e-a867-11e7-8e2f-97e6cf23ec3e.gif)

**Comment by wmbutler** [comment]
- [ ] padding-left: 5px on the Active/Hidden container

![screen shot 2017-10-03 at 6 32 48 pm](https://user-images.githubusercontent.com/1254810/31153911-552c8d82-a869-11e7-8a86-04500dc74d46.png)

**Comment by wmbutler** [comment]
- [ ] 100% height on the black background

![screen shot 2017-10-03 at 6 34 51 pm](https://user-images.githubusercontent.com/1254810/31153970-9e298486-a869-11e7-824c-372e5fbb8e3f.png)

**Comment by wmbutler** [comment]
Updated the Margin positions UX to allow for all the math to add up. Of note:
- [ ] renamed debt column to asset column
- [ ] moved debt column to allow for a value calculation (per user specified currency)
- [ ] Included a value column that should agree for both downward math and across math for preferred currency

![screen shot 2017-10-03 at 6 56 26 pm](https://user-images.githubusercontent.com/1254810/31154426-9b144094-a86c-11e7-8d1e-10346f08bcc0.png)

**Comment by svk31** [comment]
Here's a testnet example with an account holding margin positions backed by something other than TEST (the core asset):

![image](https://user-images.githubusercontent.com/6890015/31169515-28bdaaca-a8f9-11e7-90dd-61d582e10f1a.png)

**Comment by svk31** [comment]
Order expiration just takes so much space I'm opposed to including it.

The 100% height on the black background requires a lot of messing around with css, I wasn't able to figure it out and not sure it's worth it.

**Comment by wmbutler** [comment]
Font consistency. Remove the narrow font from the TH

![screen shot 2017-10-04 at 5 51 37 pm](https://user-images.githubusercontent.com/1254810/31206320-b0ba1c04-a93c-11e7-9c1a-4192ba01451c.png)

**Comment by wmbutler** [comment]
- [ ] Add price column to Portfolio. Use whatever number you use to derive the value column. (i.e. Qty * Price = Value)
- [ ] Can we change "Unknown value" to "NA" for brevity throughout. Otherwise maybe "--"?

![screen shot 2017-10-04 at 7 47 35 pm](https://user-images.githubusercontent.com/1254810/31206496-d1f47ec2-a93d-11e7-89df-38c000672916.png)

**Comment by wmbutler** [comment]
- [ ] odd gap im my portfolio between bitUSD and open.BTC. Not sure what causes this.

![screen shot 2017-10-04 at 7 56 21 pm](https://user-images.githubusercontent.com/1254810/31206554-33329a52-a93e-11e7-971c-82ea36d29d75.png)

**Comment by wmbutler** [comment]
- [ ] Excessive right padding in this dropdown, Activity tab
- [ ] Reminder: move this to the TH replacing **OPERATION** text

![screen shot 2017-10-05 at 2 42 15 am](https://user-images.githubusercontent.com/1254810/31215879-f5a77eee-a976-11e7-98c4-0a112fbecb4f.png)

**Comment by svk31** [comment]
No idea what you mean by narrow fonts in the header.

I used to have n/a for unknown prices, but nobody understood what that meant so I changed it..

The gap in the portfolio is between assets you actually have and the default list of assets that are shown so you can easily buy or trade them, they're shortcuts basically.

**Comment by wmbutler** [comment]
- [ ] We need a price on the Portfolio page. Qty * Price = Value. If we have a value and a qty, it's really important that we include the price. This isn't really an optional field when a user is looking at their total assets.

**Comment by wmbutler** [comment]
- [ ] We have the call price listed but not the price on the margin screen. I agree we have the ratio, but it makes sense to include the price as well for the user. This would also allow the user to validate the **ratio** value.

![screen shot 2017-10-05 at 10 00 47 am](https://user-images.githubusercontent.com/1254810/31234501-a3a68322-a9b4-11e7-9f44-0ee986c0be0c.png)

**Comment by wmbutler** [comment]
The sort order on the open orders listing appears arbitrary. I think we need to pick something that will remain static if the user chooses to toggle the price. Either the order placement date or expiration date would suffice. I still feel that a visible date field is important here but at a minimum, we should let the default sort order be by date. I don't know whether it should be ascending or descending. I'd imagine this will eventually be a user selectable value.

![open_order_sort](https://user-images.githubusercontent.com/1254810/31264482-118ddd2a-aa2f-11e7-90e6-3bb559adfeb8.gif)

**Comment by svk31** [comment]
The sort order is by price, which is the only sorting that makes sense.

**Comment by wmbutler** [comment]
Hrmmm, open orders being sorted on price? I would think grouped by market and then date makes more sense.

**Comment by svk31** [comment]
By markets first, then price.

**Comment by wmbutler** [comment]
My fear is that when someone inverts the price, they will lose whatever row they might have been on  and may end up canceling the wrong order.

**Comment by svk31** [comment]
The market direction is persistent and consistent with your selection everywhere else, so I don't see why anyone would ever switch that direction more than once anyway.

**Comment by wmbutler** [comment]
- [ ] Total summary column should be aligned under Value

![screen shot 2017-10-06 at 8 14 05 am](https://user-images.githubusercontent.com/1254810/31279352-645c7068-aa6e-11e7-8b1c-ef4d37d66902.png)

**Comment by svk31** [comment]
Sorting by price makes it look similar to a vertical orderbook, which at least to me makes a lot of sense..

**Comment by wmbutler** [comment]
- [ ] Anytime displayed currency is the same as the bitasset, we should display a 1 for the price.

![screen shot 2017-10-08 at 12 46 05 pm](https://user-images.githubusercontent.com/1254810/31319336-f5a69102-ac26-11e7-973c-06afe0f1a8b1.png)

**Comment by wmbutler** [comment]
- [ ] If user has any potential margin call issues, match color of dollar value in header to most vulnerable position.

Current

![screen shot 2017-10-08 at 1 48 13 pm](https://user-images.githubusercontent.com/1254810/31319916-60321172-ac31-11e7-8960-86fb45daedd5.png)

Expected

![screen shot 2017-10-08 at 2 04 04 pm](https://user-images.githubusercontent.com/1254810/31319930-9ac574be-ac31-11e7-91fb-2f628f0f469b.png)

**Comment by svk31** [comment]
I think this is about ready now, it's also taken a lot more time than the original estimate, at least 3 full days or 24 hours.

**Comment by wmbutler** [comment]
I figured!

**Comment by tbone-bts** [comment]
In a portfolio view, it makes the most sense for your largest positions to be at the top, smallest at the bottom.  So sorting descending by Value (not by Price) would really be best here.

>Sorting by price makes it look similar to a vertical orderbook, which at least to me makes a lot of sense..

**Comment by wmbutler** [comment]
@tbone-bts we are cutting off the features for now. This falls under sort order. Open a separate issue for allowing sortby. Thanks.

**Comment by svk31** [comment]
We were talking about open orders, not the portfolio.

I agree it makes sense to sort the portfolio by value of the holdings, I'll have a look to see how difficult it would be to implement.

**Comment by tbone-bts** [comment]
Ah ok, your comment was directly after a post with an image of the Portfolio table.  Threw me off.  But thanks for clarifying!

**Comment by svk31** [comment]
Merged
