### ISSUE TITLE
Limit Buy and sell, loss and stop triggers

### ISSUE THREAD

**Issue by georgygv** [bitshares/bitshares-ui#406]
The title says it all.

**Comment by wmbutler** [comment]
This items needs technical discussion. I don't think the core allows for this. @xeroc can you chime in on this since it's technically over my head regarding what is possible with the core?

**Comment by svk31** [comment]
Limit orders are the default orders in bitshares. Stop-loss triggers are not available and would need to be added to bitshares-core first.

**Comment by wmbutler** [comment]
Thanks. @georgygv feel free to post over at: https://github.com/bitshares/bitshares-core

**Comment by georgygv** [comment]
Ok, thanks.

**Comment by o5j5vg55bv5hv5j5f8799f9** [comment]
This doesn't have to be [core change](https://github.com/bitshares/bitshares-core/issues/456). In fact, it would be safer for protocol to have this done on UI level by simply executing buy/sell command at specific price. It would require keeping UI open, but pose no consensus risks.

I think it's extremely dangerous to have publicly visible stops. This would hide them.

Due to liquidity of the dex the stops would ideally have a time parameter that for a stop-sell order would check that current price is below X for Y seconds/minutes and then execute the order to sell Z amount at price W.

It would have to ignore dust amounts probably.

It would have to also check that UI won't time out lock and get approval from user when placed, just not broadcast.

It's a major trading feature that could be done without hard fork on much faster time scale.
