### ISSUE TITLE
GUI Homepage bitCNY-BTS Trading  should reverse to BTS-BitCNY

### ISSUE THREAD

**Issue by todasun** [bitshares/bitshares-ui#413]
![image](https://user-images.githubusercontent.com/10720816/30509082-c7e6ce5c-9ad9-11e7-8d9e-2ee91d3e6267.png)
BTS-BitCNY  same as  BTS-bitUSD

Sort by trading  volume   BTS-bitCNY should be at the first place
or when choose chinese language   BTS-bitCNY should be at the first place

**Comment by todasun** [comment]
![image](https://user-images.githubusercontent.com/10720816/30509108-ab833222-9ada-11e7-9037-21087229c556.png)
default  bitCNY-bts 
It's very inconvenient. Click reverse every time！！！！！！！！！！！！！！

**Comment by svk31** [comment]
When I first added this pair it was the other way around, but I got requests from Chinese people to change it because the current direction was apparently the most commonly used.

**Comment by todasun** [comment]
in hellobts wechat &qq group  we all like   BTS-bitCNY   not  bitCNY-BTS as default

**Comment by landry314** [comment]
Sort by volume makes sense to me as that is the default (initial) sort in the My Markets list and the most useful sort as well, at least until the DEX is the number one trading exchange in the world and all the pairs have high volume ;-)

**Comment by Ashaman-** [comment]
What would really be nice, is if there direction of pairs both on listings, and in places like margin call prices, was configurable by the user. Then the fact that we have groups of users with opposite preferences would cease to be an issue.

**Comment by wmbutler** [comment]
The Top Markets shouldn't really be preference based. We should have standard rules for this, like BTS is always first or BTS is always last. It should be consistent. I think that a view of the portfolio / holdings view should be where users can set the pair orientation.

**Comment by todasun** [comment]
how about  users can define the homepage  by themselves？
if some only need BTS-BitCNY BTS-bitUSD  BitUSD-BitCNY  three pairs？

**Comment by abitmore** [comment]
> We should have standard rules for this, like BTS is always first or BTS is always last.

I disagree. For some assets like OBITS and PPY it's better to use OBITS/BTS and PPY/BTS, but for CNY/USD/BTC it's better to use BTS/CNY, BTS/USD and BTS/BTC.

**Comment by wmbutler** [comment]
But this is just a personal preference. Personal preferences don't really belong on broad market indicators. Don't you think it makes more sense to leave pref out of the market and let people set those details on the trading pairs they hold in their portfolio? Considering that we could have thousands of markets, it's asking a bit much.

**Comment by abitmore** [comment]
What I've said is "common sense". It's better to make the UI "easy to use". For example, in forex markets, there are "EUR/USD" and "USD/JPY", but not made USD always the first or last, because people have got used to them.

**Comment by abitmore** [comment]
Currently the "Top Markets" are our static selection only, there won't be thousands of pairs. If we want to make it dynamic, it's another feature. In that case, we can show the data with a pre-defined order, but still it's best if the UI can remember the direction the user has selected.

**Comment by tbone-bts** [comment]
I agree with @abitmore:  1) direction selected by user should be remembered, and 2) default direction should be based on "common sense" in order to best ensure ease-of-use, especially for new users.  This can be accomplished by simply creating an order of priority for the base asset:  

1. user's preferred fiat
2. other fiat (priority based on volume)
3. BTC
4. BTS
5. other assets (priority based on volume)

**Comment by wmbutler** [comment]
Considering tucking Markets into the Dashboard area (renamed from overview). This also contains a control to switch the pair. It stil contains the same information but presents it in a columnar format as well.

![screen shot 2017-09-19 at 4 35 26 pm](https://user-images.githubusercontent.com/1254810/30616653-9060ce2a-9d58-11e7-8aeb-2ea1f8fbb875.png)

**Comment by landry314** [comment]
beautiful!

**Comment by todasun** [comment]
at least  make  bts-bitcny  same as  bts-bitusd！！！！！！！！！！！！！！！！！！！！！！！

**Comment by o5j5vg55bv5hv5j5f8799f9** [comment]
top market specific pairing not as important as making it extremely super obvious and easy that the pairs can be flipped around with a single click on exchange page. often I just edit url instead of using interface because it's faster. If they are asking for it, it means they also don't know!

1. People literally do not know they can flip pairs
2. When they try to do it manually through navigation, they can't really choose direction either bc one side is fixed choices on my markets. Typing pairs in custom order is hidden in "find markets". I think top/bottom layout of text boxes there is also confusing as well as calling one box a currency and another box an asset. I always assumed wrongly base currency wasn't customizable b/c of different wording. Not sure naming them is even necessary at all. Finally, top/bottom design is confusing to know which is base and which is asset - left right better and in line with how it's displayed normally left to right asset1:asset2.

Solutions I've mentioned before:

1. There should be an obvious button or symbol added that you can rotate order of pairs (not just mystery clicking on blue text) in top left.
2. Selecting pairs in [find markets] should be moved to same tab as my markets and use as filters. Layout should be left and right instead of top and bottom with a ":" in the middle. Rotation button here too won't hurt. Bad drawing of what it might look like https://i.imgur.com/34cUquv.png

**Comment by abitmore** [comment]
> Considering tucking Markets into the Dashboard area (renamed from overview). This also contains a control to switch the pair. It still contains the same information but presents it in a columnar format as well.

@wmbutler imho although your approach is good, it's out of this issue's scope, perhaps we can discuss it in a new ticket. This issue is asking for a simple change, which is a low-hanging fruit. We don't need to discuss such a simple change for 15 days before make a decision.

@svk31 no matter who suggested to show bitCNY:BTS as the default pair in the past, I think the best UX / common sense has changed now, as we have a much bigger user base now than before, and it's easier for us to get more users if we do things more "normally". We can see, the same user even created a duplicate issue, it means he noticed the inconvenience again but forgot that he had created an issue for it already, from his point of view this should have been fixed.

**Comment by todasun** [comment]
when too many users connect to the api server
enter the default  trading pairs  bitcny-bts  loading &loading
then  click to reverse   loading &loading again even always loading & need refresh（Increase the API server load ）

![image](https://user-images.githubusercontent.com/10720816/31048256-1ce16cfa-a64c-11e7-8c71-ea228d557d4e.png)

**Comment by landry314** [comment]
@todasun, Why not star your favorite pairs and then click "[_] Show * Only" at the top of My Markets in the EXCHANGE so you can have a quick way to find them?

I never use the Homepage/Dashboard. I just click on EXCHANGE then go to My Markets.

**Comment by tbone-bts** [comment]
It's clearly sensible for the default pair to be BTS : CNY (not CNY : BTS).  The fact that someone repeated this comment doesn't make it more right, but it does tell me we need to give people more confidence that such a sensible change like this WILL indeed be made ASAP.

**Comment by landry314** [comment]
When there is a FIAT in the pair, I always make it the quote currency (the second one), and I think this is pretty standard in cryptodom. People talk about BTC/USD which is how many USD there are PER ONE BTC. I look at BTS using BTS/CNY, how many CNY there are PER ONE BTS (about half a CNY unfortunately)...

Does anyone look at it the other way? Maybe a vote is needed on the telegram chat to figure this out?

It should default to the way most people use it for efficiency, we can all agree on that, right?
