### ISSUE TITLE
[1][svk] Withdraw modal displays incorrect fee

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#424]
Had a few complaints in Telegram of users unable to withdraw due to the fee being stuck in BTS value even though it should be in OPEN.BTC etc.

![image](https://user-images.githubusercontent.com/6890015/30606426-fe08c22a-9d71-11e7-90c8-8ebc9e2cc85a.png)

**Comment by wmbutler** [comment]
I was going to post this bug. Glad you picked it up.

**Comment by happyconcepts** [comment]
Is it really 0.22 Bitcoin fee to withdraw from OpenLedger? That is a $80
USD minimum fee to withdraw at current prices...

On Sep 19, 2017 12:36 PM, "Bill Butler" <notifications@github.com> wrote:

I was going to post this bug. Glad you picked it up.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bitshares/bitshares-ui/issues/424#issuecomment-330650079>,
or mute the thread

**Comment by svk31** [comment]
That is an example of the bug...
