### ISSUE TITLE
"Trading Overview" mixes up trading pair prices

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#441]
The Trading Overview mixes up the price/volume for the trading pairs.

### Trading Overview
![bitshares-tradingoverview-issue](https://user-images.githubusercontent.com/12114550/30776833-1fab721c-a0ae-11e7-8410-210932e17d0d.PNG)

### Market Trading Overview
![bitshares-tradingoverview-marketreal](https://user-images.githubusercontent.com/12114550/30776834-1fadd55c-a0ae-11e7-8f37-d5333326527b.PNG)

**Comment by svk31** [comment]
This was fixed in https://github.com/bitshares/bitshares-ui/issues/415

![image](https://user-images.githubusercontent.com/6890015/30780513-b12ee08a-a10c-11e7-9a5e-d7d493e30393.png)

![image](https://user-images.githubusercontent.com/6890015/30780509-9ac377de-a10c-11e7-8fa3-fac8b84da246.png)

![image](https://user-images.githubusercontent.com/6890015/30780515-c3bbfef4-a10c-11e7-9cb3-7f87e3701b1a.png)
![image](https://user-images.githubusercontent.com/6890015/30780519-d3412426-a10c-11e7-947f-da9681bf83b4.png)
