### ISSUE TITLE
[2] Hover state + click toggle for identcon/qr code

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#488]
Clicking on the user avatar should toggle it to a QR code. This preference should be remembered in localstorage. This is a convenient way to implement qr codes without a rewrite. Easy win.

![screen shot 2017-10-02 at 9 48 18 am](https://user-images.githubusercontent.com/1254810/31083434-496d927e-a757-11e7-9e11-474d62771d00.png)

![screen shot 2017-10-02 at 9 53 19 am](https://user-images.githubusercontent.com/1254810/31083560-9f2f6426-a757-11e7-9ce4-e1d83681ba7f.png)

**Comment by abitmore** [comment]
May need to let people know that picture is clickable. What's that QR code for?

**Comment by wmbutler** [comment]
The QR code would allow other bts users to send to that address by using a QR code reader. The next step will be to add send functionality into the wallet. Have you never used QR codes for sending/receiving crypto currencies?

**Comment by svk31** [comment]
I think the original feature that was requested was QR codes for private keys.

**Comment by wmbutler** [comment]
I'm still planning to UX that #444 This is my separate request because it will help people understand that their username is an address. It will also make it easy for users to show an adjacent user their deposit address on mobile once we get qr code scanning in place.

**Comment by btsfav** [comment]
QR codes for Privkey, pubkey and user name are all needed however

**Comment by abitmore** [comment]
Yes, this would be useful when we have a mobile wallet that can do "scan to pay". But I prefer UX like this (show another QR image so people will know to click):
![image](https://user-images.githubusercontent.com/9946777/31098059-b6854bd0-a7c1-11e7-9c1d-958da43eaac5.png)

**Comment by wmbutler** [comment]
@btsfav don't mix issue please. See #444 

@abitmore my reservation with this is that you are showing a QR code that might be too small resolution to act upon (for those users who don't realize they can click on it. Let me take another shot at a more obvious UX.

**Comment by wmbutler** [comment]
Question: Are these other symbols used for anything? Why don't we just replace them with a QR code based on the account name?

**Comment by svk31** [comment]
They serve as uniqueness identifiers, helping differentiate accounts with similar names. The identicons for account1 and account2 will look very different.

**Comment by wmbutler** [comment]
Although the color schemes of the identicons change with theme. Does anyone have their identicon memorized? Maybe my mind just doesn't work like this.

**Comment by wmbutler** [comment]
Proposed behavior:

Identicon is visible. When user hovers mouse over identicon, it changes to the qr code. A click displays the qr code permanently. Conversely, hovering over the qr code displays the identicon. A click displays the identicon permanently. 

![qr](https://user-images.githubusercontent.com/1254810/31309905-d1887e58-ab53-11e7-8128-234699278780.gif)

**Comment by abitmore** [comment]
> Remove the user#. This may cause a user to think that they need to send to the number rather than the account name.

I think it's better to leave the ID/number somewhere on the UI. We have many tutorials that tells people to re-check whether the ID/number is correct when making transfers. Also on the transfer page there is an ID/number.

**Comment by wmbutler** [comment]
Until someone tried to use that as their inbound address. Ambiguity is not out friend.

**Comment by tbone-bts** [comment]
I think it will be confusing for many users if you have a "Deposit BTS" button that does nothing but change the identicon to a QR code.  They may not even realize anything changed and may think the button is dead (perhaps after clicking it a couple more times) and wonder why depositing BTS is disabled.  

I also don't think having the identicon switch to a QR code won't really accomplish much (except for mobile use).  Since the problem we're having is that people don't realize their account name is their wallet address for depositing BTS, the little note saying "Your account name is your deposit address!" might help a bit.  But I think there are ways to have a much bigger impact, like switching to a simple Poloniex-style Deposit/Withdraw page.

**Comment by o5j5vg55bv5hv5j5f8799f9** [comment]
I think it's best to have the actual words QR code to give indication it's available if you click on it. Guessing without visual clues is difficult. abitmore design is best. 

(I do like the idea of Receive tab next to Send tab instead of Deposit BTS. Confusion between send/receive and deposit/withdraw is in part due to the fact users don't understand this is a separate blockchain and how its names/addresses work. )

**Comment by wmbutler** [comment]
Wow. No words. You are saying that Deposit BTS is not clear enough? They are literally the two words uttered by almost every new user in the telegram chat room right now.

**Comment by tbone-bts** [comment]
I understand you're looking for a quick and dirty solution, but I think this particular idea needs to be more thought out, especially since there's so much going on there in the upper left corner.  Not to mention, is the side menu even going to stick around?  

There's another relatively quick solution that I think will be far more effective.  Why don't you take @o5j5vg55bv5hv5j5f8799f9's persistent suggestion to create tabs on the Deposit/Withdraw page?  The tabs can be labeled BTS and Other with BTS showing as default.  Under Other you can put exactly what's currently already on the Deposit/Withdraw page.  And under BTS you give user choice between Deposit and Withdrawal, with Deposit showing by default and showing instructions on how to deposit to your account name etc.  Under deposit you can just have a copy of the Transfer form, or even just a link to existing Transfer form.  

This would avoid a LOT of confusion while the most elegant solution possible can be developed.   Or maybe we'll even find that this really does the trick well enough.

**Comment by wmbutler** [comment]
Because the deposit/withdraw area needs a ton of work and it's going to take until at least 1101 to get that put in place properly.

**Comment by tbone-bts** [comment]
I'm talking about an interim but impactful quick fix.  Are you saying the simple tabs I suggested for that purpose would be a ton of work?  Or are you referring to a more comprehensive solution?

**Comment by wmbutler** [comment]
Yes, that's what I'm saying.

**Comment by abitmore** [comment]
>From Bill: It's still here:
>![screen shot 2017-10-10 at 2 46 29 pm](https://user-images.githubusercontent.com/1254810/31407298-1348576e-adca-11e7-8649-aef7643484c5.png)

Correct. Please be aware the number shows on the "to" field is much more important than that one on the "from" field. If the number got removed from the account page, the number showing here will make no sense, because people may be unable to understand why it's here and unable to check whether she is sending funds to a correct address. 

> Until someone tries to use that as their inbound address. Ambiguity is not our friend.

Actually if the GUI was showing the underlying ID "1.2.21594" but not changed it to "#21594", we won't have this issue at the first place. Because CLI (which exchanges are playing with) works well with transfers to both ID and name, but doesn't work with a number. But now many people have got used to the number, and is using it heavily, so not good to simply remove it.

**Comment by wmbutler** [comment]
> Please be aware the number shows on the "to" field is much more important 

It's still on the To field as well

> But now many people have got used to the number

Many people? Like who? We are trying to make life easier for the masses here. In all the support chats I'm in, nobody ever talks about the user id. I agree, we can leave it on the transfer screen. My point is, I'm not proposing to remove the number from the sidebar (at least not yet).

**Comment by abitmore** [comment]
> Many people? Like who?

Every tutorial in Chinese emphasize it. In Wechat/QQ groups, when someone made a wrong transfer, others will tell him "when making a transfer, check the name and the number and the icon".

**Comment by abitmore** [comment]
If we have #557, we don't need a QR code here.

**Comment by wmbutler** [comment]
We won't have #557 for at least 3 more weeks. I still think it's worthwhile to get this into place to deal with the endless stream of support issues.

**Comment by svk31** [comment]
I think this works quite well in the end, the hover toggle makes it very likely that you'll notice it, the big DEPOSIT BTS button is clearly visible, and the account name flashes when you click it.

**Comment by tbone-bts** [comment]
I'm eager to see it.  I was just writing a post saying I'm concerned it will be more confusing now than it was before.  I mean, it's **already** not clear that "Send To" refers to the account name that is showing and that it can be an account name other than your own.  I doubt most people even realize how to get another account name to show up there, which makes the Send To more perplexing those people.  And now we're adding a Deposit BTS button that will take action **not** on the selected account as the Send To button does, but instead on the account you're logged into?  Unless I'm missing something, that's going to confuse people even more.

**Comment by wmbutler** [comment]
But this issue has nothing to do with the Send To button.

**Comment by wmbutler** [comment]
@svk31 Not trying to micromanage this, but can you speed the animation up to 1/4 second? I think it will catch the user's eye more each time they click. The animation feels slow.

![deposit](https://user-images.githubusercontent.com/1254810/31506422-00f56092-af3d-11e7-80e6-40e9125dbd7d.gif)

**Comment by svk31** [comment]
Sure. I'm all for removing the "send to"  button btw, I always found it useless.

**Comment by abitmore** [comment]
> Sure. I'm all for removing the "send to" button btw, I always found it useless.

On the opposite, I've always liked it.. especially when there was that #473 bug, clicking "send to" is the safest way to avoid fund loss.

**Comment by btsfav** [comment]
I use the send to button :(

**Comment by abitmore** [comment]
I think we can merge the "deposit" and "send to" button. When showing your own account, show "deposit" button and text "your deposit address is your account name"; when showing other's account, show "send to" or "pay" button and text "this is not your account" etc. Both can have QR code.

**Comment by wmbutler** [comment]
Send and deposit are opposite functions. This needs to be thought through carefully (but not on this thread). The end result of a send operation is that value leaves your account, while the end result of a deposit operation is that money arrives into your account.

**Comment by svk31** [comment]
Closing since the original issue has been completed, including the increased flash animation speed. We can start a new discussion about the utility of the buttons once we've seen them in action.
