### ISSUE TITLE
[7] Show status of all API servers?

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#49]
_From @abitmore on March 15, 2016 22:16_

Show status of all API servers on init-error page and/or config page and/or a dedicated page? Status includes: 

- up/down
- latency
- ~~load~~
- location
- ~~description~~

So user can select fastest server, or maybe eventually auto-select.

Related to #770. 

_Copied from original issue: cryptonomex/graphene-ui#784_

**Comment by svk31** [comment]
_From @btswolf on April 5, 2016 21:0_

GUI should ask automatically (timeout) to switch API connection after lost connection/blockchain sync problems.

**Comment by wmbutler** [comment]
I'll UX this first.

**Comment by wmbutler** [comment]
![screen shot 2017-08-14 at 12 33 04 pm](https://user-images.githubusercontent.com/1254810/29283527-c35530ba-80ec-11e7-89d1-70ec11726aa9.png)

**Comment by wmbutler** [comment]
Key for colors based upon latency

![screen shot 2017-08-14 at 12 38 33 pm](https://user-images.githubusercontent.com/1254810/29283722-8398fbb8-80ed-11e7-9851-276cead9ec26.png)

**Comment by wmbutler** [comment]
- Placeholder text for both input fields.
- Validation for ws:// and wss:// in address field

![screen shot 2017-08-14 at 12 52 31 pm](https://user-images.githubusercontent.com/1254810/29284242-7ce30424-80ef-11e7-98a8-b7cb428df779.png)

**Comment by wmbutler** [comment]
Modal for node removal

![screen shot 2017-08-14 at 1 36 33 pm](https://user-images.githubusercontent.com/1254810/29285869-a3d7c618-80f5-11e7-893c-143cc79e7e2b.png)

**Comment by wmbutler** [comment]
@svk31 Is it possible for a node to be up and have low latency but for the socket to be down or out of sync? If so, I need to expand upon the latency and up/down status. I think if the node is out of sync, it may be wise to have a third indicator, but I'm not sure what it would be called or how we would test for an out of sync node.

**Comment by calvinfroedge** [comment]
![issue-49](https://user-images.githubusercontent.com/632938/29425866-68a2aef8-834a-11e7-8188-1186ddc52eb8.gif)

[Pull request 278](https://github.com/bitshares/bitshares-ui/pull/278) has been added to address this issue. One thing to note is that when the user sets "Choose closest server automatically", that is shown as the active node rather than the node actually in use.  Will need to dig further into the code (and increase the estimate) to resolve that.

It may also be necessary to modify the mechanism used to establish latency for various servers.

Note that translations will need to be implemented for other languages. Also, some servers which appear by default do not have a status. Perhaps we need to change our logic for querying them, and if they are actually down permanently, remove them from the defaults

**Comment by ThomasFreedman** [comment]
I like the direction these changes are heading.

Where does the location info come from, the IP address? Compiled into the binary? Although I have a public, load balanced API server running I haven't added it with a PR (if that is the way it *should* be added) so I am not sure what info is required. 

One consideration is not to be too specific but rather limit location to a regional description. We need to start putting more thought in protecting the location of seed and witness servers and it's not clear to me the community thinks about that as much as we did 2 years ago.

**Comment by wmbutler** [comment]
Thanks for your comments but please open a separate ticket for specific changes.

**Comment by ThomasFreedman** [comment]
Yeah, I am unclear where you want things. I was trying to comment on this specific UI change (better info to users for connections). This issue is for such changes is it not? How are my comments out of place?

Trying to contribute, not hinder you. What is a "ticket", is it not an "issue" here on github?  Is this very page I'm interacting with not a "ticket"? A separate item (ticket / issue whatever) potentially changes the focus away from this specific topic, a facet of which I want to make a comment about (dynamic info location and where that comes from).

I see in the Telegram DEX channel you encourage people to use github and be explicit about changes. Perhaps a basic project readme that describes the methodology of the project will help people with similar (confusion) about how you have things organized. I thought my understanding was OK but perhaps not. Please set me straight if so.

**Comment by calvinfroedge** [comment]
@wmbutler @svk31 The existing PR was extended to include showing the active node when the server is automatically selected.

[Issue 110](https://github.com/bitshares/bitshares-ui/issues/110) was updated as appropriate.

**Comment by wmbutler** [comment]
@thomasfreedman his ticket has already been claimed, worked and closed. Your suggestions were expanding scope on an item that has already been completed. Open a new issue if you require additional scope.

**Comment by wmbutler** [comment]
- [ ] Sort order should be ascending latency
- [ ] Make sure down nodes are sorted to the bottom
- [ ] Remove Button is only visible on nodes the user **manually added**

@calvinfroedge you missed a few bullet points on this one... increase the estimate as you see fit.

**Comment by ThomasFreedman** [comment]
Thanks BB, noted for future issues.

**Comment by calvinfroedge** [comment]
@wmbutler 
![issue-49-ex](https://user-images.githubusercontent.com/632938/29743049-6ec7c9c4-8a4f-11e7-81fd-b6887049c9a5.gif)

Resolved by [PR 329](https://github.com/bitshares/bitshares-ui/pull/329)

**Comment by wmbutler** [comment]
Nice, @calvinfroedge thanks.
