### ISSUE TITLE
Pricing in order confirmation window

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#51]
_From @abitmore on March 18, 2016 21:37_

https://bitsharestalk.org/index.php/topic,21961.msg192149.html

Copy & paste here:

Another UI fix would be to adjust the price in the order confirmation windows to be quoted in the same asset base as the market. For instance, we can view any of the markets in either ASSET-BTS or BTS-ASSET --i prefer using ASSET-BTS to normalize them all to a BTS base; however, even when i'm viewing the market as ASSET-BTS, for some markets (e.g. BTS-BTC) automatically show the BTS-ASSET price in the trade confirmation window. This is confusing and sometimes leads me to post trades at the wrong price bc sometimes the automatic fill in the Buy/Sell windows reverts to the the last trade. 

A good fix would be to ensure the confirmation window posts the quote in the same base unit as the market we're trading.

_Copied from original issue: cryptonomex/graphene-ui#789_

**Comment by wmbutler** [comment]
This brings up the issue of the last trade being populated after the trade. We should clear the values after the trade. This issue needs more discussion and clarification.

**Comment by happyconcepts** [comment]
This is a trade confirmation window.
The dex is supposed to be an Exchange. 

Lets please stay focused on the issue because it is very bad UX to force a confirm of the user's input back to them in a different unit. I am amazed that I must point this out. Instead this gets conflated with sticky form inputs ... and pushed back as a request instead of elevated as a bug.
