### ISSUE TITLE
[.25] Lastpass doesn't recognize password field during account creation

### ISSUE THREAD

**Issue by o5j5vg55bv5hv5j5f8799f9** [bitshares/bitshares-ui#527]
I noticed that very popular password manager Lastpass fails to save the password during account generation.

I just tested it, pop up appears, it saves name, but not password - that field is recorded as blank but wouldn't know unless you look at more detail when you see lastpass add window pop up.

I assume the field is missing an internal name that's standard to passwords? Perhaps that can be addressed as I have noticed at least a few people get burnt by it. 

I assume some other password managers might benefit from this as well.

In general I think the fact people aren't writing down their passwords better is because they don't understand they are effectively private keys like on bitcoin perhaps.

**Comment by wmbutler** [comment]
https://lastpass.com/support.php?cmd=showfaq&id=3385

**Comment by wmbutler** [comment]
Related to #258

**Comment by svk31** [comment]
Tbh I think using Lastpass here is a terrible idea since it means all people need to hack your account is get access to your computer, since unless I'm mistaken Lastpass just autopopulates password fields without even requiring a pin code? Chrome autocomplete is the same..

Probably the reason why Lastpass isn't working correctly is because of the commit I made to fix this issue: https://github.com/bitshares/bitshares-ui/issues/403.

The issue there was that Chrome often autopopulates the password field while you're typing your own password, without you even noticing it, which makes people type the wrong password. Unfortunately Chrome (or any browser) makes it very difficult or even impossible to disable password input detection..

**Comment by svk31** [comment]
Well I suppose it's better than people losing their passwords which also seems to happen all the time.

**Comment by svk31** [comment]
I assume the above will fix the issue.
