### ISSUE TITLE
[.5][mattbeckman] Leading Decimal fails

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#594]
It is not possible to type a number with a leading decimal unless the user first types a 0. It should be possible to start typing a number with a decimal. Please check numeric entry fields in all areas of the application.

![leading_decimal](https://user-images.githubusercontent.com/1254810/31616250-d1d67090-b251-11e7-9c38-1f9c3b66c04f.gif)

**Comment by mattbeckman** [comment]
I haven't previously contributed, but I'm interested in handling this one. Currently, I'm a full time node dev on an agile team in California, and I've been a fan of BitShares since the PTS was the thing.

**Comment by landry314** [comment]
Yes, I noticed this and commented in this closed issue #390, which I believe is related.

In the future, should I not comment in closed issues if the bug is just a continuation of an old bug which wasn't fully solved? I am trying to not create duplicate issues but commenting in closed issue threads seems to go unnoticed.

**Comment by mattbeckman** [comment]
PR #601 includes the fix. I opted to have it prepend "0" when typing a decimal point on an empty field, as that felt more natural, and it a helps avoid a potential NaN decimal point situation.

**Comment by wmbutler** [comment]
@mattbeckman Thanks for the PR. Please be sure to test as many edge cases as you can while you are at it. @landry314 I prefer more tiny issues over one issue with a lot of small fixes, ao yes, once an issue is closed, just make a new one.
