### ISSUE TITLE
[2] Web wallet errors

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#595]
Tried ZeroNet, 

![](https://i.imgur.com/OPGWlsO.png)

* is there a security reason why this is blocked and not working & could the wallet adopt better standards?
* is there a workaround?

**Comment by svk31** [comment]
The CSP directives are there to improve security. How does zeronet hosting work?

**Comment by abitmore** [comment]
By the way transwiser should be removed.

**Comment by wmbutler** [comment]
I think it's appropriate to open an issue for this.

**Comment by btsfav** [comment]
@Hellozeronet maybe you can join the conversation?

**Comment by HelloZeroNet** [comment]
Can you please send me the site's address?

**Comment by btsfav** [comment]
@HelloZeroNet trying to host https://github.com/bitshares/bitshares-ui/releases/download/2.0.171015/hash_history_dist_2.0.171015.zip - perhaps you could check? 

if not, I'll send you the adr later :)

thanks!

**Comment by btsfav** [comment]
bump. new wallet gives out less errors, but still...

![](https://i.imgur.com/FNYoMiI.png)

**Comment by btsfav** [comment]
current errors:

![image](https://user-images.githubusercontent.com/15261692/41119287-bf6033ac-6a92-11e8-806c-4ad59be1c005.png)

**Comment by ety001** [comment]
Because of ZeroNet using 127.0.0.1:43110 as its host url, We can add http://127.0.0.1:43110 to the CSP meta config.
But this will bring another secure issue. 
All of sites on ZeroNet display in a sandboxed iframe. If we set http://127.0.0.1:43110 in the CSP, it may have a chance to load another sites' scripts.
Also the sandboxed iframe has banned the localStorage and cookies which are needed by Bitshares UI.
So I think this is not a bug.

**Comment by clockworkgr** [comment]
I don't think it's possible to host the wallet on zeronet as currently designed.

Seeing as we HAVE a standalone local client, I don't think that's much of an issue. Being able to access API nodes via TOR combined with light wallet client would be even better.
