### ISSUE TITLE
Fixed Active Node in Access Section

### ISSUE THREAD

**Issue by magicstone1412** [bitshares/bitshares-ui#609]
Today I placed some orders on DEX. But after click Confirm button and wait a sec. It says that "Failed to broadcast the transaction" ( see the below photo). I changed from Hong Kong wss://openledger.hk/ws (Medium latency) to Dallas, USA wss://dexnode.net/ws (High latency), it did the broadcast successfully even though that node is in High latency. But when I refreshed the site, it turned back to Hong Kong wss://openledger.hk/ws, the broacast problem happened again. (because it is closest location)

I would like to propose a  "Fixed Active Node" option in Access Section to avoid "Choose closest automatically" happed. Thanks
![Broadcast Problem](https://imgur.com/ctlqoFA.jpg)

**Comment by svk31** [comment]
This is exactly what already happens when you set a specific node in the settings.

__However__, if you fail to connect to that node within 5s, it will fall back to known working nodes by order of their latency, and it will replace the node you selected in the settings with the node it finally manages to connect to, so that next time it will use the same one.

Most likely your problem is one of having a bad latency connection, which means it ends up trying fallback nodes on a regular basis.

**Comment by svk31** [comment]
You can, that's what you do when you pick a node. But if that node fails to connect properly, the GUI falls back to a working node.

**Comment by magicstone1412** [comment]
I would like to ask you to reopen this issue. I live in Vietnam, Openledger node in Hong Kong always causes the above trouble. Can we ignore that node in case I dont want it to fall back as default when opening browser? 

I have also informed openledger the problem. But I think they are not willing to fix at this time. Thank you
