### ISSUE TITLE
[10] New Header and Right Menu

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#630]
11/15 Milestone

- [x] Accounts is the currently selected item
- [x] Blue lock displayed when user is logged out
- [x] Login / Logout is toggled in position 1 depending on login/logout state
- [ ] Send Deposit Withdraw grouped with separator (each calls the appropriate modal)
- [x] Support goes to `/help` endpoint
- [x] Vote brings up witness/committee/wp screen
- [x] Upgrade brings up Membership screen
- Advanced still needs to be thought through but we have time.
- [x] Accounts goes to account list (the list below the markets on the current wallet)
- [x] Starred accounts are listed under accounts for quick switcher

![screen shot 2017-10-25 at 8 24 21 am](https://user-images.githubusercontent.com/1254810/32000968-f159b2fc-b95d-11e7-8951-96ca3b2e0eb0.png)

**Comment by wmbutler** [comment]
- [ ] Added Explorer menu. This can contain a dropdown with:
  - Blockchain
  - Assets
  - Accounts
  - Witnesses
  - Committee Members
  - Markets
  - Fee Schedule

**Comment by svk31** [comment]
What happened to the left menu under Account?

**Comment by wmbutler** [comment]
My thinking here is that the left menu presents a pretty huge waste of horizontal space, which it really precious especially on small devices. I'd like to take those various controls and place them in the top right dropdown menu instead. Here is an overall look at the proposition:

> I also made some width changes on the new tables to remove the excess gaps. I think it looks a lot cleaner and I hope you feel the same way.

Old

![screen shot 2017-11-04 at 11 15 00 pm](https://user-images.githubusercontent.com/1254810/32411919-03bf2e44-c1b6-11e7-93d4-8e72d0af3838.png)


New

![screen shot 2017-11-04 at 11 11 39 pm](https://user-images.githubusercontent.com/1254810/32411902-8ca10954-c1b5-11e7-99d2-0c300a76c206.png)

**Comment by svk31** [comment]
Removing the grey background kinda makes sense for the account page, but are you also implying that the background should be black everywhere else?

**Comment by svk31** [comment]
And what about really wide screens? Black everywhere?

![image](https://user-images.githubusercontent.com/6890015/33110562-f1f586b8-cf48-11e7-9196-33c12f6ca3a4.png)

**Comment by diogo-gomes** [comment]
I like the concept of the new menu but can you try a fade in menu from the right instead of the drop-down?
With full height will be more "inside" the app than a "popup" menu.

**Comment by wmbutler** [comment]
I think even for a really wide screen, it should stretch the full width.

**Comment by diogo-gomes** [comment]
I like the concept of the new menu but it can be more than a popup menu.

### Right Menu: Can you try a slide menu with full height from the right?
[This](http://git.blivesta.com/drawer/) is a random example.

**Pros of slide menu with full height:**

- menu more integrated in the application
- more space for menu content (ex: user image and qr code from actual left menu can be incorporated)
- easily to adapt to any resolution (extra small, small, normal and large)
- easy to fix the issue of wide screens (@svk31): The slide/side menu can start open in wide/large screens with option to be closed by user.

***Note:*** Some developers like to push the main content to the left when slide menu opens, other like the slide menu overlaid. It's your choice because I don't see any UX problems in any of this cases.

---

### Menu header

**I read some comments saying that people don't like the exchange in the default.** (I know that @wmbutler agree with this).

I may have a simple solution to this in regard to this screenshot. Why we don't change de **Dashboard** word to **Wallet**.
Currently the word Dashboard can be interpreted like a dashboard of an exchange. If we change to Account makes different sections/features of all Bitshares project and not only the exchange.

**The settings can go to the right menu**
The settings can go to the right menu because it's just a configuration area and not a feature.

**Missing the send feature**
I think that we should make the *Send* feature of Bitshares more relevant and put it in the Menu header.
Some users may want to use Bitshares only for remittance (send and receive money) - [Bitspark](https://bitspark.io) use case.

---

### Blue lock
In really don't know about this. The blue bring a lot of attention and can be misunderstood that it is needed an action from the user.
I think in green and red or blue for active/unlocked but it can be misunderstood with secure/insecure.

The only way that occurs me it's change the concept of login/logout to secure/insecure.

***Note:*** This lock colour issue it's a really hard one. Maybe only possible to solve with some inquiry with the community and users to know what the colours or symbols mean for them about login/logout and security.

**Comment by wmbutler** [comment]
## Right Menu
I think you are just asking for a drawer instead of a Menu. This would help with people who have a lot of accounts starred.

http://www.material-ui.com/#/components/drawer

## Menu Header

- Dashboard can't be Wallet. Wallets are very different. Wallets can contain multiple accounts and a single account has a Dashboard which displays all financial components.
- Settings are relevant across an entire Wallet regardless of which account is selected. That's why it's accessible from the header.
- The exchange is a showcase for Bitshares. That's why it has such prominent placement.
- If you put send at the top, it sets a precedent for placing Deposit/Withdraw there as well. I really don't think it's necessary since it's so easily accessible from the menu.
- That color blue is standard for the buttons. I'm not sold on it, but I think it's a color that works and is familiar to users.

**Comment by diogo-gomes** [comment]
> I think you are just asking for a drawer instead of a Menu

Yes, my mistake. I'm talking about replace pop-up menu with a drawer sliding from the right.

# 
> Dashboard can't be Wallet... Wallets can contain multiple accounts.

Okay, I never try multiple accounts. I thought that each account has its own wallet...

# 
> Settings are relevant across an entire Wallet

I understand your point and I'm okay with that but I don't agree in terms of general standards. Normally, the app configuration settings are under the main menu or are the main menu.

# 
> The exchange is a showcase for Bitshares. That's why it has such prominent placement.

I agree, I'm only try to please to users/developers that say that exchange it's only one feature of many.

# 
> If you put send at the top, it sets a precedent for placing Deposit/Withdraw there as well

Same answer. I agree, I'm only try to please to users/developers that say that exchange it's only one feature of many and bring more emphasis to remittance feature.

# 
> I'm not sold on it, but I think it's a color that works and is familiar to users.

It's really a difficult choice not because the blue but because the relation between logged out and unlocked.
**The grey (inactive button) can bring security issues for the users because the grey not bring the required attention to the users that the wallet/account is unlocked.**

**Comment by wmbutler** [comment]
One of the problems with gray for the lock is that people don't seem to realize they are locked out. This is partially due to the nature of the blockchain where a user is free to look at their account even when they aren't logged in.

**Comment by svk31** [comment]
I'm not far from completion on this issue, but I'm concerned about all the functionality being removed. Removing the left menu means no account qr code, no follow/deposit to/send buttons.

There's also no longer any easy access to Permissions, Signed messages, Whitelisting, Issued Assets. I'm guessing those will go under Advanced, but how exactly is that meant to work? Should clicking on Advanced take you to a new page with further links to those advanced functions? I suppose it could look similar to the Explore root page, with card links with big icons..

**Comment by xeroc** [comment]
Very nice mockup. May it be possible to have the list of accounts in that menu scrollable?
At least today, if you have more than 10 accounts or so in your wallet, you cannot select it from the menu because the drop down isn't scrollable and the height is bigger than the screen.

**Comment by svk31** [comment]
The scrolling was actually fixed in a PR a few days ago. This new drop-down is a custom component that also uses the scrolling fix for that PR so it can scroll as well.

**Comment by wmbutler** [comment]
> I'm not far from completion on this issue, but I'm concerned about all the functionality being removed. Removing the left menu means no account qr code, no follow/deposit to/send buttons.

- It was my intention for the "deposit" and "send" modals to be completed before this issue.
- Follow / Add Contact is definitely an issue that I haven't fully reconciled and may need some more time to reach a good solution. Other accounts can be searched from the send interface and from the account explorer interface. These are two logical places to include "Follow / Add Contact"
- Regarding Advanced, I think the easiest solution for now is to have a divider and put each "Advanced" subcategory in the menu.

Did you end up going with a drawer for the menu as suggested in this thread above?

**Comment by wmbutler** [comment]
Awesome progress. A few notes:

- [ ] Remove vertical gap between header menu and portfolio header
- [ ] Header hover/selected color should be the same color as the unselected state of the portfolio header.
- [ ] When the right header (menu) is not hovered or activated, it should match the black all the way across the header.

![screen shot 2017-12-02 at 2 48 11 pm](https://user-images.githubusercontent.com/1254810/33519619-de2dc990-d76f-11e7-8feb-e768fc2bd8cd.png)

**Comment by wmbutler** [comment]
- [ ] User should be able to click anywhere on right menu to activate it

![clcik_anywhere](https://user-images.githubusercontent.com/1254810/33566552-f6d1207e-d8e5-11e7-9afc-a2a8c9506bfc.gif)

**Comment by wmbutler** [comment]
- [ ] User should be able to click anywhere on the account name to activate it
- [ ] Optional: Menu should go away onMouseup. At present the menu stays activated until user clicks away.

![switch_account](https://user-images.githubusercontent.com/1254810/33583246-fa801962-d91e-11e7-8ce2-c7ca54935906.gif)

**Comment by svk31** [comment]
I personally hate menus that go away when you take the mouse away so I prefer to keep it this way. I added autoclose on selecting a new account though.
