### ISSUE TITLE
Market navigation on narrow screens/windows

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#638]
When using a narrow screen, like a phone, the market selection column on the right is not accessible unless you turn the screen around. This may not be an issue if you can turn the screen, but you may wish to run the screen in a narrow window on a desktop, and then you can't select a market.

A right hand toggle, or slide in on phones, would be a nice feature to enable this.

The right hand market table also eats up a lot of window size, making it less convenient to browse it in this layout except when making a market change. Making the market table work in the same "fly-out" fashion as the navigation menu does on the left could make this less of an issue.

To not conflict with the drop down menu in #630 we need to find a good place to put this without interfering.

**Comment by Xeldal** [comment]
I would love to see a side-bar of icons similar to the one in the following picture that would control the display of the various windows in the exchange screen. 

![](https://user-images.githubusercontent.com/6866501/31656443-dbf17e1e-b32b-11e7-874f-a74c1a8e920f.jpg)

I made a basic mockup a while ago with some ideas here:  https://bitsharestalk.org/index.php/topic,25071.new.html#new

This link shows I put the icons across the top but I think it's better on the side like the image above.  being able to add or remove all but the widows you want to see is great for desktop but it's almost essential for mobile.

**Comment by wmbutler** [comment]
@Xeldal your comment is more geared towards the #361 feature.

**Comment by Xeldal** [comment]
@wmbutler I don't think it has anything to do with the the item you referenced.  I'm not talking about tradingview, not talking about charts, or chart functions.  Nothing to do with charts package.  I'm talking about navigation for small screens, and general layout of the Exchange page.

**Comment by tbone-bts** [comment]
Having a side menu like the one on Tradingview is very tricky because you need to have good icons for each menu item, which is difficult enough, and you also need to have enough of them to run the whole length of the side from top to bottom. I honestly don't see that being feasible here.  

Although I do think it could work for the Explore items.  Just for reference, here's a mock-up I made months ago.  Although it's certainly not high priority, I created a new issue for it: https://github.com/bitshares/bitshares-ui/issues/647

![blockexplorer3](https://user-images.githubusercontent.com/15830348/31956291-f8700924-b8b8-11e7-885f-ebae097b7c8d.jpg)

**Comment by startailcoon** [comment]
Fixed in new market UX
