### ISSUE TITLE
[5.25][maiopirata] News Area

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#639]
Bitshares needs a news area within the wallet. This will allow users to stay in touch with what is going on with Bitshares within the wallet. It should draw its data from the bitshares steemit tag and contain:

- [ ] Line number
- [ ] Date posted (reverse chron)
- [ ] Subject (with ellipses if subject is too long for the td)
- [ ] Author (steemit author, for resteemed articles the author should be the original author)
- [ ] author or resteemed by bitshares.fdn

Clicking on the link will take users to the steemit frontend so we don't have to build an entire reader interface.

![screen shot 2017-10-23 at 3 42 58 pm](https://user-images.githubusercontent.com/1254810/31912253-e27eeab4-b808-11e7-8a2f-b3670073e008.png)

**Comment by startailcoon** [comment]
This is a nice feature to have. Would all posts related to the steemit tag be present in the wallet? This could present some unexpended security issues like phishing attacks. 

I think it should be limited to a number of authorized authors.

Depending on what resources that can be used, not sure if there are relevant APIs to use yet, this script could be of help for anyone looking at it. https://github.com/startailcoon/GridcoinResources/blob/master/fetchSteemitPosts.php

**Comment by btsfav** [comment]
needs moderation, else you risk /bitshares getting spammed with scam or shitcoins

**Comment by wmbutler** [comment]
I think the idea of accepted authors + bitshares tag would work. Maybe we can compile some names here.

- xeroc
- svk
- billbutler
- oxarbitrage

**Comment by abitmore** [comment]
Ask the foundation to create a dedicated account for the news, then only subscribe to a list of tags posted or resteemed by that account.

By the way, this feature depends on external API calls, e.g. calls to api.steemit.com, which could be unstable and need future maintenance work.

**Comment by maiopirata** [comment]
@wmbutler, I will be happy to try focus on this if nobody has taken it..

**Comment by svk31** [comment]
As long as we're only fetching post titles and not displaying the full post content ourselves (which would require markdown parsing) this should be fairly easy to implement, so go ahead @maiopirata.

I recommend adding https://github.com/steemit/steem-js in order to fetch data from Steem.

@wmbutler where should this actually go?

**Comment by wmbutler** [comment]
We should have a "News" area close to support in the dropdown.

![screen shot 2017-11-24 at 10 24 49 am](https://user-images.githubusercontent.com/1254810/33218306-c48a97bc-d101-11e7-9833-62c6226b4a5d.png)

**Comment by wmbutler** [comment]
@abitmore While agree that news should be professionally written, I think that by limiting to official authors and the bitshares tag, we will keep things manageable.

**Comment by maiopirata** [comment]
I've almost finished this, I will push a branch in the weekend.

Some questions:
- @wmbutler can we agree a list of users/tags for the first version? Right now I only have "bitshares.fdn" with no tags. It is suboptimal, maybe for some reason bitshares.fdn wants to publish something that is not included in the feed that appears in the wallet. This would be much more common for other authors. I propose that we have a special tag "bitshares-news" (or whatever) and a list of approved author.

- on the UI, after discussing with @svk31 I've done a /news endpoint, where I show the table of news. Only titles, and original author. I limit myself to 20 because it seems enough.

- Since we have all the metadata of any news we can easily develop a filter on the front that search words in the title or author or tags.. It is a bit too much if we think we have 20 news. It would be much better in case we decide to have a feed of 50 or 100 and show only the first 20.

**Comment by wmbutler** [comment]
- bitshares.fdn is specific enough that I don't think we need to restrict it to tags. Anything this account posts or **resteems** will be accepted.
- line, date, title, author reverse descending order.
- Save filter for a future enhancement.
- Most recent 20 articles by descending creation date will be fine. We can add pagination later.

**Comment by maiopirata** [comment]
Thanks, I have all I need!

**Comment by wmbutler** [comment]
Looking forward to seeing this.

**Comment by maiopirata** [comment]
#824 Ok I think we are close

**Comment by svk31** [comment]
Nice job so far! Here's a screenshot:

![image](https://user-images.githubusercontent.com/6890015/33717549-9f3c0a14-db5a-11e7-8ce1-4f8883c65637.png)

Some feedback:

- [ ] Format dates. @wmbutler any preference here?
- [ ] Translate any text strings. If you don't find the words already in locale-en, add them to a new "news" key. react-translate-component is what's used for translations
- [ ] I think we can make author names clickable as well

For the dates; you can use counterpart like this: `counterpart.localize(new Date(singleNews.active));`

The default format is like this: Tue, 5 Dec 2017 09:06

**Comment by wmbutler** [comment]
> Dates
- [ ] I like mm/dd/yy hh:mm pm. 
- [ ] Force the date to live on a single line (rather than splitting to 2 lines). 
- [ ] Ensure same font style and size as Dashboard.
- [ ] Truncate story subjects intelligently as browser is made smaller (Technical Issue...)

> Translate
Sounds like a plan

> Author clickable
Let's just make the entire row clickable and deliver the user to Steemit.com. Use the same hover state all the other tables (that haver state is getting added in an issue this sprint). I added two more hours to handle the truncation and general testing.

**Comment by svk31** [comment]
Of course you like mm/dd/yy, you're American ;) Like most Europeans (I assume) I don't, I prefer dd/mm/yy..

**Comment by maiopirata** [comment]
@wmbutler, @svk31 

- [x] Force the date to live on a single line (rather than splitting to 2 lines).
- [x] Ensure same font style and size as Dashboard.
- [x] Truncate story subjects intelligently as browser is made smaller (Technical Issue...)
- [x] Translate (I will add translation in other languages if you want)
- [x] Author clickable --> all line clickable

Big question: I changed the style of the whole table to be similar to the ones in Dashboard, it kind of makes more sense to me, if you prefer the original design I switch it.

Still to do:
- [ ] Dates: I'm really a noob in dates, but I will push something tomorrow... 
- [ ] Cleaning: Once we agree on the result I will clean all the duplicates and reuse more code..
- [ ] Testing: It is probably a very trivial component, I will put some proptypes check and see if it makes sense to unit test something
![fullsize](https://user-images.githubusercontent.com/5641811/33810979-4c73a470-de04-11e7-9602-3cc10ccd44f5.png)
![halfsize](https://user-images.githubusercontent.com/5641811/33810980-4c8c85da-de04-11e7-9e90-22e60f049ec8.png)

**Comment by svk31** [comment]
This looks great to me as is, if you can just do the following I'll merge it:

- [ ] Remove console logs
- [ ] Change all single quotes to double quotes
- [ ] Add trailing `;` to all lines where missing
- [ ] Remove unused variables (pageTitle)

**Comment by maiopirata** [comment]
- [x] Remove console logs
- [x] Change all single quotes to double quotes
- [x] Add trailing ; to all lines where missing
- [x] Remove unused variables (pageTitle)

done

**Comment by wmbutler** [comment]
I added .25 onto this. Can you do the following:

- Remove table borders
- Change vertical padding to more closely match Portfolio padding

**Comment by maiopirata** [comment]
#855 @wmbutler  here are the changes,
I've checked and it seems identical to the table in Portfolio with two different vertical padding for header (0.85rem) and body cells (0.5rem)

**Comment by maiopirata** [comment]
@wmbutler @svk31 
in case you need it, as shown in the pictures my account is: m1i0p1r1t1

**Comment by wmbutler** [comment]
Date sort order is off. Seems to be sorting somewhat randomly. This should be sorted in reverse chronological order.

**Comment by mattbeckman** [comment]
Does anyone else think we should drop the "Line" column?

**Comment by maiopirata** [comment]
@wmbutler Yes, I will force a date sort order...

@mattbeckman you are probably right, let's see if someone else agree.

**Comment by wmbutler** [comment]
I like line numbers. Keeps users from having to count it up if they are curious.

**Comment by startailcoon** [comment]
I see no point in having a line number. What should the user be curious about, how many lines there are?
