### ISSUE TITLE
[2][dot5enko] Improved "Explore" navigation

### ISSUE THREAD

**Issue by tbone-bts** [bitshares/bitshares-ui#647]
To "Explore" the Blockchain, Accounts, Markets, Assets, Fees, etc, you have to keep clicking back before clicking on the next one.  It would be nice if small icon buttons could be located along the side so the user can easily navigate from one to the next.  

This really isn't a high priority item, but a similar side navigation conversation came up in another issue and it reminded me of this mock-up I created months ago, so I thought i should put it out there as food for thought, and for reference.

![blockexplorer3](https://user-images.githubusercontent.com/15830348/31956771-75cf665c-b8ba-11e7-9aa1-75b03f57af19.jpg)

**Comment by wmbutler** [comment]
I think we can work this into the new menu navigation #630

**Comment by dot5enko** [comment]
i claim this

**Comment by dot5enko** [comment]
How about simple textual links-tabs as in https://wallet.bitshares.org/#/accounts. Seems pretty good for me. 
![image](https://user-images.githubusercontent.com/5626922/33621032-3a08ef54-d9f2-11e7-93a7-e6d1b86166e4.png)
I would like to claim this task

**Comment by wmbutler** [comment]
Yeah, I like where you are going. It would basically be just like the Dashboard, but would have the categories listed across the top in the secondary nav bar right?

So, instead of Portfolio/Open Orders/Margin, it would have each explorer category. I think it might be wise to leave off the icons. With icons in the header, I worry it's going to look really busy.

![screen shot 2017-12-07 at 1 39 53 am](https://user-images.githubusercontent.com/1254810/33703887-a8a9fbda-daef-11e7-9db8-295825ac5ef2.png)

**Comment by dot5enko** [comment]
here s what i made
![explorer](https://user-images.githubusercontent.com/5626922/33800700-5c9a1944-dd4e-11e7-86bc-4828177d1c52.gif)

**Comment by handijk** [comment]
I don't really dig the two rows of tabs, turned out to be pretty easy to accomplish in my pull request for the main navigation so i added it here.

![image](https://user-images.githubusercontent.com/646726/33824514-ebb9fe4e-de5e-11e7-8578-14ad61dcce41.png)

![image](https://user-images.githubusercontent.com/646726/33824528-fc4e2de8-de5e-11e7-9b47-821671fb7ef4.png)

Works for mobile navigation too...

![image](https://user-images.githubusercontent.com/646726/33824589-350bd522-de5f-11e7-957d-d40b8945458b.png)
