### ISSUE TITLE
[.25][startailcoon] BTS trade button missing from portfolio view

### ISSUE THREAD

**Issue by jonnybitcoin** [bitshares/bitshares-ui#658]
BTS trade button missing (not enabled) from portfolio view. 
Even when you have a balance.

**Comment by startailcoon** [comment]
I think this is because the trade button on other assets assume you wish to trade that asset towards BTS. Since you can't trade BTS:BTS it's disabled.

The question is what other asset you should wish to come up when you select the BTS trade button.

One solution would be to make the button trade against the selected default unit that the user has. A user that has bitUSD as default unit would get a button to BTS:bitUSD.

A user that doesn't have any default unit would not get a button for trading.

**Comment by wmbutler** [comment]
> One solution would be to make the button trade against the selected default unit that the user has. A user that has bitUSD as default unit would get a button to BTS:bitUSD.

Yes. The user always has a default unit, so this is a great idea.

**Comment by startailcoon** [comment]
I can claim this. May get this done before the release next week

**Comment by wmbutler** [comment]
Awesome. It's yours.

**Comment by happyconcepts** [comment]
#217
