### ISSUE TITLE
[4][diogogomes] Dashboard - Responsive Design, mockup

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#667]
The account dashboard needs a responsive design. It should change to display properly at all resolutions down to an iPhone. Certain fields will need to be omitted as the width decreases and action items will need to be condensed to menus.

Notes:

- [ ] Disregard the side menu and top menus (those will be handled elsewhere)
- [ ] Smallest form factor must display: asset, qty, price, value
- [ ] Trim off decimal precision for FIAT based values
- [ ] action menu hamburger for various buy/trade/deposit options

![responsive](https://user-images.githubusercontent.com/1254810/32195694-03f35300-bd8c-11e7-8c1a-799e447679e4.gif)

**Comment by startailcoon** [comment]
Nice, this has been a real annoyance on my phone  👍

**Comment by magicstone1412** [comment]
Really exciting with this features. I think Responsive Design should implement for all UI. But we need to improve gradually. Will you use BootStrap for doing this @wmbutler? Thank you for your team efforts

**Comment by svk31** [comment]
The GUI uses Foundation for Apps, not Bootstrap.

Tables are quite problematic for responsive designs, I already hide some columns but we'll have to hide a lot more.

**Comment by diogo-gomes** [comment]
### Bitshares Dashboard (mobile prototype)

For the mobile version, I decided to analyze the current layout in 360x640 because it is the most used at the moment in mobile devices.

---

As you can check in screenshoot:

![Dashboard (old)](https://gist.githubusercontent.com/diogo-gomes/9cb700f1deedfea9cf5c4817d8072bf2/raw/b07f40e69cecc42c502f0fa0545e4cc790d1084a/Dashboard%2520360x640%2520(old).png)

- **The Bitshares logo is not present**
- **The user does not realize that he is in the Dashboard**
- **The burger menu is in an area of ​​difficult access to the users**
- **There is plenty of unitilized space (marked orange)**
- **There are tables inside tables**
- **There is no space for all table items**

---

I focused on these aspects and made the following prototype:
(I can also make a mockup but I need the Bitshares Marketing/Color/Font Guide)

![Dashboard - mobile prototype](https://gist.githubusercontent.com/diogo-gomes/9cb700f1deedfea9cf5c4817d8072bf2/raw/7c99c64527fd1ea61ed12e534db30bc2c2cc6259/Dashboard%2520360x640%2520(prototype).png)

- **Replace the menu with the Bitshares logo because it is the zone with less usage in the mobile layout**
- **Moved the burger menu to the right to be easier to access for the user**
- **Included the Dashboard section at the top for the user to know where he is inside the exchange**
- **Inserted a menu with bitUSD/biteur/... which controls the values ​​in which the portfolio will be used. It is located on the left side above the word Asset for the user instinctively relate the two**
- **Entered the My Portfolio/... submenu on the right side below the Burger Menu for the user instinctively relate the two**
- **Removed a lot of unitilized space and decided to use only one table to have more space for the content**
- **Used only horizontal lines in the table for easy visualization on small screens**
- **Reduced the line of each asset only to Asset, Quantity, Price and Value fields**
- **Changed the asset lines themselves to a menu. When the e user click on it, another line will appear with the remaining options**
- **Changed the remaining options of each asset to buttons to distinguish themselves from the other lines when the asset menu is open**
- **Moved Total to the right to align with Value**

Please give your feedback and suggestions.

**Comment by wmbutler** [comment]
@diogo-gomes this is looking very nice. Please track with the latest thoughts on the overall menu as well on #630. Everything you've presented is spot on in my opinion.

- [ ] Default currency can remain hidden in settings
- [ ] Right justify numeric headers, Left Justify Asset Headers

Is 8 hours a fair estimate on this? Do you think you can complete the work by 11/15 or should I move it to 12/01?

**Comment by Ingemkts** [comment]
Hi Bill, there is an exchange that has one of the best GUI I had seen, if not the best. I want to share it with you as I know you are working on the new GUI and it might help. I have traded on it before, it is the best design and performance I had seen, it is a Russian platform, you know russians are the best into the markets, well al least for me. I am not sure if I had shared it with you before. https://www.xbtce.com/en/?type=exchange

**Comment by calvinfroedge** [comment]
Has implementation on this issue been claimed yet? Not sure if @diogo-gomes is handling coding as well or just the UX.

**Comment by diogo-gomes** [comment]
Hi @calvinfroedge,

I already talked to @wmbutler privately by Telegram (I'm sorry, I should have done it here. I'll do it from now on).

**I can't code the implementation because I'm not comfortable with Foundation. I'm more comfortable with Bootstrap.**

I and Bill talked about "turn this into a design issue and then write a follow-up card for the actual work."

**I'll contribute in UI/UX with prototypes/mockups (in high resolution too).**
(I have planned to finish a project this week and spend more time with Bitshares).

@calvinfroedge and @wmbutler, I'm thinking of creating a repository with the design files and share the link here with some screenshots. Can it be?

**Comment by wmbutler** [comment]
We can continue the design process here. But need to limit the scope of each item. Let's keep this to the dashboard including Portfolio, Open Orders, Margin Positions, Activity. I'll allocate 4 hours to it.

**Comment by wmbutler** [comment]
@diogo-gomes can you have mockups finished and posted here in the next day or so?

**Comment by diogo-gomes** [comment]
Yes @wmbutler, I'm doing now.

Can you give your feedback until I finish the others?

### Account / My Portfolio (360x640)
![Account / My Portfolio (360x640))](https://raw.githubusercontent.com/diogo-gomes/bitshares-ui-redesign-proposal/feature/dashboard/BitShares%20UI%20(360x640)/BitShares%20UI%20-%20Account%20-%20My%20Portfolio%20(360x640).png)

#   
### Account / Open Orders (360x640)
![Account / Open Orders (360x640))](https://raw.githubusercontent.com/diogo-gomes/bitshares-ui-redesign-proposal/feature/dashboard/BitShares%20UI%20(360x640)/BitShares%20UI%20-%20Account%20-Open%20Orders%20(360x640).png)

**Comment by diogo-gomes** [comment]
@wmbutler, can we split the activity area from this milestone (without new allocated hours)? There is a lot of information in text and I would like to test multiple ideas.

Which do you prefer first? The activity area for mobile or the other areas for tablet and desktop resolutions?

**Comment by wmbutler** [comment]
Please don't take my comments negatively. I am really impressed with your work.

- [ ] Account should be titled: Dashboard instead
- [ ] I'm not in love with the triangle for the expander
- [ ] You may have to commit 2 rows per open order line since market pairs can be long
- [ ] Really wish we could have a single control for bringing up a drawer/menu containing all the action items instead of all the buttons. It could even be a popup modal with a list in it that could be dismissed. This would be pretty scalable.

**Comment by wmbutler** [comment]
Super rough idea of a modal to accomplish this:

![screen shot 2017-12-02 at 2 10 34 pm](https://user-images.githubusercontent.com/1254810/33519351-a3512d12-d76a-11e7-9274-418a30f2f593.png)

**Comment by diogo-gomes** [comment]
>Please don't take my comments negatively.

Of course not, I need comments/critics to improve my work.

#   
- [X] Account should be titled: Dashboard instead
- [X] I'm not in love with the triangle for the expander
- [X] Really wish we could have a single control for bringing up a drawer/menu containing all the action items instead of all the buttons. It could even be a popup modal with a list in it that could be dismissed. This would be pretty scalable.

I replace the expander and the buttons by the modal on **My Portfolio**, please review:

![Dashboard / My Portfolio (360x640)](https://raw.githubusercontent.com/diogo-gomes/bitshares-ui-redesign-proposal/feature/dashboard/BitShares%20UI%20-%20Dashboard%20-%20My%20Portfolio%20(360x640).png)

![Dashboard / My Portfolio (360x640)](https://raw.githubusercontent.com/diogo-gomes/bitshares-ui-redesign-proposal/feature/dashboard/BitShares%20UI%20-%20Dashboard%20-%20My%20Portfolio%20-%20Modal%20(360x640).png)

_**Maybe the modal needs a title but I don't figure out the best for it. Movements, transactions, actions?**_

---

> You may have to commit 2 rows per open order line since market pairs can be long

Can you explain better this? There are already two lines in the pair. It needs more space between the columns? 

> Really wish we could have a single control for bringing up a drawer/menu containing all the action items instead of all the buttons.

You want to replace the buttons in all areas or only in **My Portfolio**?

**Comment by wmbutler** [comment]
Yes, this modal should have a header identifying:

- Category (Portfolio)
- Asset (BTS)
- Maybe a prompt like: "Action"

> Can you explain better this? There are already two lines in the pair. It needs more space between the columns?

Under the Open Orders, the pair could be very long so I was suggesting that the pair be on line 1 and the rest of the info on line 2.

> You want to replace the buttons in all areas or only in My Portfolio?

I think in all areas for consistency

Looking great!

**Comment by diogo-gomes** [comment]
After add **My Portfolio / (Asset)** the user assumes that a decision/action is necessary. The text "action" becomes unnecessary.

![bitshares ui - dashboard - my portfolio - modal 360x640](https://user-images.githubusercontent.com/9022734/33636318-8ba5d356-da13-11e7-9931-c86eea5c58d4.png)

> Under the Open Orders, the pair could be very long so I was suggesting that the pair be on line 1 and the rest of the info on line 2.

**This way the pair will be between the header of the table and digits. I propose transform each pair into a card.**

I made a new improvements to tablet/desktop resolution before the release of version 171205 and I feel that greater coordination is necessary in the theme, colours, etc.

(**_I'd like to start a design guide (in other issue) to create a greater synergy between design and code._**)

---
## Account / My Portfolio (1024x768)
 ![bitshares ui - dashboard - my portfolio 1024x768](https://user-images.githubusercontent.com/9022734/33636570-a6a9abea-da14-11e7-8471-a5167e6a0f35.png)

#  
##  Account / Open Orders (1024x768)
![bitshares ui - dashboard - open orders 1024x768](https://user-images.githubusercontent.com/9022734/33636640-f3d44920-da14-11e7-9141-b235839d3154.png)

#  
##  Account / Margin Positions (1024x768)
![bitshares ui - dashboard - margin positions 1024x768](https://user-images.githubusercontent.com/9022734/33636664-0cda343e-da15-11e7-8f5b-965699288050.png)

If you want to see the progress, all my files are in the this [branch](https://github.com/diogo-gomes/bitshares-ui-redesign-proposal/tree/feature/dashboard) of this [repository](https://github.com/diogo-gomes/bitshares-ui-redesign-proposal).

**Comment by diogo-gomes** [comment]
@wmbutler, I saw that you change the milestone but it's not necessary.

As I said, with one more line for the pair in Open Orders the pair will be between the header of the table and digits.

### Account > Open Orders (360x640)
 ![Bitshares Ui - Account > Open Orders (360x640)](https://raw.githubusercontent.com/diogo-gomes/bitshares-ui-redesign-proposal/96b3e2d676a366806e497d9f0fb8d3a9a4b84ac7/png/BitShares%20UI%20-%20Dashboard%20-%20Open%20Orders%20(360x640).png)

#  
### Account > Margin Positions (360x640)
Margin Positions (360x640) only have two buttons, it's necessary one modal for this two options?

#  
### Account > Activity
Can we create another issue? I need to explore with the others developers how we can split the lines and what we can cut from each phrase.

#  
### Pull request of design files
I would like to make a pull request with the design files to this repository or a brand new. What you say about create a folder or a repo with the design files for the developers see when they need the sizes of each component?

**If it's everything in order, you can close this issue.**

I await your feedback

**Comment by handijk** [comment]
Yes this is way better than it is now, the amount of buttons on the portfolio page still looks crazy though.
My .02 bitshares; always use the plus sign when there are more than 2 buttons.
When equal to or larger amount than 2 buttons just show the buttons.

Plus sign shows modal on mobile.
Plus sign shows dropdown on desktop.

It will cost you a click on desktop, but in my opinion it outweighs the confusing look of 7 buttons in a row.

**Comment by diogo-gomes** [comment]
@handijk, I agree and I make an alternative to show to @wmbutler:

### Account > My Portfolio (1024x768)
 ![Bitshares Ui - Account > My Portfolio (1024x768)](https://raw.githubusercontent.com/diogo-gomes/bitshares-ui-redesign-proposal/87f5e070c95787da12a97d5ab1da3ae196917c3f/png/BitShares%20UI%20-%20Dashboard%20-%20My%20Portfolio%20(1024x768)%20alt2.png)

# 
> Plus sign shows dropdown on desktop.

I don't know about this. I think I prefer a modal in desktop too.

**Comment by handijk** [comment]
> I don't know about this. I think I prefer a modal in desktop too.

Yes you are right, it could be a dropdown, a modal on desktop is fine too.

**Comment by diogogomes** [comment]
Bill, I change my GitHub username diogo-gomes. Now it's **diogogomes**.

_(I don't know if it's important or not for the name of this issue but I thought I'd better let you know)_

**Comment by wmbutler** [comment]
Thoughts on your mockup... what if we go more this route?

![screen shot 2017-12-28 at 7 28 52 pm](https://user-images.githubusercontent.com/1254810/34427233-8c174b4a-ec05-11e7-92fb-5031eb56ee3f.png)

**Comment by wmbutler** [comment]
![screen shot 2017-12-28 at 8 15 56 pm](https://user-images.githubusercontent.com/1254810/34427832-f41491f2-ec0b-11e7-9511-ded4d606c371.png)

**Comment by wmbutler** [comment]
Closing and will pay for the time you invested in this.

**Comment by diogogomes** [comment]
@wmbutler, do you need a pull request of mockups files to a `design` folder?

**Comment by wmbutler** [comment]
No.

**Comment by wmbutler** [comment]
Please provide your BTS address for payment @diogogomes

**Comment by diogogomes** [comment]
My payment address is diogogomes-eu.
