### ISSUE TITLE
Account::Balances list should show all balances including those that are in open orders

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#69]
_From @steempower on January 13, 2017 5:31_

On the Account tab the 'Balances' list should show all balances including those that are in open orders alternatively another column should be added that shows the assets in open orders. 

Currently if i own 100 x.assets and i have them all in open orders; x.assets does not appear in the my 'Balances' list at all. Another scenario is if i own 100 x.assets and i have 80 x.assets in open orders the 'Balances' list will only show that i own 20 x.assets and not 100. This also effects the estimated account value at the bottom of this list when compared to the account value displayed in the top right hand corner of the wallet.

_Copied from original issue: cryptonomex/graphene-ui#897_

**Comment by landry314** [comment]
this only happens if an open order is holding ALL of an asset and you see "Unknown value" in the equivalent value column. if you leave a little bit (truncate the amount less than 1 BTS) before placing your order then the balance will calculate fine.

this is silly and wastes time. it is also something newbies have to figure out and it is scary to see Balance: 0 at the top. is this bug being fixed?
