### ISSUE TITLE
[.5] Cursor Jumps to End of Maximum Supply Field When Deleting Leading Non-Zero Digit

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#695]
Steps to Reproduce:

1) Go to ACCOUNT -> Advanced Features -> Issued Assets
2) Create Asset
3) Click in Maximum Supply field right after the "1" in "100000"
4) Delete the "1"

This causes the 1 to disappear as expected but then the cursor goes to the end of the remaining "00000" so when the user types a new number to replace the 1 it causes it to be placed as the least significant digit instead of the most... for example, typing a "3" makes it "000003" instead of "300000".

This is not what the user would expect nor what standard text editing rules would dictate.

**Comment by startailcoon** [comment]
This is an issue on multiple places when you input something and removes the leading number. I've had this exact thing happen for me on other places as well. I haven't investigated any further about it though.

**Comment by wmbutler** [comment]
@startailcoon would you like to claim it?

**Comment by startailcoon** [comment]
@wmbutler, sure. I could take this under my wings and see what I can find. I have an idea what it can be about.

**Comment by startailcoon** [comment]
@landry314, can you please provide some information regarding your setup?

**System**: (Linux/Windows/Mac)
**Wallet Type**: (Browser/Installed)

The default is to remove all 0's when you remove the first digit, since the value is not valid, but it doesn't work as expected in the light-wallet on Windows as far as I can tell. Is this your setup as well?

**Comment by landry314** [comment]
@startailcoon, but of course, fellow, raccoon...

Mac OS 10.12.6
BitShares stand-alone application version 2.0.171102.428

**Comment by startailcoon** [comment]
Since different platforms works in different ways, the input field isn't working as expected everywhere. I have the same issue as landry314 on Windows with the light-wallet. While Firefox works in Linux, as well as Edge on Windows.

The supplied PR #696 solves this by adding more control over the input and some more validation instead of relying on the OS/Browser to handle it.

**Comment by startailcoon** [comment]
@wmbutler we should apply this to most of the inputs and extend it to inputs in sections like `Core exchange rate`, `Market fee`, Market: `Price`, `Quantity` for example.
