### ISSUE TITLE
"Windows protected your PC" when installing exe client

### ISSUE THREAD

**Issue by brekyrself** [bitshares/bitshares-ui#701]
windows 10 with the latest client.

Is there a way for this not to pop up when installing the windows client?  I could see this scaring new users away that do not have expert knowledge.  The blue screen pops up with "Don't Run" as the only option unless you click more info at the top.  Once you do this you have to click "Run Anyway" to start installing.

**Comment by wmbutler** [comment]
I don't think we have any control over that.

**Comment by brekyrself** [comment]
Some good discussion here around code signing certificates.  Looks like MS wants developers to purchase these to become part of a trusted environment.  This starts to get over my head however for any standard new user, it may be worth some effort to get rid of this warning.

https://stackoverflow.com/questions/15538925/how-can-i-make-smartscreen-filter-trust-a-self-signed-certificate
https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate

**Comment by apasia-tech** [comment]
Most of the EXE/MSI executables being run under Win7/8/10 are part of UAC (User-Account Control) and they had to be thrown to Admin as potential threats. Especially ones non verified from Microsoft as explained by @brekyrself 

It's safe to be closed, since as @wmbutler said, we have 0 control over the Microsoft reaction to normal builds. 

Many thanks,

Luci.
