### ISSUE TITLE
[.25] SYNC indicator is red

### ISSUE THREAD

**Issue by happyconcepts** [bitshares/bitshares-ui#702]
Should the SYNC indicator (in the bottom right of the footer) be red if I am connected and everything is fine?

![sync-in-red](https://user-images.githubusercontent.com/14145836/32411691-2ecbac8c-c19f-11e7-9c3e-e3d83f6901ec.png)

**Comment by wmbutler** [comment]
It indicates that your latency is bad by being red. I'm not really a fan since there isn't any more detail. I'd suggest we go back to green if it's in sync.

**Comment by startailcoon** [comment]
I can set it to the previous state again. I agree that this is not best practice and since the latency of the nodes aren't working as expected, the underlaying data is not reliable enough for this feature, yet.

I would like to have another section on the left with information regarding the node, this way we have both node and network information. 

Something like this

Connected | Synced
-|-
Responsive | Head Block 120090000

Connected | Out of Sync
-|-
Slow | Head Block 120090000

The node section would then be linked to the Settings -> Access page while the Network section would take you to the Explore -> Network page.

However over the node section would give you the details about the current node you're connect to.

**Comment by btsfav** [comment]
synced is always red in light client for me. webwallets show green...

**Comment by happyconcepts** [comment]
>synced is always red in light client for me. webwallets show green...

Then maybe it is an issue with the light client and how it connects.

**Comment by wmbutler** [comment]
Do we have access to the actual latency data? I love seeing latency and it helps so much when troubleshooting connections. Let's do this:

Connected state:
![screen shot 2017-11-07 at 8 29 44 am](https://user-images.githubusercontent.com/1254810/32498674-eed58ce4-c395-11e7-98bd-8e57abf288a5.png)



Disconnected State:
![screen shot 2017-11-07 at 8 29 37 am](https://user-images.githubusercontent.com/1254810/32498660-e77f29e6-c395-11e7-9ff4-244fc658a406.png)

**Comment by startailcoon** [comment]
We do, but I decided not to include it. The way you suggest is possible to do.

**Comment by startailcoon** [comment]
How about this way?

I'm not really sure if we should change `Sync` and `Out of Sync`.
![bitshares-latency](https://user-images.githubusercontent.com/12114550/32507968-27c4f4c4-c3e9-11e7-97c8-af5363f9b972.png)

**Comment by startailcoon** [comment]
Latency is estimated by these parameters:
- On Connection start, check current time and save it in a parameter
https://github.com/bitshares/bitshares-ui/blob/47ea315f667378769e700027090c2060488ea3db/app/routerTransition.js#L194
- In `onConnect()` we take the current time again and subtract from when we started the connection attempt. 
https://github.com/bitshares/bitshares-ui/blob/47ea315f667378769e700027090c2060488ea3db/app/routerTransition.js#L95

In browsers and slow computers, this will give you a higher number. The light client may be faster in the way it handles this than the browser, which is why some of you have different values on the same computer?

The latency is _only_ estimated on connection and not updated again as far as I understand. The estimation is a simple one and works if there isn't any lag in the functions between initialization and connection process. It's not a real value though.

**Comment by wmbutler** [comment]
I really prefer my UI. Can you go with that instead?

**Comment by startailcoon** [comment]
Based on your layout. How's the font size?

![bitshares-latency3](https://user-images.githubusercontent.com/12114550/32517408-a99e4fc8-c406-11e7-9ca5-4076d45619e6.png)

**Comment by startailcoon** [comment]
As I've said, the latency may not be entirely accurate. If you're pleased with this we can use it, but another possible solution is to change it to "High/Medium/Low Latency" instead.
