### ISSUE TITLE
Parameters in translation strings

### ISSUE THREAD

**Issue by testzcrypto** [bitshares/bitshares-ui#71]
Some strings uses %(param)s parameters like %(account)s, some {account} can we change all parameters to same notations {param}?

**Comment by svk31** [comment]
No, they are different because they have to be. %(param)s is the default interpolation provided by react-translate-component, which only supports pure strings. {param} is an additional interpolation layer used by the TranslateWithLinks component that lets you use actual react components to provide things like links to assets and proper prices.

**Comment by testzcrypto** [comment]
Thanks for clarification.
