### ISSUE TITLE
[2][startailcoon] Count for proposed transactions doesn't match content

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#727]
![screen shot 2017-11-12 at 8 49 31 am](https://user-images.githubusercontent.com/1254810/32700146-9180544e-c786-11e7-9bac-ff5a597cc192.png)

**Comment by svk31** [comment]
Unable to reproduce, need more info. Which account, console errors etc

**Comment by wmbutler** [comment]
Sorry, This account was alpha-cat, but they aren't showing any proposed transactions anymore. I just happened to run across it. Note that the tab "Proposed Transactions" indicates "5", but there are no items listed in the table below it.

**Comment by svk31** [comment]
I can see that in your picture, but that count really is just the count of the number of proposed transactions, so if it says 5 there should be 5 shown inside the tab. The tab also only shows up if there are proposed transactions in the first place, suggesting this was perhaps a node issue or something.

Closing but feel free to reopen if you can reproduce it.

**Comment by wmbutler** [comment]
This will need to be reproduced on the testnet.

**Comment by startailcoon** [comment]
I can claim this, and investigate a bit more on testnet to see if I can reproduce the issue and in that case propose a fix for it.

**Comment by wmbutler** [comment]
Progress?

**Comment by startailcoon** [comment]
Done some testing for this issue and I can not reproduce this either. The code shouldn't allow this to happen.

The tab `Proposed transactions` only show up when there are said actions. If there are x proposals, then x proposals should be visible in the section as well.

Can this be because of a bad node? Where you expecting proposed actions, or not?

I've made 3 proposed actions to `billbutler1001`on testnet, and it seems good to me from here.

![image](https://user-images.githubusercontent.com/12114550/34608541-1325ed3a-f219-11e7-9e41-1896fe7a9b75.png)

At this stage, I don't think there is anything else that I can do to find out what happened for you.

**Comment by svk31** [comment]
Account in props is an immutable object so the inequality should trigger if the properties change. However it's certainly possible its somehow related to the update cycle.

**Comment by startailcoon** [comment]
I'd call this closed until further notice about it. Since we can't reproduce it

**Comment by wmbutler** [comment]
Agreed. Sorry and will pay you for the issue.
