### ISSUE TITLE
[.1] Math is wrong on Worker Proposal

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#737]
See how the first worker daily pay is not deducted from the top line budget.

![screen shot 2017-11-16 at 8 47 55 pm](https://user-images.githubusercontent.com/1254810/32926984-ca4d72a2-cb0f-11e7-9283-2eff621c1dbd.png)

**Comment by svk31** [comment]
On purpose, it shows how much remains for that worker to use.

**Comment by wmbutler** [comment]
If the daily budget is 28,045.09 and there was only 1 worker receiving 1,255.79, would that remaining budget be the same as the daily budget?

**Comment by svk31** [comment]
Yes. If we change it to be the way you're thinking the final worker (as long as the budget is being used up) will always have 0 in the remaning budget column.

In the screenshot you see how there's 25347.02 remaining of the budget for the refund400k worker, so that's how much it'll actually get paid (since it's asking for more than that, but there's not that much available).

**Comment by wmbutler** [comment]
I can honestly say it makes no sense to me. I think I should be able to take a top line number and keep subtracting until it zero's out. I will close this because I'm clearly not bright enough to comprehend this math.
