### ISSUE TITLE
[2] Percentage Indicators on bitassets depth chart

### ISSUE THREAD

**Issue by xeroc** [bitshares/bitshares-ui#756]
In the depth cart of bitassets, we see a line at the settlement price.
Can we also have indications for **percentage offsets**. I am thinking of two mouse following bars (parallel to the settlement) that also show the percentage they are away from settlement price.

**Comment by startailcoon** [comment]
I can take this.

@xeroc you mean the offset should be percentage from markets last buy and sell values, right?

**Comment by wmbutler** [comment]
@xeroc need clarification. See above.

**Comment by startailcoon** [comment]
@xeroc I'm a bit unclear of what your wanting here.

- What do you mean by `two mouse following bars`?
Each bitAsset has it's own defined `Force settlement offset` value USD has 1%, CNY has 5% since recently. Is this what you wish to show?

I know we currently have a few more lines showing when an asset has a force settlement in progress, but there's none now and I can't remember what it is. Do you wish this to be active all the time, or just when we have a forced settlement in progress?

I've made a crude mockup (thank god it's not me doing these most of the time ;))
![bitshares-mockup-offset_li](https://user-images.githubusercontent.com/12114550/34390419-f5661e44-eb3f-11e7-92a0-ce963fb60e45.jpg)

**Comment by startailcoon** [comment]
Today we have `Call Limit`, which I guess is the offset. 
As it's today, these are so close to each other that they merge together. 

![image](https://user-images.githubusercontent.com/12114550/34392809-ce4d94b8-eb4e-11e7-94f1-9879920bd662.png)

**Comment by wmbutler** [comment]
@xeroc I think we still need some input on this.

**Comment by wmbutler** [comment]
@xeroc

**Comment by startailcoon** [comment]
Due to lack of details I'm removing my assignment to this issue

**Comment by wmbutler** [comment]
I'm closing it since we've had no further input.
