### ISSUE TITLE
[1] About migration, sometimes local wallet doesn't be detected so unable to backup?

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#763]
There is a post in forum: https://bitsharestalk.org/index.php/topic,25350.msg312750.html#msg312750

**Comment by wmbutler** [comment]
I suspect this would happen to anyone who partially connected to a socket. @svk31 can we dumb down this process anymore to keep the browser from getting hung up?

**Comment by svk31** [comment]
I guess this might happen if you fail to initialize the app, I suppose we could hardcode some values to simplify the init chain.

**Comment by wmbutler** [comment]
Sorta what I was thinking. In order to download the binary, we don't have to connect do we?

**Comment by svk31** [comment]
In practice we don't, but wallets are linked to a chain id which is why you can have a wallet called default for both the main chain and the testnet for example.

In our case we don't really care about testnet wallets or wallets for any other chains, so we can hardcode the chain id of the mainnet for this specific use case.

**Comment by svk31** [comment]
https://github.com/bitshares/bitshares-ui/commit/0d653a27e0d8806bf586a50666a1aeddbfc290e7
