### ISSUE TITLE
[1.5][nbcks] smartcoin force settlement offset need be shown in the asset detail page

### ISSUE THREAD

**Issue by bitcrab** [bitshares/bitshares-ui#766]
force settlement offset is important information for settlers or shorters to make decison in trading, it should be shown for people to get easily.

**Comment by wmbutler** [comment]
Do you have any suggestions or screenshots? We are currently changing the color of the Margin Positions value and highlighting the affected margin positions. Please be more specific.

**Comment by bitcrab** [comment]
I think we need to differentiate Fed Price and Settlement Price, Fed Price refer to what now is called "Settlement Price", it is just the middle number of the fed prices, Settlement Price(in bit***/BTS format) = Fed Price*(1+offset) .

in the smartcoin asset detail page: show the 3 parameters as below:

![image](https://user-images.githubusercontent.com/5886543/33315860-db2fa91c-d46c-11e7-9f84-a539190bfdda.png)

in the exchange bit***/BTS pair, show the Fed Price and also the Settlement Price 



this can avoid a lot of confusing and misleading

**Comment by startailcoon** [comment]
This is sort of related to #756

**Comment by nbcks** [comment]
I've made a change to the asset page to accommodate the settlement delay and offset, just like cryptofresh. I haven't included the fed price, since personally I think that will very much confuse people. 
![screenshot from 2018-02-05 20-41-22](https://user-images.githubusercontent.com/16877932/35827739-1099537c-0ab5-11e8-8431-bffff2f66fc9.png)

**Comment by nbcks** [comment]
Could I claim this as well please

**Comment by nbcks** [comment]
Submitted a pull request with #1123
