### ISSUE TITLE
[2][pavel-lipcean] UX for Settings

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#787]

**Comment by carolincik** [comment]
Hey William! 

Here is a mock-up for the Settings area. I included lots of new changes - all are related to the previous mock-ups - to keep it all consistent. I am using the same grid as in the dashboard and same UX elements for the inputs / font-sizes and everything else. 

Also, to display a more hierarchic design - I suggest the white color for the area - where the action actually takes place. 

A new feature here is also the Notifications icon - on the top right, we can make it animate. Since to be honest - I couldn't find where users get notified in this dashboard. Notifications can be used to boost up a new help section, some tutorial or update - or even a drop in the currency - users could also set-up their emails to get notified. 

![3](https://user-images.githubusercontent.com/5729949/33572134-bc7ffd14-d93a-11e7-8156-ca4bbab1796c.png)

**Comment by carolincik** [comment]
Also here - you can see that I use the new flag from the new flags I just completed this weekend - all of them round-shaped. I think it will make the users find their language faster. These flags, are specially designed for small sizes - we can place them in a single sprite-file.
 
![flags](https://user-images.githubusercontent.com/5729949/33572613-19ebe73c-d93c-11e7-867a-b010bc3834b9.png)

**Comment by pavel-lipcean** [comment]
Also, Bill, I spent more than 5 hours on this mockup. Can we update the task to reflect that?

**Comment by wmbutler** [comment]
Couple of things:

1. The pay rate is $125 on our hours. I'm used to UX work costing less than $125 per hour, so I could stretch this to 2 hours.
1. I'm not sure if you realize that there are 3 themes in the wallet currently. Your mockup seems to start with the dark theme, but you have a white background displayed. As a UX person, I am hoping you can appreciate that a user who has chosen a dark theme will most likely complain about seeing a bright white area.
1. Also, UX must be iterated on and involve input and comments. In order to avoid hard feelings about effort vs. reward, I think it's also important that these get estimated up front.

If you are able to adapt the color set on this and incorporate it into the latest dashboard look, I'll pay award 2 hours at $125 per hour on this.

**Comment by pavel-lipcean** [comment]
![settings2](https://user-images.githubusercontent.com/5729949/34324822-f56a768e-e887-11e7-9f8c-aedfa76179ad.png)

**Comment by pavel-lipcean** [comment]
All dark Settings plus the white Settings. 

The colors and everything else I can adapt with the css changes if these are accepted. So I am not providing just mock-ups, but will of course cover them with style changes (for some UI elements will need some assistance from Developers);

![white- -dark-mock-ups](https://user-images.githubusercontent.com/5729949/34324868-6ba8340c-e889-11e7-9634-b0fffd52953e.png)

**Comment by pavel-lipcean** [comment]
All dark Settings plus the white Settings.

The colors and everything else I can adapt with the css changes if these are accepted. So I am not providing just mock-ups, but will of course cover them with style changes (for some UI elements will need some assistance from Developers);

I propose in the mock-ups new colors sets, new fonts, new UI elements - and it will serve as a guide-book for the future - like standards to follow. 

Right now, we have more than 5 colors for different call to action buttons and elements - even here on Github you can see they use maximum 2 - green for the buttons and all important UI elements and regular blue for the links. It's consistent, this way the user knows where to focus easily, without any help.

**Comment by wmbutler** [comment]
@pavel-lipcean thanks for the revised color set. Keep in mind that this issue is not intended to be a rework of fonts and controls. It's about making the existing settings more intuitive. Your best bet is to keep the controls the same as the entire site and make a separate issue for "change buttons styles", "change toggle styles", etc. That way you can focus your effort on consistency throughout.

This is really nice work. Thanks.

**Comment by pavel-lipcean** [comment]
Hey, 

got it - will restart it, with the current layout in mind - nothing fancy first, then we will evolve it. I proposed the most futuristic look, just too see where we are headed to.

**Comment by wmbutler** [comment]
The font issue is not one of difficulty for me, it's one of consistency. I think when we are ready to talk fonts, it should be discussed as an overall issue across every endpoint with an appropriate styleguide.

**Comment by pavel-lipcean** [comment]
![all-dark](https://user-images.githubusercontent.com/5729949/34335680-5047436c-e959-11e7-95b3-3a7c2e976021.png)

**Comment by pavel-lipcean** [comment]
![dark](https://user-images.githubusercontent.com/5729949/34335695-774b9382-e959-11e7-8cd4-723baebcd6d6.png)

**Comment by pavel-lipcean** [comment]
Well.. I already worked on it to follow the current fonts and colors and general layout - without any fancy styles.

Here it is^^^

1) I am using a general icons font, that will be consistent (in this case font-awesome) instead of separate svg files. 

2) Changed the CREATE ACCOUNT to be more visible and clear that the user doesn't have an account yet - and that there is the place to Create an Account - right now it is kind of invisible. 

3) Moved the Reset Settings to a separate page, since if we place it at the bottom, it is too easily clicked in my opinion, it looks like a SAVE SETTINGS button - but on a separate page - it is much safer for the users to play with it. 

4) Changed the header icons to some proper icons, since right now, the Explore icon - actually is SERVERS icons - you can see it here: http://fontawesome.io/icon/server/

Then, the Exchange icon, is showing a chart in it - that the dashboard doesn't really have, we have another type of chart. For exchange, it is widely used this icon instead: http://fontawesome.io/icon/exchange/

5) Used Roboto in it, but we can go with Arial for now too - since both are close in style fonts. So either way will work. 

6) Used the current colors for the background and everything else.

**Comment by wmbutler** [comment]
@pavel-lipcean thanks for your time and effort here, really appreciate your work. Any thoughts on how we can integrate the top header like we have with some other areas?

![screen shot 2017-12-25 at 3 05 33 pm](https://user-images.githubusercontent.com/1254810/34342919-1593dd76-e985-11e7-9b97-9852971869be.png)


Keep in mind that the plan is to go to a hierarchical side menu (right side) as the application moves to smaller screens.

**Comment by pavel-lipcean** [comment]
@wmbutler - why right side and not left side them - since on Settings and Help page, the secondary menus are left sided. To keep a consistent user experience..  

On small screens, each secondary menu item would be full-width (on phone screens at least) - while on tablets left sided too. 

Do you need a mock-up for both requests?

**Comment by pavel-lipcean** [comment]
One thing I don't understand, is where the Exchange and Explore go on small screens now? 

![image](https://user-images.githubusercontent.com/5729949/34360967-9a39a530-ea6e-11e7-9c6b-cf7939f687d2.png)

**Comment by wmbutler** [comment]
I'd like to see everything stack into the right menu as the screen gets narrower. I think having a single right menu is easier to support so we don't have to remember right vs left when trying to talk people through issues.

**Comment by wmbutler** [comment]
I like your work on the Help Screen. Seems like we can merge these style guides (particularly the left menu pinned to the left instead of floating to the center).

**Comment by pavel-lipcean** [comment]
Why I chose a floating center Settings menu, was because - the Settings have less content in them so we didn't really needed them presented in full-width. Especially on very-big-screens - having it centered is easier - since you don't have to move the mouse so much! 

Let me see what I can do regarding this, I will also try to stack settings in a right menu all time - will show it to you in a bit..

**Comment by pavel-lipcean** [comment]
Question on this item:

![image](https://user-images.githubusercontent.com/5729949/34452346-fdd2d52e-ed45-11e7-9d54-fa945373a1df.png)

**Comment by pavel-lipcean** [comment]
Question on this item in the Settings Menu:
![image](https://user-images.githubusercontent.com/5729949/34452347-12abc294-ed46-11e7-94e6-a3276e04ed1c.png)

**Comment by pavel-lipcean** [comment]
Here is full-width Settings page, with the menu - far-left:

![1](https://user-images.githubusercontent.com/5729949/34452459-12010082-ed48-11e7-951b-638bd3cb271b.png)

**Comment by pavel-lipcean** [comment]
But I would go with another design solution, to place it in the menu and have it there on all screen sizes, check out how the settings would look like (this is after you clicked the menu icon, and it would come out from the right side):

![2](https://user-images.githubusercontent.com/5729949/34452466-481085bc-ed48-11e7-9f83-7d0af5fd9274.png)
