### ISSUE TITLE
Dynamically updating list of nodes

### ISSUE THREAD

**Issue by testlump** [bitshares/bitshares-ui#854]
Description
-------------
The current list of available nodes is fixed with each build and requires a new release to update. This leads to a lot of new nodes not being listed and the corresponding complaints from users about the non-performance of listed nodes. 

Expected Result
-----------------

Ideally, the list of nodes could be dynamically updated and the accepted resulted pulled from a centralized location in the same way that client update notifications are pushed to the current Bitshares build (171215), perhaps from a centralized github file that is pushed in the same way as notifications for client updates.

**Comment by testlump** [comment]
Can you look to bump this up the priority list? As the userbase increases the performance of default nodes is really struggling leading to a poor user experience and an increasing number of complaints in the Telegram and Reddit channels.

**Comment by wmbutler** [comment]
I don't see this as a high priority. Users can pick a different node if one is performing poorly.

**Comment by testlump** [comment]
How can they pick from nodes that aren't listed? Your response makes no sense.

**Comment by wmbutler** [comment]
Users can add their own nodes. Also, users can issue pull requests to have nodes added and we update the client every 2 weeks.

**Comment by testlump** [comment]
This leaves a two week window during which listed nodes would be overloaded (and this assumes you're going to be releasing builds in perpetuity every two weeks). Why on earth would you not consider implementing a centralized single source for nodes that clients can check and update periodically? It seems entirely irrational to deny such a feature.

**Comment by landry314** [comment]
This is a serious issue, @wmbutler. A lot of people have been having issues with bad or slow nodes. You can't leave users with a bad user experience for a few weeks until an update. It makes sense to have a dynamic list instead of all the nodes hardcoded into each release.

Most users don't know how to find better nodes or add their own. You have to design software for the simple user and have more advanced features available. It is a mistake to write a program and not be thinking this way. We are looking for mass adoption.

**Comment by landry314** [comment]
This issue should be reopened.
