### ISSUE TITLE
Rename Dashboard and Portfolio

### ISSUE THREAD

**Issue by Xeldal** [bitshares/bitshares-ui#858]
A "Portfolio" includes balances, open orders, and margin positions.  

The current "Dashboard" is nothing more than exactly a Portfolio.  

**Action:**
Replace "Dashboard" with the word "Portfolio".
Use the word "Balances" to reference the list of tokens and balances replacing where "portfolio" was.  
that's it... (super simple)

...longer term
As suggested in another of my issues for menu structure(#816).  This change translates to that by having "portfolio" as a menu item on the left (with everything else) under "Wallet" **or** as a top level item next to "Wallet".  

![](https://content.screencast.com/users/Enkianu/folders/Jing/media/4775fbb5-95ac-42db-a3d8-547f747853f4/2017-12-12_2226.png)

Whether or not the pictured left menu is implemented, we stay as we are now, or have something entirely different, the above action makes sense.

As for the "Dashboard".  We don't really have one yet.  The home screen from the "b" is the closest thing we have. In fact it's kind of the same thing. No need to use "Dashboard" yet, or ever maybe.  

Personally I still find myself searching for where to find my balances.  It doesn't logically click to look under "Dashboard".  and then again under "Portfolio"... Both of those words refer to something else.  I think you need to have a logical link to balances very near to the persistent menu if not on it specifically.  It's arguably the most important thing.  While Portfolio may not be a direct link, it is at least better than Dashboard.

**Comment by landry314** [comment]
Everything you said is exactly right.

The naming of things has been weird for a long time and the people who are deciding the naming don't seem to care... it is a shame because it DOES matter what things are called.

the "b" menu doesn't make sense to be called a letter. It is not clear what it is.

The portfolio is certainly not a dashboard. The list of only balances not in open orders or held as collateral is certainly not a portfolio.

Unfortunately, this issue will get nowhere...

**Comment by sschiessl-bcp** [comment]
Included
