### ISSUE TITLE
[5][gibbsfromncis] Implement Settings UX

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#904]
## See UX here
https://github.com/bitshares/bitshares-ui/issues/787

**Comment by GildedHonour** [comment]
Will it be ok if I take this one?

**Comment by wmbutler** [comment]
Yes, please be sure to carefully read the end of this issue. As you can see, the UX did not get fully refined until the end. Also, carefully read my comments. This issue will be paid:

- 3 * $125 = $375
- If the PR is accepted

If this takes over 3 hours, be sure to discuss here so we can increase as needed.

**Comment by GildedHonour** [comment]
Got it. 
Many of the paid issues have some activity in them implying that they're being worked on. Which ones are free for me to take?

**Comment by wmbutler** [comment]
Anything without a name in the header or a Github Assignee are free for you to claim.

**Comment by GildedHonour** [comment]
I'll take a look at it this week I think.

**Comment by wmbutler** [comment]
Can you have it ready to test by 04 Jan 2018?

**Comment by GildedHonour** [comment]
I can't promise that.

**Comment by wmbutler** [comment]
I'll remove your claim them. Please only claim items that you can complete during the current Sprint.

**Comment by GildedHonour** [comment]
does the Sprint have the dates assigned to each issue to complete it within?

**Comment by Kennybll** [comment]
Question, what about light and midnight theme?

**Comment by wmbutler** [comment]
>does the Sprint have the dates assigned to each issue to complete it within?
MIlestone YYMMDD represents the due date. Moving this to the next Sprint.

>Question, what about light and midnight theme?
The colors are variables for each theme I believe.

**Comment by gibbsfromncis** [comment]
@wmbutler I have read all comments and took a look all mockups. Could you answer please, which of the mockups should be implemented?

a) https://github.com/bitshares/bitshares-ui/issues/787#issuecomment-354533138 (I like this one because It looks more freely and I think the user settings it's not a thing which should be available on all screens)
b) https://github.com/bitshares/bitshares-ui/issues/787#issuecomment-354533211 (It looks interesting but for another cases, not for Settings. I will keep this idea on my mind. Maybe sometimes we find a feature for this style of the menu)

It depends on my free time I should have to work on this task to make sure I can complete this in the upcoming Sprint.

**Comment by wmbutler** [comment]
Go with a) full width. Ultimately, the settings menus should be part of the hierachical nav under the right burger once that gets worked.

**Comment by gibbsfromncis** [comment]
@wmbutler what do you mean about "should be part of the hierarchical nav" ?

**Comment by gibbsfromncis** [comment]
@wmbutler As I see I should just update the design of Settings, right? Just get Settings inside some dark (based on theme) block and change fonts sizes, fonts colors, paddings and that's it? 

The title of issue made me confused because I don't see any changes to UX. Only changes related to UI. 

Do I understand the task correct?

**Comment by wmbutler** [comment]
Yes, this was mostly a UI task. Ultimately, we will have a right nav bar under the burger that is hierachical. In otther words, it will contain all of the cascading menus and options available. The second graphic showed them on the left, but it will in fact be on the right as part of a larger plan to consolidate the nav for smaller devices.

**Comment by gibbsfromncis** [comment]
@wmbutler my point of view as a user - if I click on somebody's username I can take a look his account info and that's it. I don't want to assume the role of this user.

It's like on social networks - if you click on Mark Zuckerberg name somewhere you can take a look his profile and more data about this man. And that's it. You are not going to be this user and see his profile as yours. 

Is this the feature? If yes, why it works only for users with wallet account? And what is the main idea of this feature? 

Because mostly it looks like a bug for me.

**Comment by wmbutler** [comment]
I agree on all counts. Thanks.

**Comment by gibbsfromncis** [comment]
@ahdigital hey. I'm going to work on burger menu again and make it hierarchical. Does it conflict with our task too?

**Comment by ahdigital** [comment]
No, go ahead. :)

**Comment by gibbsfromncis** [comment]
@ahdigital thanks man ;)

**Comment by gibbsfromncis** [comment]
@wmbutler I've done first two options. The last one requires more work on Settings Router and Dropdown:
1) I should change router of Settings (now all tabs located on /settings url). I should change router so any pages on mobile can be accessed by url `/settings/access`, `/settings/local-wallet` etc.) to put those link on Hamburger. Because now is no way to redirect user to specific settings tab.
2) I should implement new Hamburger menu for mobile devices and show it on specific media point (for e.g. device_screen_width < 600px). 

I did review of what we have now and I need additional time to implement these changes. Can we increase estimate to at least 5h?

Btw there are screenshots of new Settings Design (I did some refactoring because some UI elements didn't use the same styles. I didn't have some colors for Midnight & Light themes so I've chosen them by my opinion) :

<img width="954" alt="screenshot 2018-02-13 15 56 52" src="https://user-images.githubusercontent.com/35899973/36156943-e7c26a04-10d8-11e8-9d99-9fd137113d79.png">
<img width="954" alt="screenshot 2018-02-13 15 56 42" src="https://user-images.githubusercontent.com/35899973/36156944-e7de4954-10d8-11e8-8ccf-1a5648f343bb.png">
<img width="954" alt="screenshot 2018-02-13 15 56 20" src="https://user-images.githubusercontent.com/35899973/36156945-e8397e1e-10d8-11e8-9fc1-5fe50b2d3b12.png">

(Minor change of nodes border-colors)

<img width="1093" alt="screenshot 2018-02-13 16 14 48" src="https://user-images.githubusercontent.com/35899973/36157114-5686f568-10d9-11e8-80df-49d8d9a01299.png">

<img width="1095" alt="screenshot 2018-02-13 16 14 35" src="https://user-images.githubusercontent.com/35899973/36157115-56a39736-10d9-11e8-80fa-341a52a0b013.png">

<img width="1094" alt="screenshot 2018-02-13 16 14 20" src="https://user-images.githubusercontent.com/35899973/36157116-56c5df12-10d9-11e8-9894-61619ab60a58.png">

Feel free to comment changes - maybe you want me to revert/add/fix something.

**Comment by gibbsfromncis** [comment]
@wmbutler 
I didn't wait for your approve/response and immediately began to work. 

This is result of sub menu:

![gif-hamburger-submenu](https://user-images.githubusercontent.com/35899973/36172982-e031343a-1107-11e8-8ec4-b6df6185029c.gif)

It's not awesome from design perspective but if you want we can open new issue about Menu & Sub menu redesign. 

Also I've put "idea" of submenus for menu. So it will be so easy to create submenu for any another menu item. 

I decided to use `990px` breakpoint to hide Settings Menu and show it as submenu on Hamburger. You can test it by yourself and if you want I can change it.

**Comment by wmbutler** [comment]
Looking really good and placing us on the right path for submenus.

**Comment by ahdigital** [comment]
Just wondering why we couldn't have been consistent with #1107 that was recently closed.

I like the sub menu you've done but don't think the UX is right for this specific use case.

**Comment by gibbsfromncis** [comment]
PR: #1164

**Comment by gibbsfromncis** [comment]
@wmbutler as I told above I would be glad if you can increase estimate for at least 1 hour of this task. It took almost 2 days to make everything looks production-ready and cool.

**Comment by wmbutler** [comment]
I added 2.
