### ISSUE TITLE
[2][gibbsfromncis] Scan QR Code - Library Installs

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#999]
https://github.com/lwansbrough/react-native-camera
https://github.com/moaazsidat/react-native-qrcode-scanner

**Comment by startailcoon** [comment]
What's the status of this?

Issue #998 and #832 depends on this.

**Comment by wmbutler** [comment]
Nobody has claimed it yet so it site here until that happens.

**Comment by startailcoon** [comment]
Sorry, for some reason I thought I saw svk to be assigned to this.

**Comment by wmbutler** [comment]
I probably did that since he's usually the one to add new libraries.

**Comment by gibbsfromncis** [comment]
@wmbutler I can take it.

**Comment by gibbsfromncis** [comment]
@startailcoon all provided libraries are for react-native. As I see from our repository we do not have/do not support react-native. I see we have "wrappers" for Desktops only (Electron). But no any wrappers for Mobile platforms like phonegap/react-native. So I'm confused why did you select those libraries to use. 

Can you explain the cases of usage QR codes in bitshares so I can help you to find solution?

**Comment by wmbutler** [comment]
We can display QR codes already, but we need to allow the wallet to access the camera on mobile devices and desktops to be able to recognize qr codes.

**Comment by startailcoon** [comment]
> So I'm confused why did you select those libraries to use.

I'm not versed in libraries for react and was only browsing for a solution when I found these as possible solutions. Hence the reason I needed some help analysing if they indeed could be of use.

I assume we need to look further for a solution.

We're looking for a solution to scan QR codes to ease input of form data in the wallet.

**Comment by gibbsfromncis** [comment]
@wmbutler @startailcoon okay, I got your feedbacks. 

We're not able to use the libraries you've provided. Actually we're not able to even install these libraries because them are for Mobile Devices (android/ios packages) so thats why you were confused how to install them.

@wmbutler 
What we can do:
1) Add button "Select QR code"
2) User press on it and sees dropdown menu like with few options (based on mobile OS): Select Photo or Take Photo using Camera.
3) User selects photo/or shot it by camera 
4) If code recognized well he sees the success message.

This is a little sample of idea how it works: 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/35899973/35990794-86ea91d8-0d05-11e8-847f-e78fa1475263.gif)
(Library, Demo - you can test it by your smartphone) (Do not worry about Design, we will remove all UI except button "Select QR code")

Sometimes code cannot be recognized and user should take new photo from another angel. Unfortunately we cannot make user be able to move his camera till QR code not recognized like on Native iOS/Android apps because this is web and we cannot have direct access to camera. 

@startailcoon We will go by this way: I'll create an React Component called QRScanner. This will present only one button with few props like "onQRRead", "buttonLabel" etc. and you will use it anywhere in our app where you need. How does it sound for you? Btw I do not have time to make it today/tomorrow so I will prepare on weekend and let you know when my pull request be pushed.

**Comment by wmbutler** [comment]
Is there a way to handle this as a video grab rather than as a photo? Or is it possible to trigger the photo and submit it automatically based upon qr code detection?

**Comment by wmbutler** [comment]
I'm thinking since we are so Chrome heavy, we may be able to get away with saying "For the best experience, use chrome". It's free and it's universal. There isn't much reason for someone to push back. Unless they are just a contrarian for the sake of it. I think it's important to focus on getting the experience right and compatibility can be added later.

**Comment by gibbsfromncis** [comment]
@wmbutler as I said your way about QR code scanning can work only for Desktop Chrome. Now I'm confusing why are you going to scan QR codes on Desktop? 

If we are talking not about this feature only so we can go by your way. It's OK. But lets keep our project supported by another browsers too. Cool product cannot be fully supported by only one browser so someday we will start to work on another browsers support and this will be hard work. So I want to propose if we have situations where Chrome support some cool feature and another browsers not - lets make 2 versions of feature - cool for Chrome users and simple-hack for another browsers. If we have some feature on Chrome we should have the same feature on another browsers. Maybe on another browsers this feature will looks not so cool but we should have it. For e.g. I think it's bad way to say users - if you want to scan QR codes - use Chrome only. But we can add some little text on another browsers under the scan button "You can use Chrome to capture QR code automatically except making a photo.

**Comment by wmbutler** [comment]
@gibbsfromncis interesting, because Mobile Chrome has a way to scan QR codes natively.

**Comment by gibbsfromncis** [comment]
@wmbutler interesting, can you give me some example or link to test it? I use chrome on my iPhone and never seen this feature.

**Comment by wmbutler** [comment]
When you pull down to search via mobile Chrome, they offer a control to capture a QR code. It's next to the microphone control.

![img_ad233f3450c8-1](https://user-images.githubusercontent.com/1254810/36063093-16a666d8-0e3e-11e8-812d-ce94c67c2052.jpeg)

**Comment by gibbsfromncis** [comment]
@wmbutler yep, I know about this one. But this is only for scanning links encoded in qr codes. This one can't help us :)

**Comment by gibbsfromncis** [comment]
@wmbutler I've created my own library for eact app to recognize QR codes and it works awful. Recognizing QR by image works really really bad. 

@startailcoon @wmbutler **new idea:** 

We can pass needed params into url for QR code. On this way user be able to use his phone default features for scanning QR codes. 

@wmbutler on this way you will be able to pull down your Chrome, scan QR code by chrome feature and go by link to (for e.g.) https://wallet.bitshares.org/#/transfer-money?param1=a&param2=s etc.

User Experience:
1) User sees some QR code he need to scan on Desktop to pay someone by bitshares
2) User take his phone and 

@wmbutler Can you please describe me an idea of how QR codes should work? Who/where place QR codes? What will be if I scan QR code? I suppose I don't understand this feature at all. I don't understand why do you need QR code scanner for Desktop and how do you imagine this UX.

**Comment by gibbsfromncis** [comment]
@startailcoon please take a participant on our discussions. I appreciate your opinion and your help. Maybe you have some good another ideas or my idea suits for you well?

**Comment by gibbsfromncis** [comment]
@wmbutler @startailcoon this is simple example of my new idea:
![ezgif com-video-to-gif 3](https://user-images.githubusercontent.com/35899973/36074062-d79a0f3c-0f3a-11e8-93cc-1d099913cf3c.gif)

User scans QR code somewhere. Then he goes by link in QR code. All parameters what we need should be hardcoded in QR code url like:
1) Amount of transaction 
2) Transaction Receiver
etc.

**Comment by gibbsfromncis** [comment]
Example from Chrome:

![ezgif com-video-to-gif 4](https://user-images.githubusercontent.com/35899973/36074121-d3e0725e-0f3b-11e8-9b7b-56f6a39cce3b.gif)

The main this is we should do: put transaction params into URL and when user go to page like:

`https://wallet.bitshares.org/#/transfer?to=billbutler&amount=500&asset=1.20.123`

We should fill all fields on the page using info from the url. So user just should check data and press "send"

**Comment by wmbutler** [comment]
These are great ideas. To answer your question, it's important that we be able to scan a qr code from within the web app as well. If the QR code references a full wallet URL, this will ultimately not be scalable because it will rely on a user going to a particular domain. It also forces a browser to load the entire source.

We have begun to put into place some ideas for the QR code side of things regarding the parameterization of the QR code. There is a fairly well framed pattern for bitcoin and we have a precedent for bts as well.

https://github.com/bitshares/bitshares-pay/issues/1

If you think about it, when you see a qr code, you generally first decide which wallet you want to use to send and then you open it and would choose send. From send, you would have the option of either entering the address and amount manually or scanning a QR code.

Remember though, this issue is about the library installs, not defining the standard by which this will operate. I expect a URI for bts will look like:

payment request is just ONE use case. it should be like this:

````
bitshares:payment/request?account=account&amount=1&asset=1.2.3&memo=memo
````

for adding to address book

````
bitshares:add/to/address/book?account=account&memo=memo
````

we should list all possible use cases and define their paths and query params.

**Comment by gibbsfromncis** [comment]
@wmbutler Unfortunately I don't know the better way to work with QR codes from mobile browsers because I'm looking for crossbrowser stable library. 

Libraries provided on top cannot be installed because them for Android/iOS - not WEB. 

Libraries for React (not React-Native) make a photo and try to recognize and decode QR code but all of them which I've tested recognize QR codes really bad. One of them I've found works like you mention above - [https://thomasbilliet.com/react-qr-reader/](https://thomasbilliet.com/react-qr-reader/). But it doesn't work for iOS Chrome. It works only for Safari. Idk does it work for Android browsers or not. 

Safari on iOS not supported at well for now. Actually I cannot restore my wallet in Safari...

Solution I told above is crossbrowser and can be supported even by Windows Phone 😃 

Do we have some cool guys who may propose for us any another solution that maybe suits your requirements?

If you disagree my idea you can unassign me from this task and lets wait for somebody who can propose better way because I suppose I did all my best.

**Comment by wmbutler** [comment]
I reviewed the libraries for this. I think taking a picture rather than having live video should work just fine. It's a really nice compromise until the video can be accessed natively.

Was this the library you were suggesting?

https://github.com/LazarSoft/jsqrcode

**Comment by gibbsfromncis** [comment]
@wmbutler yes but it's hard to integrate it for React app. I guess this one is better - https://thomasbilliet.com/react-qr-reader/

**Comment by wmbutler** [comment]
That looks great...

**Comment by wmbutler** [comment]
Advancing this. Plan to add the library?

**Comment by gibbsfromncis** [comment]
@wmbutler oh yes. I forgot about this issue.

**Comment by wmbutler** [comment]
I'm really hoping there is a way to do this without reloading the UI web application. Ideally, we can capture the contents of the code and send the result to the withdraw modal first. Would be nice to work on withdraw for alternative currencies for now since we don't have much consensus on the URI scheme for BTS.

**Comment by gibbsfromncis** [comment]
@wmbutler This task is only for library install. As additional thing I will create some `<QRCodeScanner/>` component which guys who work with QR codes can use on our app.

**Comment by gibbsfromncis** [comment]
@wmbutler I've added "QRScanner" component so anyone developer can use it. It's a button and when  user click on it modal with camera appears. User can close it manually or it closes when QR scanned success. 

Video - https://drive.google.com/file/d/1BnG3aig0t6X7BKioIDdun7vMZuaL0bBi/view (sorry, service for video converting into gif is unavailable right now)

**Comment by gibbsfromncis** [comment]
@startailcoon When you start to work on QR codes please make sure you use HTTPS server (https://localhost:8085) instead of http because mobile browsers policy disable camera on http.

**Comment by gibbsfromncis** [comment]
PR #1355
